var L = [
    "",
    "Humano",
    "Bestia",
    "Enano",
    "Elemental",
    "Elfo",
    "Goblin",
    "Monstruo",
    "No Muerto",
    "Constructo",
    "Planta",
    "Gnomo",
    "Dios Antiguo",
    "Saurónido",
    "Demonio",
    "???",
    "Luchador",
    "Mago",
    "Arquero",
    "Héroe",
    "Multiclase",
    "Seguidor",
    "Frente",
    "Atrás",
    "-",
    "Ataque",
    "Vida",
    "Velocidad",
    "Muerte",
    "MUERTE: Hace algo después de morir.",
    "Final",
    "FINAL: Hace algo cuando todos los personajes terminaron de atacar. Ignora el agotamiento.",
    "Redoble",
    "REDOBLE: Hace algo luego de un ataque normal.",
    "Ruina",
    "RUINA: Se activa cuando muere un personaje enemigo.",
    "Brío",
    "BRÍO: Se activa cuando aumenta la vida de un personaje aliado.",
    "Ardid",
    "ARDID: Se activa si el personaje no ataca.",
    "Preludio",
    "PRELUDIO: Se activa antes del inicio del combate.",
    "Ritual",
    "Ritual X: Gasta X almas para activar una habilidad entre rondas. Se puede usar una vez por ronda. Clic derecho para activar.",
    "Veneno",
    "VENENO: Los personajes envenenados reciben 1 de daño después de un ataque normal. Dura hasta el final del combate. No se acumula.",
    "Maldición",
    "MALDICIÓN: Se duplica el próximo daño que reciba el personaje.",
    "Escudo",
    "ESCUDO: El próximo daño que el personaje reciba se anula.",
    "Contra",
    "CONTRA: Hace algo cuando el personaje pierde vida y sobrevive.",
    "Aflicción",
    "AFLICCIÓN: Los personajes con aflicción no ganan vida, armadura o poder. Se pierde una carga de aflicción cuando termina un turno del personaje.",
    "Poder",
    "PODER: El próximo ataque inflige más daño.",
    "Armadura",
    "ARMADURA: La cantidad de daño que un personaje puede recibir antes de perder vida. La armadura se pierde al final de cada ronda.",
    "Sacrificio",
    "Sacrificio X: Recibe daño para activar una habilidad entre rondas. Se puede usar una vez por ronda.clic derecho para lanzar.",
    "Revivir",
    "Revivir: Revive con 1 de vida a un aliado muerto.",
    "Maná",
    "Maná:nGasta maná para activar una habilidad entre asaltos. Puede usarse una vez por asalto. Clic derecho para lanzar.",
    "Invocación",
    "Los personajes que invocan y se benefician de las invocaciones son más frecuentes en los campamentos.",
    "Nivel",
    "Sobrenivel",
    "Este personaje puede subir de nivel infinitamente. Obtiene esta bonificación a nivel 4 y cada nivel posterior.",
    "camino",
    "héroe",
    "artefacto",
    "personaje",
    "articulo",
    "mejora",
    "monstruo",
    "grupo",
    "Campamento",
    "Recluta o despide personajes. Haz clic derecho para desequipar objetos.",
    "Hoguera",
    "Las hogueras tienen más personajes para elegir que un campamento. Desbloquear unidades nuevas desbloquea hogueras nuevas.",
    "Cofre de Tesoro",
    "Se transforma en un objeto aleatorio.",
    "Sala de Tesoro",
    "Ganas 3 de oro.",
    "Bathin",
    "Bathin ofrece tratos opcionales que aumentan la dificultad del próximo combate a cambio de oro.",
    "Mercader",
    "Compra y vende objetos. Haz clic derecho para desequipar objetos.",
    "La Bruja",
    "¡Tú! ¡Tengo más pociones a la venta!",
    "Andromalius",
    "Andromalius transforma una pieza de equipamiento.  Haz clic derecho para quitar el equipamiento de un personaje y luego coloca el equipamiento en el Vacío.",
    "El Cerrajero",
    "Oh. Hola. ¿Necesitas llaves?",
    "El Gigante",
    "Elige un anillo.",
    "Contrabandista",
    "El mercado negro vende objetos a menor precio que las tiendas comunes.",
    "El Mago Perdido",
    "¿Un anillo de obsidiana? ¿Puedo verlo? Se parece a uno que perdí hace mucho tiempo.",
    "Sala de Tesoro de Aamon",
    "Aamon ofrece anillos malditos. La maldición depende del héroe actual.",
    "Cofre de Artefactos",
    "Elige un artefacto.",
    "Elige tu héroe",
    "Sangre de Abaddon",
    "Ganas 8 de oro.",
    "Sangre de Illifar",
    "Recibes un personaje nivel 2.",
    "Sangre de Nazzatoth",
    "Recibes un objeto raro.",
    "Alma del Guardián",
    "El límite de tu grupo aumenta en 1. La vida máxima de tu héroe es 1 para siempre.",
    "Canción de la Muerte",
    "+25% de puntuación Los héroes enemigos ganan 1 de ataque.",
    "Nueva partida",
    "Nueva partida+1",
    "Nueva partida+2",
    "Nueva partida+3",
    "Nueva partida+4",
    "Nueva partida+5",
    "Leyenda",
    "Todas las zonas",
    "La Mazmorra Superficial",
    "El Subsuelo",
    "El Abismo",
    "El Portal",
    "La Torre",
    "Vaya alma sin suerte",
    "El Aventurero Perdido",
    "Clamabanquetes",
    "{kw-followup}: Un aliado herido recupera 2 de vida.",
    "Líder de la Manada",
    "Objetivo: el enemigo con menos vida.",
    "Noble de la tierra antigua",
    "Thoric del Martillo",
    "{kw-endofround}: gana 1 de armadura.",
    "Maestro herrero",
    "{kw-endofround}: el aliado en el frente de esta fila gana 1 de armadura.",
    "La última astrónoma",
    "Eloa",
    "{kw-followup}: un aliado en esta fila gana 1 de {kw-charge}.",
    "Inagotable.",
    "Investigadora arcana",
    "{kw-endofround}: un mago aliado en esta fila gana 2 de {kw-charge}.",
    "De la luna antigua",
    "Taz'gyn",
    "{kw-channelmana} 2: invoca un {kw-summon:0}.",
    "Invocador ascendido",
    "Si este personaje elimina un enemigo, invoca un {kw-summon:1}.",
    "Taz'gyn, de La Orden",
    "{kw-otherunitdies}: gana 1 de {kw-charge}.",
    "El chef ambulante",
    "Dominique Boutroux",
    "{kw-followup}: cura 1 de vida a un aliado herido en esta fila.",
    "El mercader ambulante",
    "{kw-startofbattle}: ganas 1 de oro.",
    "Quien nada en soledad",
    "Cacique Gryx",
    "Cuando un aliado muere, ataca.",
    "Matriarca del nido",
    "Veneno.",
    "El joven príncipe",
    "Xandos III",
    "Empieza con {kw-relic:51}.",
    "Xandos, el Grande",
    "Conocimientos errantes",
    "Mariana",
    "{kw-startofbattle}: invoca a {kw-summon:2}.",
    "Animara",
    "Cuando se realiza un sacrificio, gana 1 de {kw-charge}.",
    "Del más allá",
    "Elsbeth",
    "{kw-channelsoul}1: inflige 2 de daño al enemigo más cercano. Almas máx. +1.",
    "Elsbeth, la Bruja del Pantano",
    "{kw-startofbattle}: envenena a dos enemigos aleatorios.",
    "La vengadora",
    "Empieza con {kw-relic:47}.",
    "Emperador dorado",
    "Gana 1 de ataque por cada 5 de oro.",
    "La artificiera",
    "Empieza con dos reliquias aleatorias adicionales.",
    "Cieno Regenerante",
    "Cuando un aliado muere, recupera 1 de vida.",
    "Limo Replicante",
    "{kw-counter}: invoca dos {kw-summon:42}s.",
    "Cieno Metálico",
    "{kw-endofround}: gana 1 de armadura y luego se mueve.",
    "Arúspice",
    "{kw-otherunitdies}: inflige {kw-scaling:1/1/0} de daño a un enemigo aleatorio.",
    "Sectario",
    "{kw-otherunitdies}: recupera {kw-scaling:1/0/0} de vida.",
    "Berserker",
    "{kw-counter}: gana 1/2/3 de {kw-charge}.",
    "Danzaespadas",
    "Gana 1/2/3 de ataque si tiene toda la vida.",
    "Hechicero",
    "{kw-endofround}: todos los magos aliados ganan 1 de {kw-charge}.",
    "Cazador",
    "{kw-followup}: inflige/ataca dos veces por/ataca tres veces por 1 de daño al enemigo con menos vida.",
    "Forjador",
    "{kw-endofround}: un aliado en esta fila gana {kw-scaling:1/1/0} de armadura.",
    "Mago del Sol",
    "Gana el doble de {kw-charge}.",
    "Clérigo de la Senda",
    "{kw-followup}: un personaje aliado recupera {kw-scaling:1/0/0} de vida.",
    "Clérigo de la Rosa",
    "{kw-healthisrecovered}: inflige {kw-scaling:1/0/0} de daño al enemigo más cercano en esta fila.",
    "Caballero con Armadura",
    "Tiene ataque adicional igual a su armadura.",
    "Druida",
    "{kw-channelmana} {kw-scaling:0/1/1}: invoca una {kw-summon:6/7/8} dos veces.",
    "Protector Divino",
    "Cuando se invoca un aliado, le otorga {kw-shield}.",
    "Escudero",
    "{kw-endofround}: un aliado en esta fila gana 1/2/3 de {kw-charge}.",
    "Aguatilis",
    "Cuando un aliado muere, gana 2/3/4 de {kw-charge}.",
    "Hipogeo",
    "{kw-scheme}: recupera 1 de vida por cada saurónido aliado.",
    "Montaraz",
    "Cuando se invoca un aliado, gana 1/2/3 de {kw-charge}.",
    "Adepto de Fey",
    "Los aliados invocados ganan {kw-scaling:1/0/0} de ataque.",
    "Ladrón",
    "Curtidor",
    "Si este personaje elimina un enemigo, ganas 1 de oro.",
    "Guardia Real",
    "Cuando este personaje recupera vida, tu héroe gana 1/2/3 de {kw-charge}.",
    "Canalizante",
    "{kw-followup}: activa todos los efectos aliados de ruina.",
    "Jabalinero",
    "Ataca tras ganar armadura.",
    "Tirador",
    "Cuando un enemigo recibe {kw-poison}, le inflige {kw-scaling:1/0/0} de daño.",
    "Praexator",
    "Cuando este personaje elimina un enemigo, todos los saurónidos aliados ganan 1 de {kw-charge}.",
    "Adepto del Rayo",
    "Cuando este personaje gana {kw-charge}, inflige {kw-scaling:1/0/0} de daño a un enemigo al azar.",
    "Invocador de Acero",
    "{kw-channelmana} {kw-scaling:0/1/1}: invoca un {kw-summon:12/13/14}.",
    "Clérigo de la Oscuridad",
    "Cuando este personaje elimina un enemigo, gana {kw-shield}.",
    "{kw-channelmana} {kw-scaling:0/1/1}: Obtienes {kw-shield}.",
    "Sanguinista",
    "{kw-endofround}: invoca un {BloodSummon] enemigo en esta fila.",
    "Carnicero",
    "Cuando este personaje elimina un enemigo, un personaje aliado herido recupera 1 de vida/ dos veces/ tres veces.",
    "Zampaponsoña",
    "Recupera {kw-scaling:1/0/0} de vida cuando un personaje envenenado muere.",
    "Clérigo del Martillo",
    "{kw-endofround}: invoca un {kw-summon:16/17/18}.",
    "Maestro Cervecero",
    "{kw-counter}: cura 2 de vida a un personaje aliado.",
    "Tallarunas",
    "Cuando otro enano recibe daño, gana 1 de {kw-charge}. {kw-endofround}: gana 1 de armadura por cada enano.",
    "Tirador",
    "1 de daño adicional por cada aliado no muerto.",
    "Guardia de Tarus",
    "{kw-channelsoul} 1: otorga a los aliados no muertos 1/2/3 de armadura. Almas máx. +1.",
    "Bebealmas",
    "{kw-endofround}: si tienes 2 o más almás, recupera {kw-scaling:1/0/0} de vida. Almas máx +2.",
    "Adepto Caído",
    "{kw-channelsoul} X: inflige /2/4X de daño al enemigo más cercano en esta fila. Almas máx. +3.",
    "Necromante",
    "{kw-channelsoul} 2: invoca un {kw-summon:3}. Almas máx. +2.",
    "Sangre Férrea",
    "{kw-channelblood} 1: gana 1 de armadura por cada aliado herido.",
    "Sangre Carmesí",
    "{kw-channelblood} 2: gana 1 de ataque.",
    "Heliocuerno",
    "{kw-channelblood} 1: cura 1 de vida /dos veces/tres veces a una bestia adyacente herida.",
    "Oso Bélico",
    "{kw-endofround}: si este personaje tiene 1 de vida, recupera 1/2 o menos de vida, recupera 2/3 o menos de vida, recupera 3 de vida.",
    "Adepto del Fuego",
    "También daña enemigos en la misma columna.",
    "{kw-channelmana} {kw-scaling:1/0/0}: ataca.",
    "Artificiera",
    "{kw-endofround}: si este personaje tiene {kw-charge}, invoca una {kw-summon:20/21/22}.",
    "Conducto de la Furia",
    "{kw-counter}: ataca.",
    "Cazador Nocturno",
    "{kw-otherunitdies}: gana 1/2/3 de {kw-charge}.",
    "Venomante",
    "{kw-followup}: inflige {kw-scaling:1/0/0} de daño a todos los enemigos envenenados.",
    "Praliador",
    "Este personaje ataca de nuevo si elimina un enemigo.",
    "Bruja Venina",
    "Inflige el doble de daño a enemigos envenenados.",
    "{kw-channelmana} {kw-scaling:1/-1/0}: Invoca un {kw-summon:9}.",
    "Sanguijuela de Sangre",
    "{kw-otherunitdies}: invoca un {kw-summon:10/11}.",
    "Arquero Arcano",
    "{kw-endofround}: los magos en esta columna ganan 2/3 de {kw-charge}.",
    "Asesino",
    "Los enemigos reciben {kw-scaling:1/-1/0} de daño adicional por veneno.",
    "Maeledox",
    "Cuando este personaje gana {kw-charge}, también gana {kw-shield}. {kw-scheme}: aplica {kw-weaken} al enemigo más cercano.",
    "Hidalgo",
    "{kw-followup}: activa todos los efectos de {kw-counter} de los personajes adyacentes.",
    "Xerxis",
    "{kw-channelmana} {kw-scaling:1/-1/0}: invoca un {kw-summon:19}.",
    "Amguan",
    "{kw-scheme}: todos los saurónidos aliados ganan 1/2 de {kw-charge}.",
    "Conducto de Almas",
    "{kw-channelsoul} 1: recupera 1/2 de vida. {kw-followup}: gana 1 alma. Almas máx +1.",
    "Espíritu del Bosque",
    "Cuando otro aliado bestia recibe daño, gana 1/2 de {kw-charge}.",
    "Vándalo",
    "{kw-channelblood} 2: ataca. Cuando este personaje elimina un enemigo, recupera 1/2 de vida.",
    "Chamán",
    "{kw-channelblood} 2: {kw-revive} un aliado bestia.",
    "Guardia Aviakorano",
    "{kw-counter}: Invoca una {kw-summon:6/7}.",
    "Inmortal",
    "No pierde armadura al final de la ronda.",
    "Mago de Combate",
    "Cuando este personaje gana {kw-charge}, también recupera 1/2 de vida.",
    "Clérigo Bélico",
    "{kw-followup}: cura 1 de vida a todos los personajes en esta columna.",
    "Invocador del Vacío",
    "{kw-endofround}: invoca un {kw-summon:23/24} enemigo.",
    "Animante",
    "{kw-endofround}: si no hay almas, gana 1/2 alma y 2/4 de {kw-charge}. Almas máx. +2.",
    "Elementalista",
    "Cuando se invoca un elemental aliado, gana 1 de ataque.",
    "{kw-channelmana} {kw-scaling:1/-1/0}: invoca un {kw-summon:25}.",
    "Capitán Real",
    "{kw-endofround}: todos los personajes en esta columna ganan 1 de armadura.",
    "Sabio de la Palabra",
    "{kw-healthisrecovered}: otorga 1/2 de {kw-charge} a un aliado al azar.",
    "Cuando contratas este personaje, ganas 2 de oro por cada aliado saurónido. {kw-death}: ganas 1/2 de oro.",
    "Portaestandarte Caído",
    "{kw-channelsoul} 1: todos los arqueros aliados atacan. Almas máx. +1.",
    "Bégimo Óseo",
    "{kw-endofround}: por cada alma, gana al azar 1 de {kw-charge} o recupera 1 de vida. Almas máx. +2",
    "Ares, el Caballero Perdido",
    "Cuando este personaje gana armadura, también gana 3 de {kw-charge}.",
    "Edric, Maestro Esgrimista",
    "Ataca dos veces.",
    "Cyril, el Maestro Animista",
    "Cuando se invoca un aliado, recupera 1 de vida.",
    "{kw-death}: se transforma en {kw-summon:26}.",
    "Ixotle, el Guardia de las Crías",
    "{kw-startofbattle} y {kw-death}: llena tu tablero con {kw-summon:27}s de saurónido.",
    "Taur, el Exiliado",
    "Gana 1 de ataque por cada aliado bestia. Cuando este personaje elimina un enemigo, recupera 3 de vida.",
    "Zed, el Embaucador Eterno",
    "Cuando este personaje gana {kw-charge}, invoca un {kw-summon:28} inamovible.",
    "Nix, de la Luna Antigua",
    "{kw-otherunitdies}: un enemigo aleatorio recibe {kw-weaken}.",
    "Lyra, Luz del Albor",
    "Objetivo: un enemigo aleatorio en cualquier fila.",
    "{kw-healthisrecovered}: ataca.",
    "El Devorador",
    "Cuando un personaje muere, invoca un {kw-summon:9}.",
    "Ayma, la Clamarayos",
    "{kw-counter}: los aliados ganan 1 de {kw-charge}.",
    "Alta Sacerdotisa",
    "{kw-followup}: todos los aliados recuperan 1 de vida.",
    "Nangrui, el Alquimista",
    "Cuando un aliado gana armadura, gana 1 de {kw-charge}.",
    "Ven, el Anciano",
    "Cuando un personaje envenenado muere, gana 1 de ataque y recupera 2 de vida.",
    "Aeron, Espíritu del Bosque",
    "Cuando un aliado muere, recupera 1 de vida. {kw-followup}: todos los aliados invocados atacan.",
    "Ursa, el Oso Divino",
    "Ataca cuando un aliado hace un sacrificio.",
    "Wisp del Vacío Menor",
    "Se ataca a sí mismo. {kw-death}: inflige 1 de daño a todos los aliados.",
    "Montón de Huesos",
    "{kw-endofround}: se transforma en un {kw-summon:3}.",
    "Jack",
    "Esqueleto",
    "Llama Sempiterna",
    "{kw-endofround}: un aliado gana 1 de {kw-charge}.",
    "Wisp Sagrado",
    "{kw-endofround}: cura 1 de vida a un personaje aliado.",
    "Paloma",
    "Cuervo",
    "Lobo",
    "Limo Venenoso",
    "Wisp de Sangre",
    "Wisp de Sangre Mayor",
    "Wisp Metálico Menor",
    "{kw-endofround}: un aliado en esta fila gana 1 de armadura.",
    "Wisp Metálico",
    "{kw-endofround}: un aliado en esta fila gana 2 de armadura.",
    "Wisp Metálico Mayor",
    "{kw-endofround}: un aliado en esta fila gana 3 de armadura.",
    "Espectro de Sangre",
    "{kw-death}: inflige 4 de daño al héroe aliado.",
    "Martillo Espectral",
    "{kw-followup}: recibe 1 de daño.",
    "Martillo Espectral Superior",
    "Martillo Espectral Dorado",
    "Escama Venenosa",
    "Bomba",
    "{kw-death}: inflige 2 de daño a TODOS los personajes en esta fila.",
    "Bomba Grande",
    "{kw-death}: inflige 4 de daño a TODOS los personajes en esta fila.",
    "Bomba Dorada",
    "{kw-death}: inflige 6 de daño a TODOS los personajes en esta fila.",
    "Wisp del Vacío",
    "Se ataca a sí mismo. {kw-death}: inflige 2 de daño a todos los aliados.",
    "Wisp del Vacío Mayor",
    "Se ataca a sí mismo. {kw-death}: inflige 3 de daño a todos los aliados.",
    "Wisp Eléctrico",
    "{kw-death}: todos los aliados ganan 1 de {kw-charge}.",
    "Cyril, Truenatierra",
    "Cría",
    "Espejismo",
    "No se puede mover.",
    "Limo Cósmico",
    "No cuenta para tu límite de grupo.",
    "{kw-endofround}: todos los elementales aliados ganan 1 de {kw-charge}.",
    "Asmodel, el Dorado",
    "Se vende por 15 de oro en campamentos.",
    "{kw-endofround}: gana {kw-shield}.",
    "Estatua Excepcional",
    "Estatua Dorada",
    "Se vende por 10 de oro en campamentos.",
    "Seguidor Leal",
    "Matorral",
    "Wisp Dorado",
    "Desaparece al final de la segunda ronda.",
    "{kw-endofround}: se mueve.",
    "Aventurero Perdido",
    "El Heraldo",
    "{kw-followup}: invoca un {kw-summon:1}.",
    "El Avizor",
    "Objetivo: un personaje aleatorio en cualquier fila.",
    "Rata Calamitosa",
    "Limo",
    "Barril",
    "Minn Tarascón",
    "{kw-endofround}: cambia de fila.",
    "Arquero Goblin",
    "Diente de Rata",
    "{kw-endofround}: invoca una bestia aleatoria.",
    "Murciélago",
    "Cobra",
    "Urna Metálica",
    "Aziel",
    "Gana 1 de ataque por cada {kw-summon:3} aliado.",
    "Faxel Tarascón",
    "{kw-counter}: inflige 1 de daño al enemigo más cercano y cambia de fila.",
    "Barril Explosivo",
    "Limo Amebiano",
    "{kw-death}: invoca dos {kw-summon:42}s.",
    "Herrero Tarascón",
    "{kw-endofround}: un aliado al azar gana 4 de armadura.",
    "Guardia Esquelético",
    "Sarcodón",
    "{kw-followup}: un aliado bestia aleatorio gana 1 de ataque.",
    "Flit Tarascón",
    "{kw-counter}: gana 1 de {kw-charge}.",
    "Fial Tarascón",
    "Cuando un personaje muere, gana 1 de ataque.",
    "El Tarascón Perdido",
    "{kw-endofround}: invoca un {kw-summon:48}.",
    "Madre del Enjambre",
    "Escarabajo Enterrador",
    "{kw-endofround}: la {kw-summon:64} gana 2 de armadura.",
    "Coloso Reanimado",
    "Doblemante",
    "Rey Tarascón",
    "{kw-endofround}: invoca un {kw-summon:46}.",
    "El Orbe de Comando",
    "Los goblins ganan 1 de ataque.",
    "Invisible.",
    "Limo Colosal",
    "{kw-endofround}: invoca dos {kw-summon:42}s y cambia de fila.",
    "Limo Solidificado",
    "Engendro de Valac",
    "{kw-endofround}: invoca un {kw-summon:73}.",
    "Orbe Ambulante",
    "Objetivo: uno de los enemigos más cercanos en cualquier fila.",
    "Simulae Acéfalo",
    "{kw-followup}: se mueve.",
    "Amasijo de Orbes",
    "{kw-death}: invoca tres {kw-summon:73}s.",
    "Colmillo de Plata",
    "Simulae Putrefacto",
    "{kw-death}: invoca un {kw-summon:74}.",
    "Urna Antigua",
    "Reina Orbe",
    "Gana 1 de ataque por cada aliado.",
    "Simulae Veninic",
    "Ataque paralizante.",
    "Simulae Perfecto",
    "Cuando este personaje elimina un enemigo, recupera 2 de vida.",
    "Licántropo",
    "Espíritu Cavernario",
    "Matorral Maldito",
    "{kw-death}: inflige 2 de daño al enemigo más cercano en esta fila.",
    "Matorral Animado",
    "{kw-endofround}: invoca dos matorrales malditos.",
    "Araña",
    "Baba Yaga",
    "{kw-endofround}: invoca un limo aleatorio y se mueve.",
    "Pícaro",
    "Cuando este personaje elimina un enemigo, roba 1 de oro.",
    "Mimético",
    "{kw-death}: ganas 1 de oro.",
    "Progenitor Orbe",
    "{kw-endofround}: invoca dos {kw-summon:73}s.",
    "Simulae Clypaen",
    "{kw-endofround}: le otorga {kw-shield} a otro aliado.",
    "Simulae Firic",
    "{kw-counter}: inflige 1 de daño al enemigo más cercano.",
    "La Hechicera",
    "Cuando un aliado muere, otro aliado gana 2 de ataque.",
    "Firis",
    "Venina",
    "Clypaes",
    "Simulae Prime",
    "{kw-followup}: inflige 5 de daño a todos los aliados y gana 1 de ataque.",
    "El Espejo",
    "{kw-endofround}: invoca un {kw-summon:77}.",
    "El Antiguo",
    "Cuando un aliado bestia muere, gana 1 de ataque.",
    "Licántropo Alfa",
    "{kw-death}: Invoca dos {kw-summon:83}s.",
    "El Invidente",
    "Objetivo: el enemigo con más vida.",
    "Escórpido",
    "Escórpido Esquelético",
    "Ataca tres veces.",
    "Servidor del Fuego",
    "{kw-followup}: cambia de fila y gana 1 de ataque.",
    "Príncipe Carmesí",
    "Ataques malditos.",
    "Wisp de Fuego",
    "{kw-death}: todos los aliados ganan 2 de {kw-charge}.",
    "Caminante del Abismo",
    "{kw-endofround}: invoca un {kw-summon:109}.",
    "Resplandor Amenazante",
    "{kw-endofround}: invoca dos {kw-summon:112} y luego se mueve.",
    "Resplandor inestable",
    "{kw-endofround}: inflige 5 de daño a TODOS los personajes en esta fila.",
    "Trol Anciano",
    "Trol",
    "Pesadilla",
    "{kw-endofround}: paraliza un enemigo al azar.",
    "Terror Cristalino",
    "{kw-death}: invoca un {kw-summon:117}.",
    "Terror",
    "Servidor de la Sombra",
    "Gana 1 de ataque por cada enemigo.",
    "Príncipe Sombrío",
    "Apabullante.",
    "Wisp Infernal",
    "{kw-death}: el {kw-summon:121} gana 1 de ataque.",
    "Guardián del Abismo",
    "{kw-endofround}: invoca un {kw-summon:120}.",
    "Urna Espiritual",
    "{kw-death}: destruye al {kw-summon:123}.",
    "Espíritu Carmesí",
    "{kw-endofround}: gana 15 de armadura y se mueve.",
    "Gigante Cárnico",
    "Los ataquen aplican 2 de {kw-affliction}.",
    "Gusano de la Carne",
    "Servidor de la Avaricia",
    "Príncipe Dorado",
    "{kw-followup}: roba 1 de oro.",
    "La Mano de Abaddon",
    "Cuando un monstruo aliado muere, gana 1 de ataque.",
    "Sacerdote de Abaddon",
    "{kw-counter}: {kw-summon:128} gana 2 de armadura.",
    "Sacerdotisa de Abaddon",
    "{kw-counter}: {kw-summon:128} gana 2 de {kw-charge}.",
    "Llama Primordial",
    "{kw-endofround}: inflige 2 de daño a todos los personajes en esta fila y luego se mueve.",
    "Roca",
    "Llama Sombría Menor",
    "{kw-death}: invoca un {kw-summon:134}.",
    "Llama Sombría",
    "{kw-death}: invoca un {kw-summon:135}.",
    "Llama Sombría Mayor",
    "El Hurtamentes",
    "Los ataques aplican un estado aleatorio. Ataca al azar.",
    "Campeón Hueco",
    "{kw-endofround}: gana 1 de ataque y se mueve.",
    "Abaddon",
    "Cada turno se transforma.",
    "Pereza",
    "Lujuria",
    "Envidia",
    "{kw-endofround}: invoca una {kw-summon:142}.",
    "Esfera Envenenada",
    "{kw-death}: el enemigo con menos vida recibe {kw-poison}.",
    "Ira",
    "Soberbia",
    "El enemigo con más vida pasa a tener 1 de vida.",
    "Avaricia",
    "{kw-endofround}: invoca tres {kw-summon:147}s.",
    "Corrupción",
    "{kw-endofround}: invoca dos esferas malditas.",
    "Esfera Dorada",
    "Gula",
    "{kw-endofround}: invoca dos devoradores aleatorios.",
    "Esfera Maldita",
    "{kw-death}: maldice un enemigo al azar.",
    "Devorador de Fuerza",
    "Los personajes no ganan armadura.",
    "Devorador de Esperanza",
    "Los personajes no recuperan vida.",
    "El Guardián",
    "Illifar",
    "Valac",
    "Orobas",
    "Morax",
    "{kw-endofround}: {kw-summon:153} gana 5 de armadura.",
    "Aamon",
    "{kw-endofround}: {kw-summon:153} gana 3 de {kw-charge}.",
    "Haagenti",
    "Los ataques ignoran la armadura.",
    "Bathin Mayor",
    "{kw-death}: paraliza a todos los personajes enemigos.",
    "{kw-endofround}: todos los aliados ganan 1 de {kw-charge}.",
    "Sombra Afligida",
    "Nazzatoth",
    "{kw-endofround}: invoca dos sombras.",
    "Sombra de Fuego Sombrío",
    "{kw-endofround}: invoca dos fuegos sombríos en esta fila.",
    "Sombra Eléctrica",
    "Sombra Inestable",
    "{kw-followup}: inflige 2 de daño a todos los personajes en esta fila.",
    "Sombra Cautivadora",
    "Sombra Aulladora",
    "Sombra Maldita",
    "Fuego Sombrío",
    "El Guardián del Portal",
    "Vacío",
    "{kw-death}: aplica un estado aleatorio a un enemigo al azar.",
    "{kw-endofround}: un aliado al azar gana 4 de {kw-charge}.",
    "Ojo de Nazzatoth",
    "Ojo de Illifar",
    "Inflige el doble de daño a enemigos con aflicción.",
    "Ojo de Abaddon",
    "Reflejo del Guardián",
    "{kw-endofround} y {kw-death}: inflige 5 de daño al enemigo más cercano de esta fila y aplica 2 de {kw-affliction}.",
    "{kw-endofround}: invoca un reflejo con una habilidad aleatoria.",
    "{kw-endofround} y {kw-death}: inflige 1 de daño a todos los enemigos.",
    "{kw-endofround} y {kw-death}: inflige 10 de daño al enemigo más cercano en esta fila.",
    "{kw-endofround} y {kw-death}: inflige 4x2 de daño al enemigo más cercano en esta fila.",
    "{kw-endofround} y {kw-death}: inflige 3 de daño al enemigo con más vida y lo paraliza.",
    "Espectro de la Mazmorra",
    "Lombriz Áurea",
    "{kw-death}: ganas 13 de oro.",
    "Rey de la torre",
    "{kw-endofround}: ???",
    "Guardia de la torre",
    "Archimaje",
    "Cazador real",
    "{kw-followup}: inflige 1 de daño a un enemigo aleatorio.",
    "Herrero",
    "Bomba",
    "{kw-endofround}: Invoca un {kw-summon:20}.",
    "Capitán de la torre",
    "{kw-followup}: un enemigo aleatorio recibe {kw-weaken}.",
    "Brujo real",
    "Espadachín real",
    "Heraldo del martillo",
    "{kw-endofround}: Invoca un {kw-summon:17}.",
    "Maestro de pociones",
    "Asesino",
    "Astrónomo",
    "{kw-endofround}: otorga 2 de {kw-charge} a un aliado al azar.",
    "Oráculo",
    "Torre Caballero",
    "{kw-followup}: gana {kw-shield}.",
    "Guardián de la cripta",
    "{kw-endofround}: invoca una {kw-summon:1} dos veces.",
    "Asesino",
    "Botecario",
    "{kw-otherunitdies}: inflige 2 de daño al enemigo más cercano.",
    "Bufón de la corte",
    "Lotante",
    "Lobo del Pantano",
    "{kw-endofround}: recupera 1 de vida.",
    "Cobra gigante",
    "Dúas de anochecer",
    "Torturador",
    "Golem",
    "Lancero",
    "Nobleza de la torre",
    "{kw-endofround}: recupera 2 de vida.",
    "Lacayo",
    "Limo interminable",
    "Mago de sangre",
    "{kw-death}: invoca un {kw-summon:11}.",
    "Amanecer beatle",
    "{kw-startofbattle}: gana {kw-shield}.",
    "Magma Golem",
    "{kw-followup}: gana 1 de ataque.",
    "Tumba inquieta",
    "{kw-death}: invoca un {kw-summon:244}.",
    "Golem nulo",
    "{kw-death}: inflige 1 de daño a todos los enemigos.",
    "Cazador",
    "Bailarín de espada",
    "Gana 1 de ataque si tiene toda la vida.",
    "Clérigo de la corte",
    "{kw-endofround}: Restaura 1 de salud al héroe aliado.",
    "Espíritu encarcelado",
    "Esbirro",
    "Armadura del anochecer",
    "{kw-counter}: gana 1 de armadura.",
    "Golem infernal",
    "Gigante de la torre",
    "Salvia de la corte",
    "Anochecer elemental",
    "{kw-endofround}: Da +1 {kw-charge} al héroe aliado.",
    "Duelista",
    "Armadura del Terror",
    "{kw-counter}: gana 4 de armadura.",
    "Dragón del Crepúsculo",
    "Demonio Nocturno",
    "Golem Perfecto",
    "Golem Arcano",
    "{kw-death}: invoca un {kw-summon:174}.",
    "Dragón del Alba",
    "Gigante anciano",
    "Comehombres",
    "{kw-death}: paraliza un enemigo al azar.",
    "Espíritu Vengador",
    "Urna Maldita",
    "{kw-death}: el enemigo más cercano en esta fila recibe {kw-poison}.",
    "Trampa de estatua",
    "{kw-death}: invoca un {kw-summon:20}.",
    "Carcaj de Lyra",
    "Los arqueros aliados ganan 1 de ataque.",
    "Escritura Taurina",
    "Las bestias y saurónidos aliados ganan 1 de vida.",
    "Diario de Edric",
    "Los luchadores aliados ganan 1 de ataque y pierden 1 de vida.",
    "Martillo de la Tierra Antigua",
    "Los enanos y gnomos aliados ganan 2 de vida.",
    "Capa del Juez",
    "Los aliados ganan +3 Velocidad.",
    "El Martillo del Herrero",
    "Cuando un aliado gana armadura, gana 1 de armadura adicional.",
    "Libro de la Ley",
    "Los humanos y enanos aliados ganan 1 de vida.",
    "Martillo de Thorich",
    "Los aliados conservan hasta 1 de armadura al final de cada ronda.",
    "Piedra de Erilari",
    "Los aliados invocados ganan 1 de ataque.",
    "Bastón de Cyril",
    "Los aliados invocados no se agotan.",
    "Recolector de Esencia",
    "Cuando muere un personaje aliado, invoca dos wisps de sangre.",
    "Antorcha Sempiterna",
    "{kw-startofbattle}: invoca una {kw-summon:4}.",
    "La Cuchilla del Juez",
    "{kw-startofbattle}: tu héroe gana 3 de {kw-charge} y {kw-shield}.",
    "Grillete Espiritual",
    "Invoca un {kw-summon:244} la primera vez que muere un aliado.",
    "Bendición de Clypaen",
    "La pimera vez que un aliado recibe daño, gana {kw-shield}.",
    "Destilador de Esencia",
    "Tras la primera ronda, invoca un {kw-summon:23} menor enemigo.",
    "El Secreto del Mercader",
    "Los objetos cuestan 1 menos de oro.",
    "Veneno Concentrado",
    "Los enemigos reciben 2 de daño adicional por veneno.",
    "Maleficio de Venina",
    "Monedas Falsificadas",
    "Los personajes en campamentos cuestan 2 de oro menos.",
    "Insignia Real",
    "La primera actualización en cada campamento y tienda es gratis. {kw-startofbattle}: tu héroe ataca.",
    "Sangre de Trol",
    "Cuando tu héroe elimina un enemigo, recupera 2 de vida.",
    "Martillo Titánico",
    "{kw-startofbattle}: todos los aliados ganan 2 de armadura.",
    "Bastón de los Amguan",
    "Cuando un aliado no ataca, gana 1 de {kw-charge}.",
    "Destilador Sagrado",
    "Tras la primera ronda, invoca un {kw-summon:5}.",
    "Libro del Poder",
    "{kw-endofround}: un aliado humano al azar gana 1 de {kw-charge}.",
    "Esencia Etérea",
    "Cuando un aliado pierde su escudo, gana 1 de ataque.",
    "Violín de Jack",
    "Cuando visitas un campamento u hoguera, ganas 3 de oro.",
    "Libro de las Estrellas",
    "{kw-endofround}: el mago aliado con menos vida gana 1 de {kw-charge}.",
    "Carcaj Vertiginoso",
    "{kw-startofbattle}: los arqueros aliados atacan dos veces.",
    "Encantamiento de Fey",
    "Cuando se invoca un aliado, le otorga 2 de {kw-charge}.",
    "Bastón de la Llama",
    "{kw-startofbattle}: inflige 8 de daño a un enemigo al azar.",
    "Bastón celestial",
    "{kw-startofbattle}: Da a todos los aliados +1 {kw-charge}.",
    "Bastón del Vacío",
    "{kw-endofround}: inflige 1 de daño a un enemigo al azar.",
    "Esencia Elemental",
    "Los elementales aliados ganan 2 de vida.",
    "Maza Fundida",
    "{kw-endofround}: un luchador aliado al azar gana 1 de armadura.",
    "Libro de Bathin",
    "{kw-startofbattle}: ganas 1 de oro. Tu héroe tiene 2 de vida menos.",
    "La Cuchilla Perdida",
    "Tu héroe gana 1 de ataque y 2 de velocidad.",
    "Botas de Edric",
    "Tu héroe ataca dos veces.",
    "Cuchilla de la Esencia",
    "Tu héroe posee \\\"{kw-otherunitdies}: gana 1 de {kw-charge}\\\".",
    "Libro de la Premura",
    "Los magos aliados no se agotan.",
    "Brebaje Extraño",
    "{kw-startofbattle}: otorga 1 de ataque a un aliado saurónido, gnomo y elemental.",
    "Símbolo de la Alianza",
    "{kw-startofbattle}: otorga {kw-shield} a un aliado humano, enano y elfo.",
    "Destilador de Veneno",
    "Cuando un personaje envenenado muere, un personaje aliado herido recupera 1 de vida.",
    "Maleficio de Sangre",
    "Tras la primera ronda, invoca un especto de sangre.",
    "Campana de Invocación",
    "{kw-startofbattle}: invoca dos martillos espectrales.",
    "Receptáculo de Almas",
    "Almas máx. +6.",
    "Recuerdo de Jack",
    "Los aliados bestia ganan 1 de vida y 2 de velocidad.",
    "Manastone",
    "Los personajes Manacast tienen +1 de Maná.",
    "Hoja sagrada",
    "Tu héroe posee \\\"{kw-healthisrecovered}: gana 1 de {kw-charge}\\\".",
    "Manablade",
    "Cuando un personaje manaca, tu héroe gana +1 Ataque.",
    "La Corona del Alba",
    "La capacidad de tu grupo aumenta en 1.",
    "Capa de Seguidor",
    "Poción de Lealtad",
    "Transforma a un {kw-summon:33} en un {kw-summon:34}. El personaje pierde todo su equipamiento. Consumible",
    "Cuchilla de Aamon",
    "{kw-counter}: gana 1 de ataque.",
    "Espada infernal",
    "Espada de Campeón",
    "Cuchilla Fénix",
    "Invitación de la Muerte",
    "Quien se lo equipe, muere.",
    "Anillo de la Plaga",
    "{kw-startofbattle}: envenena, pero ganas 3 de oro.",
    "Anillo de Edad",
    "{kw-startofbattle}: ganas 3 de oro.",
    "Anillo de Mortalidad",
    "{kw-startofbattle}: recibe 1 de daño y ganas 3 de oro.",
    "Anillo de Debilidad",
    "Poción Curativa",
    "Recupera 2 de vida. Consumible.",
    "Poción Temporal",
    "Transforma a tu héroe. Pierde todo su equipamiento.",
    "Poción Curativa Menor",
    "Recupera 1 de vida. Consumible.",
    "Poción Curativa Mayor",
    "Recupera 8 de vida. Consumible.",
    "Capa Ritual",
    "Capa de Trotamundos",
    "Arco Corto",
    "Arco de la Sombra",
    "Capa de Chatarrero",
    "Cuando este personaje elimina un enemigo, invoca un {kw-summon:7}.",
    "Ballesta de Iliphar",
    "Arco infernal",
    "Ballesta de Andromalius",
    "Poción Misteriosa Menor",
    "Se transforma en un objeto aleatorio. Consumible.",
    "Poción de Transformación",
    "Transforma a un arquero en un personaje Nivel 3 aleatorio. El personaje pierde todo su equipamiento. Consumible.",
    "Vial de Esencia",
    "{kw-death}: invoca un {kw-summon:10}.",
    "Dije con Espejo",
    "El personaje equipado es inmune a la parálisis.",
    "Lente Anímico",
    "Cuando muere un aliado, inflige 1 de daño al enemigo más cercano.",
    "Collar de Clypaes",
    "Bastón de Adepto",
    "Piedra Solar",
    "{kw-endofround}: gana 1 de {kw-charge}.",
    "Amuleto Maldito",
    "Signo Calcinante",
    "Cetro Bendito",
    "{kw-followup}: cura 1 de vida a un personaje aliado herido .",
    "Varita infernal",
    "Garra de Andromalius",
    "Poción de Midas",
    "Transforma a un mago en una {kw-summon:32} que se puede vender por 10 de oro en los campamentos. El personaje pierde todo su equipamiento. Consumible.",
    "Poción de Versatilidad Mayor",
    "Transforma a un mago en multiclase, lo que permite que use equipamiento de cualquier clase. Consumible.",
    "Poción Misteriosa Mayor",
    "Broquel de Madera",
    "Escudo Venenoso",
    "{kw-startofbattle}: se envenena.",
    "Escudo de Guerrillero",
    "Broquel Reforzado",
    "Yelmo Inmortal",
    "{kw-otherunitdies}: gana 1 de armadura.",
    "Pared de Titán",
    "Escudo Cometa",
    "Yelmo Vampírico",
    "{kw-otherunitdies}: recupera 1 de vida.",
    "Escama de Dragón",
    "Escudo infernal",
    "{kw-startofbattle}: gana 2 de armadura.",
    "Escama de Andromalius",
    "Poción de Versatilidad",
    "Transforma a un luchador en multiclase, lo que permite que use equipamiento de cualquier clase. Consumible.",
    "Poción de Réplica",
    "Transforma a un luchador en una copia básica de un integrante aleatorio del grupo. El personaje pierde todo su equipamiento. Consumible.",
    "Huevo de Saurónido",
    "Después de la primera ronda, invoca una {kw-summon:27} de saurónido.",
    "Colmillo Relámpago",
    "Colmillo Venenoso",
    "Los ataques aplican veneno a los enemigos.",
    "Huevo Tóxico",
    "Después de la primera ronda, invoca un saurónido {kw-summon:19}.",
    "Moneda de la Suerte",
    "No se sabe para qué sirve.",
    "Gorro de la Muerte",
    "Cuando muere un personaje envenenado, recupera 1 de vida.",
    "Gorro Venenoso",
    "{kw-followup}: inflige 1 de daño a todos los enemigos envenenados.",
    "Gorro de la Inmortalidad",
    "{kw-followup}: recupera 1 de vida.",
    "Alma Agrietada",
    "{kw-startofbattle}: gana 1 alma. Almas máx. +1.",
    "Amuleto de Calavera",
    "Después de un ritual, gana 1 de armadura.",
    "Varita Sanguina",
    "Después de la primera ronda, invoca un {kw-summon:10}.",
    "Varita de Escamas Verdes",
    "{kw-endofround}: otorga 1 de armadura a un aliado invocado aleatorio.",
    "Varita Necrótica",
    "Piedra Estelar",
    "Cinturón de Midas",
    "Hacha Arrojadiza",
    "{kw-counter}: inflige 1 de daño a un enemigo aleatorio.",
    "Hacha de Berserker",
    "Gana 1 de ataque si no tiene toda la vida.",
    "Hacha Bendita",
    "Cuando este personaje recupera vida, también gana 1 de {kw-charge}.",
    "Cinturón de Inmortalidad",
    "{kw-counter}: recupera 1 de vida.",
    "Gema ancestral",
    "Cuchillo de Taur",
    "Armadura de Noble",
    "{kw-death}: ganas 1 de oro.",
    "Cota de Malla",
    "Armadura de Mártir",
    "{kw-death}: otorga 1 de ataque a todos los aliados.",
    "Armadura de Campeón",
    "Anillo de Sangre Vital",
    "Anillo de Paloma",
    "Una Llave Antigua",
    "Anillo Bezoar",
    "El personaje equipado es inmune al veneno.",
    "Llave Dorada",
    "Llave del Contrabandista",
    "Anillo de Titán",
    "{kw-startofbattle}: gana 4 de armadura.",
    "Guantes de Curtidor",
    "Anillo del Halcón",
    "Anillo Colérico del Vacío",
    "Cuando este personaje elimina un enemigo, inflige 1 de daño a un enemigo aleatorio.",
    "Guantes Reforzados",
    "Anillo Necrótico",
    "Robaalmas",
    "Cuando este personaje mata un enemigo, recupera 1 de vida.",
    "Anillo de Thoric",
    "Bendición de la Muerte",
    "En vez de que muera este personaje, se destruye este objeto.",
    "Cinturón de Pociones",
    "Cráneo del Vacío",
    "Guanteletes",
    "Anillo de Diamante",
    "Llave del Portal",
    "Gema de Zafiro",
    "Cenizas",
    "Anillo de Obsidiana",
    "Un vetusto anillo de transformación.",
    "Gema de Obsidiana",
    "Anillo de Esmeralda",
    "Anillo de Ametista",
    "Anillo de Rubí",
    "Anillo de Topacio",
    "Regalo de la Muerte",
    "+25% de puntuación",
    "Sombra de la Muerte",
    "{kw-counter}: gana {kw-shield}.",
    "Poción de Experiencia",
    "Gana 1 de EXP. Consumible.",
    "Gana 1 de EXP. Los personajes que mueren en este combate no ganan EXP. Consumible.",
    "Poción de Maestría",
    "Gana 3 EXP. Consumible.",
    "Poción Cósmica",
    "Transforma a un personaje en un {kw-summon:29}. El personaje pierde todo su equipamiento. Consumible.",
    "Bolsa de Oro",
    "Poción de Experiencia Superior",
    "Gana 2 EXP. Los personajes que mueren en este combate no ganan EXP. Consumible.",
    "Metal",
    "Sol",
    "Martillo",
    "Corazón",
    "Escama",
    "Rama",
    "Cráneo",
    "Garra"
];
