var L = [
    "",
    "Humano",
    "Enano",
    "Gnomo",
    "Elfo",
    "Reptiliano",
    "Elemental",
    "Bestia",
    "Duende",
    "No muerto",
    "Monstruo",
    "Planta",
    "Constructo",
    "Dios ancestral",
    "Demonio",
    "???",
    "Héroe",
    "Luchador",
    "Arquero",
    "Mago",
    "Discípulo",
    "Multiclase",
    "-",
    "Solo frente",
    "Atrás solo",
    "Ataque",
    "Salud",
    "Velocidad",
    "Muerte",
    "MUERTE: Condición activada al morir.",
    "Fin de ronda",
    "FIN DE RONDA: Condición activada después de que todos los personajes ataquen. Ignora el agotamiento.",
    "Continuación",
    "CONTINUACIÓN: Ejecuta otra acción después del ataque normal del personaje.",
    "Condena",
    "CONDENA: Condición activada si muere un personaje enemigo.",
    "Esperanza",
    "ESPERANZA: Condición activada cuando la Salud de un personaje aliado aumenta.",
    "Esquema",
    "ESQUEMA: Condición activada si el personaje no ataca.",
    "Inicio de batalla",
    "INICIO DE BATALLA: Condición activada cuando comienza la batalla.",
    "Poder de almas",
    "Poder de almas X: Usa X almas para activar una habilidad entre rondas. Puede usarse una vez por ronda. Haz clic derecho para usar.",
    "Veneno",
    "VENENO: Los personajes envenenados reciben 1 de daño después de su ataque normal. Dura hasta el final de esta batalla. No se acumula.",
    "Maldición",
    "MALDICIÓN: La próxima vez que este personaje sea atacado, recibirá el doble de daño.",
    "Escudo",
    "ESCUDO: La próxima vez que este personaje reciba daño, lo anulará por completo.",
    "Contraataque",
    "CONTRAATAQUE: Condición activada cuando el personaje pierde Salud y sobrevive.",
    "Aflicción",
    "AFLICCIÓN: ALos personajes afligidos no pueden ganar Salud, Armadura o Poder. Al final del turno del personaje, se elimina una acumulación de Aflicción.",
    "Poder",
    "PODER: El próximo ataque inflige más daño.",
    "ARMADURA",
    "ARMADURA: La cantidad de daño que puede recibir un personaje antes de perder Salud. La Armadura se pierde al final de cada ronda.",
    "Asesinatos",
    "Conjuro de sangre",
    "Conjuro de sangre X: Sufres daño para activar una habilidad entre rondas. Puede usarse una vez por ronda. Haz clic derecho para usar.",
    "Revivir",
    "Revivir: Revive a un aliado con 1 de Salud.",
    "invoca",
    "El aventurero perdido",
    "Qué alma tan desafortunada",
    "Thoric del Martillo",
    "Noble de la vieja tierra",
    "{kw-endofround}: Gana +1 de Armadura.",
    "Maestro herrero",
    "{kw-endofround}: Otorga +1 de Armadura al aliado más adelantado en su fila.",
    "Eloa",
    "El último astrónomo",
    "{kw-followup}: Otorga +1 de {kw-charge} a un aliado en su fila. Inagotable.",
    "Investigador arcano",
    "{kw-endofround}: Otorga +2 de {kw-charge} a un Mago aliado en su misma fila.",
    "Dominique Boutroux",
    "El cocinero viajero",
    "{kw-followup}: Cura 1 de Salud a un aliado dañado en su misma fila. Inagotable.",
    "Vendedor Ambulante",
    "{kw-startofbattle}: Ganas 1 de oro. Inagotable.",
    "Anciana Gryx",
    "La nadadora solitaria",
    "Cuando un aliado muere, ataca. Inagotable.",
    "Matriarca de la Progenie",
    "Venenoso. Inagotable.",
    "Mariana",
    "Conocimientos itinerantes",
    "{kw-startofbattle}: Invoca a {kw-summon:159}. Inagotable.",
    "Buscador de Venganza",
    "Comienza con Recuerdo de Jack. Inagotable.",
    "Taz'gyn",
    "Sombra de la Luna Ancestral",
    "Comienza con un destilador de esencia. Inagotable.",
    "Invocador ascendido",
    "Si un personaje mata a un enemigo, invoca una {kw-summon:4}. Inagotable.",
    "Xandos III",
    "El príncipe joven",
    "Comienza con la corona del alba.",
    "Emperador Dorado",
    "Tiene +1 de Ataque por cada 5 de oro. Inagotable.",
    "Elsbeth",
    "Efigie del más allá",
    "{kw-channelsoul} 1: Inflige 2 de daño al enemigo más cercano. Máx. de almas +1. Inagotable.",
    "Artificiero",
    "Comienza con dos reliquias adicionales aleatorias. Inagotable.",
    "Animara",
    "Si un personaje lanza un conjuro de sangre, gana +1 de {kw-charge}. Inagotable.",
    "Taz'gyn, Campeón de la Orden",
    "{kw-otherunitdies}: Gana +1 de {kw-charge}. Inagotable.",
    "Xandos, el Grande",
    "Elsbeth, Bruja del Pantano",
    "{kw-startofbattle}: Envenena a dos enemigos aleatorios. Venenoso. Inagotable.",
    "Cofre de artefactos",
    "Escoge un artefacto.",
    "Espada de campeón",
    "Espada de Aamon",
    "{kw-counter}: Gana +1 de Ataque.",
    "Cenizas",
    "Espada del fénix",
    "Capa de discípulo",
    "Cinta de la paloma",
    "Anillo de titán",
    "{kw-startofbattle}: Gana +4 de Armadura.",
    "Anillo de Thoric",
    "Cinta del halcón",
    "Anillo necrótico",
    "Anillo de sangre vital",
    "Anillo antiveneno",
    "El personaje equipado no puede ser envenenado.",
    "Anillo de furia del Vacío",
    "Cuando este personaje mate a un enemigo, inflige 1 de daño a un enemigo aleatorio.",
    "Cinto de pociones",
    "{kw-endofround}: Recupera 1 de Salud.",
    "Ladrón de almas",
    "Cuando este personaje mate a un enemigo, se cura 1 de Salud.",
    "Calavera del Vacío",
    "Gracia de la Muerte",
    "Si el personaje que lo lleva muere, destruye este objeto en su lugar.",
    "Invitación de la Muerte",
    "Al equiparlo, mueres.",
    "Regalo de la Muerte",
    "+25 % de puntuación",
    "Sombra de la Muerte",
    "{kw-counter}: Gana {kw-shield}.",
    "Guantes de curtidor",
    "Guantes reforzados",
    "{kw-startofbattle}: Gana +2 de Armadura.",
    "Guanteletes",
    "Yelmo de inmortal",
    "{kw-otherunitdies}: Gana +1 de Armadura.",
    "Yelmo vampírico",
    "{kw-otherunitdies}: Recupera 1 de Salud.",
    "Escudo de madera",
    "Escudo reforzado",
    "Escudo del hostigador",
    "Escudo de cometa",
    "Muro del titán",
    "Escama de dragón",
    "Escama de Andromalius",
    "Escudo de veneno",
    "{kw-startofbattle}: Envenenado.",
    "Piedra del sol",
    "{kw-endofround}: Gana +1 de {kw-charge}.",
    "Colgante espejado",
    "El personaje equipado no puede ser paralizado.",
    "Colgante de Clypaes",
    "{kw-startofbattle}: Gana {kw-shield}.",
    "Vial de esencia",
    "{kw-death}: Invoca un {kw-summon:170}.",
    "Amuleto condenado",
    "{kw-followup}: Recibe 1 de daño.",
    "Lente del alma",
    "Cuando un aliado muere, inflige 1 de daño al enemigo más cercano.",
    "Bastón del adepto",
    "Signo abrasador",
    "Cetro sagrado",
    "{kw-followup}: Cura 1 de Salud a un aliado dañado que no sea un héroe.",
    "Garra de Andromalius",
    "Arco corto",
    "El Arco de las Sombras",
    "Capa de travesía",
    "Capa de vagabundo",
    "Capa de carroñero",
    "Cuando este personaje mata a un enemigo, invoca un {kw-summon:161}.",
    "Arbalesta de Iliphar",
    "Arbalesta de Andromalius",
    "Coraza de mártir",
    "{kw-death}: Otorga +1 de Ataque a todos los aliados.",
    "Coraza de noble",
    "{kw-death}: Gana 2 de oro.",
    "Cota de malla",
    "Coraza de campeón",
    "Cinto de Midas",
    "{kw-startofbattle}: Gana 1 de oro.",
    "Cinturón del inmortal",
    "{kw-counter}: Recupera 1 de Salud.",
    "Hacha arrojadiza",
    "{kw-counter}: Inflige 1 de daño a un enemigo aleatorio.",
    "Hacha sagrada",
    "Cuando este personaje gana Salud, también gana +1 de {kw-charge}.",
    "Hacha de berserker",
    "Gana +1 de Ataque si está por debajo de su Salud máxima.",
    "Huevo de cría",
    "Tras la primera ronda, invoca a una {kw-summon:179} de reptiliano.",
    "Huevo Tóxico",
    "Tras la primera ronda, invoca a un Envenescamoso reptiliano.",
    "Colmillo del relámpago",
    "Colmillo venenoso",
    "Los ataques envenenan al enemigo golpeado.",
    "Varita sanguina",
    "Tras la primera ronda, invoca a un {kw-summon:170}.",
    "Varita necrótica",
    "{kw-endofround}: Inflige 1 de daño al enemigo con menor Salud.",
    "Varita de escamas verdes",
    "{kw-endofround}: Otorga +1 de Armadura a una invocación aliada aleatoria.",
    "Casco de veneno",
    "{kw-followup}: Inflige 1 de daño a todos los enemigos envenenados.",
    "Moneda de la suerte",
    "Casco del inmortal",
    "{kw-followup}: Recupera 1 de Salud.",
    "Casco de la muerte",
    "Cuando un personaje envenenado muere, recupera 1 de Salud.",
    "Piedra estelar",
    "Talismán de calavera",
    "Cuando un personaje use su Poder de almas, gana +1 de Armadura.",
    "Alma agrietada",
    "{kw-startofbattle}: Gana 1 alma.Máx. de almas +1.",
    "Cuchilla de Taur",
    "Gema ancestral",
    "Si un personaje lanza un conjuro de sangre, gana +1 de {kw-charge}.",
    "Una llave vieja",
    "La llave del contrabandista",
    "Llave dorada",
    "Llave del portal",
    "Anillo de obsidiana",
    "Un antiguo anillo de transformación.",
    "Anillo de esmeralda",
    "Anillo de topacio",
    "Anillo de diamante",
    "Anillo de rubí",
    "Anillo de amatista",
    "Gema de obsidiana",
    "Gema de zafiro",
    "Anillo de debilidad",
    "{kw-startofbattle}: Gana 3 de oro. (Anciana Gryx, Mariana)",
    "Anillo de mortalidad",
    "{kw-startofbattle}: Recibe 1 de daño y gana 3 de oro. (Xandos III, Taz'gyn, Elsbeth)",
    "Anillo de la edad",
    "{kw-startofbattle}: Ganas 3 de oro. (Eloa, Dominique Boutroux)",
    "Anillo de la plaga",
    "{kw-startofbattle}: Envenenado. Gana 3 de oro. (Thoric del Martillo)",
    "Poción de transformación",
    "Transforma a un Arquero en un personaje aleatorio de nivel 3. El personaje pierde todo su equipo. Consumible.",
    "Poción de replicación",
    "Transforma a un Guerrero en una copia básica de un miembro aleatorio del grupo. El personaje pierde todo su equipo. Consumible.",
    "Poción de Midas",
    "Transforma a un Mago en una Estatua de Oro, que puede venderse por 10 de oro en los campamentos. El personaje pierde todo su equipo. Consumible.",
    "Poción temporal",
    "Transforma a tu héroe. Al hacerlo, perderá todo su equipo.",
    "Poción de misterio mayor",
    "Se transforma en un objeto aleatorio. Consumible.",
    "Poción de misterio menor",
    "Poción de versatilidad",
    "Transforma al guerrero en un multiclase, permitiéndole usar equipo de cualquier otra clase. Se consume al usarlo.",
    "Poción de versatilidad mayor",
    "Transforma al mago en un multiclase, permitiéndole usar equipo de cualquier otra clase. Se consume al usarlo.",
    "Bolsa de oro",
    "Gana 3 de oro.",
    "Poción de experiencia",
    "Gana +1 de EXP. Consumible.",
    "Gana +1 de EXP. Los personajes que hayan muerto en esta batalla no ganarán EXP. Consumible.",
    "Poción de experiencia mayor",
    "Gana +2 de EXP. Los personajes que hayan muerto en esta batalla no ganarán EXP. Consumible.",
    "Poción de maestría",
    "Gana +3 de EXP. Consumible.",
    "Poción de curación menor",
    "Restaura 1 de Salud. Consumible.",
    "Poción de curación",
    "Restaura 2 de Salud. Consumible.",
    "Poción de curación mayor",
    "Restaura 8 de Salud. Consumible.",
    "Poción cósmica",
    "Transforma a un personaje en un {kw-summon:154}. El personaje pierde todo su equipo. Consumible.",
    "Poción de lealtad",
    "Transforma a un Discípulo en un {kw-summon:153}. El personaje pierde todo su equipo. Consumible.",
    "Carcaj de Lyra",
    "Los arqueros aliados ganan +1 de Ataque.",
    "Escritura tauriana",
    "Las Bestias y los Reptilianos aliados ganan +1 de Salud.",
    "Diario de Edric",
    "Los Luchadores aliados ganan +1 de Ataque y pierden -1 de Salud.",
    "Libro de las Estrellas",
    "{kw-endofround}: Otorga +1 de {kw-charge} al Mago aliado con la menor Salud.",
    "Martillo de la Tierra Ancestral",
    "Los aliados Enanos y Gnomos ganan +2 de Salud.",
    "La capa del Inquisidor",
    "Los Elfos y los Elementales aliados ganan +3 de Velocidad.",
    "El Martillo del Forjador",
    "Cada vez que un aliado gana Armadura, obtiene +1 de Armadura adicional.",
    "La espada del Inquisidor",
    "{kw-startofbattle}: Otorga +3 de {kw-charge} y {kw-shield} a tu héroe.",
    "Libro de leyes",
    "Los aliados Humanos y Enanos ganan +1 de Salud.",
    "Martillo de Thoric",
    "Los aliados podrán acumular hasta 1 de Armadura al final de cada ronda.",
    "Bendición de Clypaen",
    "La primea vez que un aliado reciba daño, le otorga un {kw-shield}.",
    "El secreto del mercader",
    "Los objetos cuesta 1 de oro menos.",
    "Piedra de Erilari",
    "Los aliados invocados ganan +1 de Ataque.",
    "Bastón de Cyril",
    "Los aliados invocados no pueden agotarse.",
    "Antorcha eterna",
    "{kw-startofbattle}: Invoca una {kw-summon:163}.",
    "Espíritu con Cadenas",
    "La primera vez que muera un aliado, invoca un {kw-summon:164}.",
    "Destilador de esencia",
    "Tras la primera ronda, invoca a un {kw-summon:172} enemigo.",
    "Recolector de esencia",
    "Cuando un aliado no invocado muera, invoca dos Wisps Sangrientos.",
    "Veneno puro",
    "Los enemigos reciben +1 de daño de los venenos.",
    "Maleficio de Venina",
    "{kw-startofbattle}: Envenena a dos enemigos aleatorios.",
    "Monedas falsificadas",
    "Los personajes de los campamentos cuestan 2 de oro menos.",
    "Insignia real",
    "Tu primer cambio de héroes en un campamento/tienda será gratuito. {kw-startofbattle}: Tu héroe atacará.",
    "Sangre de trol",
    "Cuando tu héroe mate a un enemigo, recuperará 2 de Salud.",
    "Libro de poder",
    "{kw-endofround}: Otorga +1 de {kw-charge} a un aliado Humano aleatorio.",
    "Bastón del Amguan",
    "Cuando un aliado no ataque, le otorga +1 de {kw-charge}.",
    "Esencia etérea",
    "Cuando un aliado pierde su escudo, les otorga +1 de Ataque.",
    "Martillo titánico",
    "{kw-startofbattle}: Otorga 2 de Armadura a todos los aliados.",
    "Destilador sagrado",
    "Tras la primera ronda, invoca a un {kw-summon:166}.",
    "Violín de Jack",
    "Al visitar un campamento o una fogata, ganas 3 de oro.",
    "Carcaj de disparo rápido",
    "{kw-startofbattle}: Los arqueros aliados atacan dos veces.",
    "Hechicería de los Fey",
    "Al invocar a un aliado, le otorga +2 de {kw-charge}.",
    "Bastón de la Llama",
    "{kw-startofbattle}: Inflige 5 de daño a un enemigo aleatorio.",
    "Bastón del Cielo",
    "{kw-startofbattle}: Inflige 4 de daño distribuido aleatoriamente entre todos los enemigos.",
    "Bastón del Vacío",
    "{kw-endofround}: Inflige 1 de daño a un enemigo aleatorio.",
    "Esencia elemental",
    "Los Elementales aliados ganan +2 de Salud.",
    "Mazo fundido",
    "{kw-endofround}: Otorga a un Luchador aliado aleatorio +1 de Armadura.",
    "Libro de Bathin",
    "{kw-startofbattle}: Gana 1 de oro. Tu héroe perderá -2 de Salud.",
    "La Hoja Perdida",
    "Tu héroe tiene +1 de Ataque y +2 de Velocidad.",
    "Botas de Edric",
    "Tu héroe tiene un ataque adicional.",
    "Espada de esencia",
    "Tu héroe gana \\\"{kw-otherunitdies}: Gana +1 de {kw-charge}.\\\"",
    "Libro de prisa",
    "Los Magos aliados no pueden agotarse.",
    "Brebaje extraño",
    "{kw-startofbattle}: Otorga +1 de Ataque a un Reptiliano, un Gnomo y un Elemental aliados.",
    "Símbolo de la Alianza",
    "{kw-startofbattle}: Le otorga {kw-shield} a un Humano, un Enano y un Elfo aliados.",
    "Destilador de Venin",
    "Cuando un personaje envenenado muere, cura 1 de Salud a un aliado dañado que no sea un héroe.",
    "Maleficio de sangre",
    "Después de la primera ronda, invoca a una {kw-summon:182}.",
    "Campana de invocación",
    "{kw-startofbattle}: Invoca dos Martillos Espectrales.",
    "Vasija de almas",
    "Máx. de almas +6.",
    "Recuerdo de Jack",
    "Las Bestias aliadas ganan +1 de Salud y +2 de Velocidad.",
    "La corona del alba",
    "El límite de tu grupo aumenta en 1.",
    "Aguatilis",
    "Cuando un aliado muere, gana +2/3/4 de {kw-charge}. Inagotable.",
    "Caballero con armadura",
    "Tiene una bonificación de Ataque igual a su Armadura.",
    "Forjador",
    "{kw-endofround}: Otorga +2/3/4 de Armadura a otro aliado en esta fila.",
    "Berserker",
    "{kw-counter}: Gana +1/2/3 de {kw-charge}.",
    "Maestro cervecero",
    "{kw-counter}: Restaura 1 de Salud a un aliado herido que no sea un héroe.",
    "Carnicero",
    "Cuando este personaje mata a un enemigo, cura 1 de Salud a un aliado daña/e a un enemigo, restaura 1 de Salud dos veces a un aliado heri/e a un enemigo, restaura 1 de Salud tres veces a un aliado herido que no sea un héroe.",
    "Canalizador",
    "{kw-followup}: Activa todos los efectos aliados de Condena.",
    "Clérigo de la Oscuridad",
    "Cuando este personaje mata a un enemigo, gana {kw-shield}.",
    "Clérigo del Martillo",
    "{kw-endofround}: Invoca un {kw-summon:183/184/185}.",
    "Clérigo del Camino",
    "{kw-followup}: Restaura 1/1/2 de Salud a un aliado herido que no sea un héroe.",
    "Clérigo de la Rosa",
    "{kw-healthisrecovered}: Inflige 1/1/2 de daño al enemigo más cercano en su misma fila.",
    "Sectario",
    "{kw-otherunitdies}: Recupera 1/2/3 de Salud.",
    "Arquero Mortífero",
    "Gana +1 de daño por cada No Muerto aliado.",
    "Protector Divino",
    "Cuando invocas a un aliado, le otorga un {kw-shield}.",
    "Druida",
    "Tras la primera ronda, invoca a una/un/a un {kw-summon:160/161/162} dos veces.",
    "Sangre de Ascuas",
    "{kw-channelblood} 2: Gana +1 de Ataque.",
    "Encantador",
    "{kw-endofround}: Otorga +1 de {kw-charge} a todos los Magos aliados.",
    "Adepto Caído",
    "{kw-channelsoul} X: Inflige X de daño/daño doble/daño cuádruple al enemigo más cercano en su misma fila. Máx. de almas +3.",
    "Súbdito de los Fey",
    "Venenoso. Los aliados invocados tienen +1/2/3 de Ataque.",
    "Erudito de la Llama",
    "Los ataques también infligen daño a los enemigos en la misma columna.",
    "Haruspex",
    "{kw-otherunitdies}: Inflige 1/2/4 de daño a un enemigo aleatorio.",
    "Cazador",
    "{kw-followup}: Inflige 1 de daño /dos veces/tres veces al enemigo con menor Salud.",
    "Hipogeo",
    "{kw-scheme}: Recupera 1 de Salud por cada Reptiliano aliado.",
    "Sangre de Hierro",
    "{kw-channelblood} 1: Ganas +1 de Armadura por cada aliado herido.",
    "Jabalinero",
    "Ataca después de ganar Armadura.",
    "Erudito del Relámpago",
    "Cuando este personaje gana {kw-charge}, inflige 1/2/3 de daño a un enemigo aleatorio.",
    "Mago del Sol",
    "Ganas el doble de {kw-charge}.",
    "Nigromante",
    "{kw-channelsoul} 2: Invoca un {kw-summon:5}. Máx. de almas +2.",
    "Arquero nocturno",
    "{kw-otherunitdies}: Gana +1/2/3 de {kw-charge}. Inagotable.",
    "Praexator",
    "Cuando este personaje mata a un enemigo, otorga +1 de {kw-charge} a todos los Reptilianos aliados. Inagotable.",
    "Praliator",
    "Si este personaje mata a un enemigo, ataca de nuevo.",
    "Pícaro",
    "Guardia Real",
    "Cuando este personaje gane Salud, tu héroe gana +1/e Salud, tu héroe gana +1/a Salud, tu héroe gana +2 de {kw-charge}.",
    "Herrero Rúnico",
    "Cuando otro Enano reciba daño, gana +1 de {kw-charge}. {kw-endofround}: Gana +1 de Armadura por cada Enano presente.",
    "Exanguinador",
    "{kw-endofround}: Invoca una {kw-summon:182} en su misma fila. Inagotable.",
    "Francotirador",
    "Cuando un enemigo se ve afectado por {kw-poison}, le inflige 1/a un enemigo se le aplica un {kw-poison}, le inflige 2/a un enemigo se le aplica un {kw-poison}, le inflige 3 de daño.",
    "Bebealmas",
    "{kw-endofround}: Si tienes 2 almas o más, restaura 1/2/3 de Salud. Máx. de almas +2.",
    "Escudero",
    "{kw-endofround}: Otorga +1/2/3 de {kw-charge} a otro aliado en esta fila.",
    "Invocador de Acero",
    "Tras la primera ronda, invoca un {kw-summon:168/167/169}.",
    "Cuerno del Sol",
    "{kw-channelblood} 1: Cura 1 de Salud /dos veces/tres veces a una Bestia herida adyacente.",
    "Danzarín de las Espadas",
    "Tiene +1 de Ataque mientras esté al máximo de salud/2 de Ataque mientras su Salud esté al máximo/3 de Ataque mientras su Salud esté al máximo. Inagotable.",
    "Curtidor",
    "Si este personaje mata a un enemigo, gana 1 de oro.",
    "Guardia de Tarus",
    "{kw-channelsoul} 1: Otorga +1/2/3 de Armadura a los demás No Muertos aliados. Máx. de almas +1.",
    "Artesana",
    "{kw-endofround}: Si este personaje tiene {kw-charge}, invoca una {kw-summon:175/176/177}.",
    "Bebedor de venenos",
    "Cuando un personaje envenenado muera, restaura 1/staura 2/cupera 3 de Salud. Venenoso.",
    "Venenomante",
    "{kw-followup}: Inflige 1/2/3 de daño a todos los enemigos envenenados. Venenoso.",
    "Oso de Guerra",
    "{kw-endofround}: Si este personaje tiene 1 de Salud, recupera 1/2 de Salud o menos, recupera 2/3 de Salud o menos, recupera 3 de Salud.",
    "Canalizador de la Ira",
    "{kw-counter}: Ataca. Inagotable.",
    "Amguan",
    "{kw-scheme}: Otorga +1/2 de {kw-charge} a todos los Reptilianos aliados.",
    "Arquero arcano",
    "{kw-endofround}: Otorga +2 de {kw-charge} a todos los Magos aliados en su misma/3 de {kw-charge} a todos los Magos aliados de su columna.",
    "Asesino",
    "Los enemigos reciben +1/2 de daño de los venenos. Venenoso.",
    "Guardia de Aviakoran",
    "{kw-counter}: Invoca una/ {kw-summon:160/161}.",
    "Clérigo de batalla",
    "{kw-followup}: Restaura 1 de Salud a todos los personajes en su misma columna.",
    "Mago de batalla",
    "Cuando este personaje consigue {kw-charge}, recupera 1/2 de Salud.",
    "Thane, el Combatiente",
    "{kw-followup}: Activa los efectos de {kw-counter} de todos los personajes adyacentes.",
    "Sanguijuela de Sangre",
    "{kw-otherunitdies}: Invoca un {kw-summon:170/171}.",
    "Elemante",
    "Cuando invoques a un Elemental aliado, gana +1 de Ataque. Tras la primera ronda, invoca un {kw-summon:165}.",
    "Portaestandartes Caído",
    "{kw-channelsoul} 1: Todos los Arqueros aliados atacan. Máx. de almas +1.",
    "Espíritu del Bosque",
    "Cuando otra Bestia aliada reciba daño, gana +1 de {kw-charge}.",
    "Hellion",
    "{kw-channelblood} 2: Ataca. Cuando este personaje mate a un enemigo, recupera 1/a a un enemigo, recupera 2 de Salud. Inagotable.",
    "Inmortal",
    "No pierde Armadura al final de la ronda.",
    "Maeledox",
    "Cuando este personaje consigue {kw-charge}, también obtiene un {kw-shield}. {kw-scheme}: Aplica una {kw-weaken} al enemigo más cercano.",
    "Guardabosques",
    "Cuando invocas un aliado, gana +2/3 de {kw-charge}. Inagotable.",
    "Capitán real",
    "{kw-endofround}: Otorga +1 de Armadura a todos los personajes en su columna.",
    "Sabio de la Palabra",
    "{kw-healthisrecovered}: Otorga +1/2 de {kw-charge} a un aliado aleatorio.",
    "Contrabandista",
    "Cuando contrates a este personaje, gana 2 de oro por cada Reptiliano aliado. {kw-death}: Gana 1/s 2 de oro por cada Reptiliano aliado. {kw-death}: Gana 2 de oro.",
    "Canal del alma",
    "{kw-channelsoul} 1: Restaura 1 de Salud. {kw-followup}: Gana +1 alma. Máx. de almas +1.",
    "Almamante",
    "{kw-endofround}: Si no tienes almas, gana +1/2 alma y +2/4 de {kw-charge}. Máx. de almas +2.",
    "Clamaespíritus",
    "{kw-channelblood} 2: {kw-revive} a una Bestia aliada.",
    "Bruja del Veneno",
    "Tras la primera /y la segunda ronda, invoca un {kw-summon:181}. Inflige el doble de daño a los personajes envenenados.",
    "Invocador del Vacío",
    "{kw-endofround}: Invoca un {kw-summon:173/174} enemigo/.",
    "Xerxis",
    "Tras la primera ronda, invoca un {kw-summon:180}.",
    "Aeron, Espíritu del Bosque",
    "Cuando un aliado muere, restaura 1 de Salud. {kw-followup}: Todos los aliados invocados atacan.",
    "Ares, el Caballero Perdido",
    "Cuando este personaje gane Armadura, también ganará +3 de {kw-charge}.",
    "Ayma, Señor de los Relámpagos",
    "{kw-counter}: Otorga +1 de {kw-charge} a todos los aliados.",
    "Cyril, maestro animista",
    "{kw-death}: Se transforma en un {kw-summon:158}. Cuando se invoca un aliado, recupera 1 de Salud.",
    "Edric, Maestro de Esgrima",
    " Ataca dos veces. Inagotable.",
    "Ixotle, guardián de las crías",
    "{kw-startofbattle} y {kw-death}: Llena tu lado del campo de batalla con {kw-summon:179}s de Reptiliano.",
    "Coloso",
    "{kw-endofround}: Por cada alma, ganas uno de dos efectos aleatorios: gana +1 de {kw-charge} o recupera 1 de Salud. Máx. de almas +2.",
    "Lyra, Luz del Amanecer",
    "{kw-healthisrecovered}: Ataca.",
    "Nangruil, el Alquimista",
    "Cuando un aliado gane armadura, gana +1 de {kw-charge}.",
    "Nyx, de la luna ancestral",
    "{kw-otherunitdies}: Aplica {kw-weaken} a un enemigo aleatorio. Inagotable.",
    "Taur, el exiliado",
    "Gana +1 de Ataque por cada Bestia aliada. Si este personaje mata a un enemigo, recupera 3 de Salud.",
    "El Devorador",
    "Cuando un personaje envenenado muere, invoca un {kw-summon:181}.",
    "La Suma Sacerdotisa",
    "{kw-followup}: Restaura 1 de Salud a todos los otros aliados.",
    "Ursa, el Oso Divino",
    "Cuando un aliado use un conjuro de sangre, ataca. Inagotable.",
    "Ven, el Gran Anciano",
    "Cuando un personaje envenenado muere, gana +1 de Ataque y recupera 1 de Salud.",
    "Zed, el Embaucador Eterno",
    "Cuando este personaje consiga {kw-charge}, invocará un {kw-summon:178} que permanecerá inmóvil.",
    "Limo replicante",
    "{kw-counter}: Invoca un {kw-summon:2}.",
    "Limo",
    "El Heraldo",
    "{kw-followup}: Invoca una {kw-summon:4}.",
    "Pila de huesos",
    "{kw-endofround}: Se transforma en un {kw-summon:5}.",
    "Esqueleto",
    "El Vigilante",
    "Ataca a un enemigo aleatorio de cualquier fila.",
    "Rata terrible",
    "Minn Muerdegrilletes",
    "{kw-endofround}: Cambia de fila.",
    "Trasgo arquero",
    "Faxel Fetterbite",
    "{kw-counter}: Inflige 1 de daño al enemigo más cercano, luego cambia de fila.",
    "Cieno restaurador",
    "Cuando un aliado muere, recupera 1 de Salud.",
    "Limo Divisor",
    "{kw-death}: Invoca 2 x {kw-summon:2}.",
    "Aziel",
    "Tiene +1 de Ataque por cada Esqueleto aliado. {kw-followup}: Invoca una {kw-summon:4}.",
    "Dienterrata",
    "{kw-endofround}: Invoca una Bestia aleatoria.",
    "Cobra",
    "Ataca dos veces.",
    "Murciélago",
    "Herrero de los Muerdegrilletes",
    "{kw-endofround}: Otorga +4 de Armadura a un aliado aleatorio.",
    "Guarda Esquelético",
    "Cieno metálico",
    "{kw-endofround}: Gana +1 de Armadura, luego se mueve.",
    "Dienteamargo",
    "{kw-followup}: Otorga +1 de Ataque a una Bestia aliada aleatoria.",
    "Flit Muerdegrilletes",
    "{kw-counter}: Gana +1 de {kw-charge}.",
    "Fial Muerdegrilletes",
    "Si un personaje cualquiera muere, gana +1 de Ataque.",
    "El Muerdegrilletes perdido",
    "{kw-endofround}: Invoca un {kw-summon:16}.",
    "Matriarca",
    "Escarabajo Carroñero",
    "{kw-endofround}: Otorga +2 de Armadura a la Matriarca.",
    "Limo colosal",
    "{kw-endofround}: Invoca 2 x {kw-summon:2} y cambia de fila.",
    "Limo solidificado",
    "Coloso Reanimado",
    "Doblemante",
    "Rey Muerdegrilletes",
    "{kw-endofround}: Invoca un {kw-summon:9}.",
    "El Orbe de Mando",
    "Los Trasgos tienen +1 de Ataque. Invisible.",
    "Colmillo Plateado",
    "Venenoso. {kw-endofround}: Cambia de fila.",
    "Espejismo Deteriorado",
    "{kw-death}: Invoca un {kw-summon:35}.",
    "Espejismo de Acéfalo",
    "{kw-followup}: Se mueve.",
    "Engendro de Valac",
    "{kw-endofround}: Invoca un {kw-summon:37}.",
    "Orbe Errante",
    "Ataca a uno de los enemigos más cercanos de cualquier fila.",
    "Devorador",
    "{kw-followup}: Restaura 2 de Salud a un aliado herido.",
    "Licántropo",
    "Reina Orbe",
    "Tiene +1 de Ataque por cada aliado.",
    "Masa de Orbes",
    "{kw-death}: Invoca 3 x {kw-summon:37}. {kw-endofround}: Se mueve.",
    "Matorral Convocado",
    "{kw-endofround}: Invoca 2 x {kw-summon:43}.",
    "Matorral Maldito",
    "{kw-death}: Inflige 2 de daño al enemigo más cercano en su misma fila.",
    "La Bruja",
    "Venenoso. {kw-endofround}: Invoca un {kw-summon:2} aleatorio. Después, se mueve.",
    "Ladrón",
    "Cuando este personaje mate a un enemigo, roba 1 de oro.",
    "Espejismo de Venina",
    "Ataque paralizador. {kw-endofround}: Cambia de fila.",
    "Espejismo Perfecto",
    "Cuando este personaje mate a un enemigo, recupera 2 de Salud.",
    "Mímico",
    "Araña",
    "Venenoso.",
    "Progenitor del Orbe",
    "{kw-endofround}: Invoca 2 x {kw-summon:37}.",
    "Espejismo de Clypaes",
    "{kw-endofround}: Otorga {kw-shield} a otro aliado.",
    "Líder de la manada",
    "Ataca al enemigo con menor Salud.",
    "Espíritu de la Cueva",
    "Espejismo de Firis",
    "{kw-counter}: Inflige 1 de daño al enemigo más cercano.",
    "La Hechicera",
    "Cuando un aliado muere, otorga +2 de Ataque a otro aliado.",
    "El Antiguo",
    "Cuando una Bestia aliada muere, gana +1 de Ataque. {kw-endofround}: Cambia de fila.",
    "Licántropo Alfa",
    "{kw-death}: Invoca 2 x {kw-summon:39}. {kw-endofround}: Cambia de fila.",
    "Firis",
    "Clypaes",
    "Venina",
    "Ataque paralizador. {kw-endofround}: Se mueve.",
    "Espejismo Primordial",
    "{kw-followup}: Inflige 5 de daño a todos los aliados y gana +1 de Ataque.",
    "Pozo de espejismos",
    "{kw-endofround}: Invoca un {kw-summon:34}. Invisible.",
    "Aquel Que No Ve",
    "Ataca al enemigo con la Salud más alta. Venenoso.",
    "Escórpido",
    "{kw-endofround}: Se mueve.",
    "Escórpido Esquelético",
    "Ataca tres veces.",
    "Caminante del Abismo",
    "{kw-endofround}: Invoca un {kw-summon:67}.",
    "Wisp de Llamas",
    "{kw-death}: Otorga +2 de {kw-charge} a todos los aliados.",
    "Pesadilla",
    "{kw-endofround}: Paraliza a un enemigo aleatorio.",
    "Terror cristalino",
    "{kw-death}: Invoca un {kw-summon:70}.",
    "Terror",
    "Resplandor Amenazador",
    "{kw-endofround}: Invoca 2 x {kw-summon:72}, luego se mueve.",
    "Resplandor Inestable",
    "{kw-endofround}: Inflige 5 de daño a TODOS los personajes de esta fila.",
    "Sirviente del Fuego",
    "{kw-followup}: Cambia de fila y gana +1 de Ataque.",
    "Príncipe de Ascuas",
    "Ataques malditos. Invisible. {kw-followup}: Se mueve.",
    "Trol anciano",
    "Trol",
    "Espíritu de Ascuas",
    "{kw-endofround}: Gana +15 de Armadura, luego se mueve. Tiene una bonificación de Ataque igual a su Armadura.",
    "Urna espiritual",
    "{kw-death}: Destruye al Espíritu de Ascuas.",
    "Sirviente de la Sombra",
    "Tiene +1 de Ataque por cada enemigo presente.",
    "Príncipe de las Sombras",
    "Confundido. Invisible. {kw-followup}: Se mueve.",
    "Guardián del Abismo",
    "{kw-endofround}: Invoca un {kw-summon:82}.",
    "Wisp Infernal",
    "{kw-death}: Otorga +1 de Ataque al Guardián del Abismo.",
    "Gigante de Carne",
    "Los ataques aplican 2 acumulaciones de {kw-affliction}. {kw-endofround}: Cambia de fila.",
    "Gusano de Carne",
    "Sirviente de la Codicia",
    "Ataca dos veces. {kw-endofround}: Cambia de fila.",
    "Príncipe Dorado",
    "{kw-followup}: Roba 1 de oro. Invisible.",
    "El Usurpador de Mentes",
    "Los ataques aplican un efecto de estado aleatorio. Ataca aleatoriamente.",
    "Campeón del Vacío",
    "{kw-endofround}: Gana +1 de Ataque y se mueve.",
    "La Mano de Abaddon",
    "Cuando un monstruo aliado muere, gana +1 de Ataque. Ataca a uno de los enemigos más cercanos de cualquier fila.",
    "Sacerdote de Abbadon",
    "{kw-counter}: Otorga +2 de Armadura a la Mano de Abaddon.",
    "Sacerdotisa de Abaddon",
    "{kw-counter}: Otorga +2 de {kw-charge} a la Mano de Abaddon.",
    "Llama Primigenia",
    "{kw-followup}: Inflige 2 de daño a todos los personajes en su misma fila. {kw-endofround}: Se mueve.",
    "Llama Sombría Menor",
    "{kw-death}: Invoca una {kw-summon:94}. Invisible.",
    "Llama Sombría",
    "{kw-death}: Invoca una {kw-summon:95}. Invisible.",
    "Llama Sombría Mayor",
    "Invisible.",
    "Abaddon",
    "Se transforma en cada turno.",
    "Esfera Dorada",
    "Esfera Maldita",
    "{kw-death}: Maldice a un enemigo aleatorio.",
    "Esfera Envenenada",
    "{kw-death}: Aplica {kw-poison} al enemigo con la Salud más baja.",
    "Devorador de Esperanza",
    "Los personajes no pueden recuperar Salud.",
    "Devorador de Fuerza",
    "Los personajes no pueden ganar Armadura.",
    "El Guardián",
    "Ataca a un personaje aleatorio de cualquier fila. Invisible.",
    "Illifar",
    "Bathin",
    "Ataque paralizador. Ataca al enemigo con la Salud más alta.",
    "Bathin, el Grande",
    "{kw-death}: Paraliza a todos los enemigos no heroicos.",
    "Andromalius",
    "Los ataques aplican 2 acumulaciones de {kw-affliction}.",
    "Morax",
    "{kw-endofround}: Illifar gana +5 de Armadura. Venenoso.",
    "Aamon",
    "{kw-endofround}: Illifar gana +3 de {kw-charge}.",
    "Haagenti",
    "Los ataques ignoran la Armadura.",
    "Valac",
    "{kw-endofround}: Invoca un {kw-summon:37}. Ataca a un personaje aleatorio de cualquier fila.",
    "Orobas",
    "{kw-endofround}: Todos los aliados ganan +1 de {kw-charge}. Invisible.",
    "Nazzatoth",
    "{kw-endofround}: Invoca 2 x Sombra.",
    "Sombra de la Llama Negra",
    "{kw-endofround}: Invoca 2 x {kw-summon:121} en su misma fila. Invisible.",
    "Sombra Maldita",
    "Ataques malditos. Invisible.",
    "Sombra Aulladora",
    "Sombra Embelesadora",
    "Confundido. Invisible.",
    "Sombra Inestable",
    "{kw-followup}: Inflige 2 de daño a todos los personajes en su misma fila. Invisible.",
    "Sombra Afligida",
    "Los ataques aplican 2 acumulaciones de {kw-affliction}. Invisible.",
    "Sombra Eléctrica",
    "Ataca tres veces. Invisible.",
    "Llama Oscura",
    "El Guardián del Portal",
    "Vacío",
    "{kw-death}: Aplica un efecto de estado aleatorio a un enemigo aleatorio.",
    "{kw-endofround}: Otorga +4 de {kw-charge} a un aliado aleatorio.",
    "Ojo de Abaddon",
    "Ataca al enemigo con la Salud más alta. Invisible.",
    "Ojo de Illifar",
    "Inflige el doble de daño a los enemigos afligidos. Invisible. {kw-endofround}: Cambia de fila.",
    "Ojo de Nazzatoth",
    "Los ataques aplican 2 acumulaciones de {kw-affliction}. Invisible. {kw-endofround}: Cambia de fila.",
    "{kw-endofround}: Invoca un Reflejo con una habilidad aleatoria.",
    "El Reflejo del Guardián",
    "{kw-endofround} y {kw-death}: Inflige 10 de daño al enemigo más cercano en su misma fila.",
    "{kw-endofround} y {kw-death}: Inflige 1 de daño a todos los enemigos.",
    "{kw-endofround} y {kw-death}: Inflige 4 de daño dos veces al enemigo más cercano en su misma fila.",
    "{kw-endofround} y {kw-death}: Inflige 5 de daño al enemigo más cercano en su misma fila, y le aplica 2 acumulaciones de {kw-affliction}.",
    "{kw-endofround} y {kw-death}: Inflige 3 de daño al enemigo con mayor Salud y lo paraliza.",
    "Gusano Áureo",
    "{kw-death}: Gana 13 de oro. Venenoso.",
    "Sombra de la Mazmorra",
    "Reduce al enemigo con mayor salud a 1 de Salud.",
    "Wisp Dorado",
    "Desaparece al final de la segunda ronda. {kw-endofround}: Cambia de fila.",
    "Cofre del tesoro",
    "Aventurero perdido",
    "Urna antigua",
    "Barril",
    "Urna de metal",
    "Matorral",
    "No se puede mover.",
    "Roca",
    "Barril explosivo",
    "{kw-death}: Inflige 2 de daño a TODOS los personajes en esta fila.",
    "Discípulo Leal",
    "No cuenta para tu límite máx. de grupo.",
    "Limo cósmico",
    "{kw-endofround}: Todos los demás Elementales aliados ganan +1 de {kw-charge}. No cuenta para tu límite máx. de grupo.",
    "Estatua Dorada",
    "Se vende por 10 de oro en los campamentos.",
    "Estatua excepcional",
    "Se vende por 15 de oro en los campamentos.",
    "Asmodel, el Dorado",
    "{kw-endofround}: Gana un {kw-shield}. Se vende por 15 de oro en los campamentos.",
    "Cyril, el sacudidor de la tierra",
    "Cuando se invoca un aliado, recupera 1 de Salud.",
    "Jack",
    "Paloma",
    "Cuervo",
    "Lobo",
    "Llama Eterna",
    "{kw-endofround}: Otorga +1 de {kw-charge} a un aliado.",
    "Espíritu Vengador",
    "Inagotable.",
    "Wisp del Relámpago",
    "{kw-death}: Todos los aliados ganan +1 de {kw-charge}.",
    "Wisp Sagrado",
    "{kw-endofround}: Cura 1 de Salud a un aliado dañado que no sea un héroe.",
    "Wisp de Metal",
    "{kw-endofround}: Otorga +1 de Armadura a otro aliado en esta fila.",
    "Wisp de Metal Menor",
    "Wisp de Metal Mayor",
    "Wisp Sangriento",
    "Wisp Sangriento Mayor",
    "Wisp Menor del Vacío",
    "Se ataca a sí mismo. {kw-death}: Inflige 1 de daño a todos los aliados.",
    "Wisp del Vacío",
    "Se ataca a sí mismo. {kw-death}: Inflige 2 de daño a todos los aliados.",
    "Wisp Mayor del Vacío",
    "Se ataca a sí mismo. {kw-death}: Inflige 3 de daño a todos los aliados.",
    "Bomba",
    "Bomba grande",
    "{kw-death}: Inflige 4 de daño a TODOS los personajes de esta fila.",
    "Bomba dorada",
    "{kw-death}: Inflige 6 de daño a TODOS los personajes de esta fila.",
    "Reflejo de espejo",
    "Cría",
    "Envenenescamoso",
    "Limo Venenoso",
    "Sombra Sangrienta",
    "{kw-death}: Inflige 4 de daño a un héroe aliado.",
    "Martillo Espectral",
    "{kw-followup}: Recibe 1 de daño. Inagotable.",
    "Gran Martillo Espectral",
    "Martillo Espectral Dorado",
    "Elige tu héroe",
    "Sangre de Abaddon: Gana 3 de oro.",
    "Sangre de Illifar: Obtén un personaje aleatorio de nivel 2.",
    "Sangre de Nazzatoth: Gana un artículo raro.",
    "Alma del Guardián: El tamaño de tu grupo aumenta en 1. La salud máxima de tus héroes es 1.",
    "Canción de la Muerte: +25 % de puntuación Los héroes enemigos tienen +1 de Ataque.",
    "Campamento",
    "Las hogueras tienen más personajes que contratar que los campamentos. Si desbloqueas nuevas unidades, también desbloquearás más hogueras.",
    "Oh, hola. ¿Necesitas llaves?",
    "El mercader",
    "La Bruja",
    "Elige un anillo.",
    "El mercado negro vende objetos a un precio más bajo que las tiendas normales.",
    "Aamon ofrece anillos malditos. La maldición dependerá de tu héroe actual.",
    "Un anillo de obsidiana... ¿Puedo verlo? Se parece a uno que perdí hace mucho tiempo.",
    "camino",
    "héroe",
    "artefacto",
    "personaje",
    "artículo",
    "mejora",
    "monstruo",
    "grupo",
    "Nueva partida",
    "Nueva partida +",
    "Nueva partida ++",
    "Nueva partida +++",
    "Nueva partida ++++",
    "Nueva partida +++++",
    "Leyenda",
    "Todas las zonas",
    "Mazmorra superior",
    "Lo Profundo",
    "El Abismo",
    "El portal"
];
