var L = [
    "",
    "Humano",
    "Bestia",
    "Enano",
    "Elemental",
    "Elfo",
    "Duende",
    "Monstruo",
    "No muerto",
    "Constructo",
    "Planta",
    "Gnomo",
    "Dios ancestral",
    "Reptiliano",
    "Demonio",
    "???",
    "Luchador",
    "Mago",
    "Arquero",
    "Héroe",
    "Multiclase",
    "Discípulo",
    "Solo frente",
    "Atrás solo",
    "-",
    "Ataque",
    "Salud",
    "Velocidad",
    "Muerte",
    "MUERTE: Condición activada al morir.",
    "Fin de ronda",
    "FIN DE RONDA: Condición activada después de que todos los personajes ataquen. Ignora el agotamiento.",
    "Continuación",
    "CONTINUACIÓN: Ejecuta otra acción después del ataque normal del personaje.",
    "Condena",
    "CONDENA: Condición activada si muere un personaje enemigo.",
    "Esperanza",
    "ESPERANZA: Condición activada cuando la Salud de un personaje aliado aumenta.",
    "Esquema",
    "ESQUEMA: Condición activada si el personaje no ataca.",
    "Inicio de batalla",
    "INICIO DE BATALLA: Condición activada cuando comienza la batalla.",
    "Poder de almas",
    "Poder de almas X: Usa X almas para activar una habilidad entre rondas. Puede usarse una vez por ronda. Haz clic derecho para usar.",
    "Veneno",
    "VENENO: Los personajes envenenados reciben 1 de daño después de su ataque normal. Dura hasta el final de esta batalla. No se acumula.",
    "Maldición",
    "MALDICIÓN: La próxima vez que este personaje sea atacado, recibirá el doble de daño.",
    "Escudo",
    "ESCUDO: La próxima vez que este personaje reciba daño, lo anulará por completo.",
    "Contraataque",
    "CONTRAATAQUE: Condición activada cuando el personaje pierde Salud y sobrevive.",
    "Aflicción",
    "AFLICCIÓN: ALos personajes afligidos no pueden ganar Salud, Armadura o Poder. Al final del turno del personaje, se elimina una acumulación de Aflicción.",
    "Poder",
    "PODER: El próximo ataque inflige más daño.",
    "Armadura",
    "ARMADURA: La cantidad de daño que puede recibir un personaje antes de perder Salud. La Armadura se pierde al final de cada ronda.",
    "Conjuro de sangre",
    "Conjuro de sangre X: Sufres daño para activar una habilidad entre rondas. Puede usarse una vez por ronda. Haz clic derecho para usar.",
    "Revivir",
    "Revivir: Revive a un aliado con 1 de Salud.",
    "Maná",
    "Maná:nGasta maná para activar una habilidad entre asaltos. Puede usarse una vez por asalto. Clic derecho para lanzar.",
    "Invocado",
    "Los personajes que usan y se benefician de las invocaciones aparecerán con mayor frecuencia en las fogatas.",
    "Nivel",
    "Sobrenivel",
    "Este personaje puede subir de nivel infinitamente. Obtiene esta bonificación a nivel 4 y cada nivel posterior.",
    "camino",
    "héroe",
    "artefacto",
    "personaje",
    "artículo",
    "mejora",
    "monstruo",
    "grupo",
    "Campamento",
    "Recluta o deshazte de personajes. Pulsa clic derecho para quitar objetos.",
    "Hoguera",
    "Las hogueras tienen más personajes que contratar que los campamentos. Si desbloqueas nuevas unidades, también desbloquearás más hogueras.",
    "Cofre del tesoro",
    "Se transforma en un objeto aleatorio.",
    "Sala del tesoro",
    "Gana 3 de oro.",
    "Bathin",
    "Bathin te ofrecerá tratos opcionales con los que aumentar la dificultad de tu próxima batalla a cambio de oro.",
    "Mercader",
    "Compra y vende objetos. Haz clic derecho para desequipar objetos.",
    "La Bruja",
    "¡Tú! ¡Tengo más pociones a la venta!",
    "Andromalius",
    "Andromalius transformará una pieza de equipo.  Haz clic derecho para quitar una pieza de equipo de un personaje, y luego colócala en el Vacío.",
    "El Forjador de Llaves",
    "Oh, hola. ¿Necesitas llaves?",
    "El gigante",
    "Elige un anillo.",
    "Contrabandista",
    "El mercado negro vende objetos a un precio más bajo que las tiendas normales.",
    "El mago perdido",
    "Un anillo de obsidiana... ¿Puedo verlo? Se parece a uno que perdí hace mucho tiempo.",
    "Sala del tesoro de Aamon",
    "Aamon ofrece anillos malditos. La maldición dependerá de tu héroe actual.",
    "Cofre de artefactos",
    "Escoge un artefacto.",
    "Elige tu héroe",
    "Sangre de Abaddon",
    "Gana 8 de oro.",
    "Sangre de Illifar",
    "Obtén un personaje aleatorio de nivel 2.",
    "Sangre de Nazzatoth",
    "Gana un artículo raro.",
    "Alma del Guardián",
    "El tamaño de tu grupo aumenta en 1. La salud máxima de tus héroes es 1.",
    "Canción de la Muerte",
    "+25 % de puntuación Los héroes enemigos tienen +1 de Ataque.",
    "Nueva partida",
    "Nueva partida +1",
    "Nueva partida +2",
    "Nueva partida +3",
    "Nueva partida +4",
    "Nueva partida +5",
    "Leyenda",
    "Todas las zonas",
    "Mazmorra superior",
    "Lo Profundo",
    "El Abismo",
    "El portal",
    "La Torre",
    "Qué alma tan desafortunada",
    "El aventurero perdido",
    "Devorador",
    "{kw-followup}: Restaura 2 de Salud a un aliado herido.",
    "Líder de la manada",
    "Ataca al enemigo con menor Salud.",
    "Noble de la vieja tierra",
    "Thoric del Martillo",
    "{kw-endofround}: Gana +1 de Armadura.",
    "Maestro herrero",
    "{kw-endofround}: Otorga +1 de Armadura al aliado más adelantado en su fila.",
    "El último astrónomo",
    "Eloa",
    "{kw-followup}: Otorga +1 de {kw-charge} a un aliado en su fila.",
    "Inagotable.",
    "Investigador arcano",
    "{kw-endofround}: Otorga +2 de {kw-charge} a un Mago aliado en su misma fila.",
    "Sombra de la Luna Ancestral",
    "Taz'gyn",
    "{kw-channelmana}: invoca un {kw-summon:0}.",
    "Invocador ascendido",
    "Si un personaje mata a un enemigo, invoca una {kw-summon:1}.",
    "Taz'gyn, Campeón de la Orden",
    "{kw-otherunitdies}: Gana +1 de {kw-charge}.",
    "El cocinero viajero",
    "Dominique Boutroux",
    "{kw-followup}: Cura 1 de Salud a un aliado dañado en su misma fila.",
    "Vendedor Ambulante",
    "{kw-startofbattle}: Ganas 1 de oro.",
    "La nadadora solitaria",
    "Anciana Gryx",
    "Cuando un aliado muere, ataca.",
    "Matriarca de la Progenie",
    "Venenoso.",
    "El príncipe joven",
    "Xandos III",
    "Comienza con {kw-relic:51}.",
    "Xandos, el Grande",
    "Conocimientos itinerantes",
    "Mariana",
    "{kw-startofbattle}: Invoca a {kw-summon:2}.",
    "Animara",
    "Si un personaje lanza un conjuro de sangre, gana +1 de {kw-charge}.",
    "Efigie del más allá",
    "Elsbeth",
    "{kw-channelsoul} 1: Inflige 2 de daño al enemigo más cercano. Máx. de almas +1.",
    "Elsbeth, Bruja del Pantano",
    "{kw-startofbattle}: Envenena a dos enemigos aleatorios.",
    "Buscador de Venganza",
    "Comienza con {kw-relic:47}.",
    "Emperador Dorado",
    "Tiene +1 de Ataque por cada 5 de oro.",
    "Artificiero",
    "Comienza con dos reliquias adicionales aleatorias.",
    "Cieno restaurador",
    "Cuando un aliado muere, recupera 1 de Salud.",
    "Limo replicante",
    "{kw-counter}: Invoca un {kw-summon:42}.",
    "Cieno metálico",
    "{kw-endofround}: Gana +1 de Armadura, luego se mueve.",
    "Haruspex",
    "{kw-otherunitdies}: Inflige {kw-scaling:1/1/0} de daño a un enemigo aleatorio.",
    "Sectario",
    "{kw-otherunitdies}: Recupera {kw-scaling:1/0/0} de Salud.",
    "Berserker",
    "{kw-counter}: Gana +1/2/3 de {kw-charge}.",
    "Danzarín de las Espadas",
    "Tiene +1/2/3 de Ataque mientras esté al máximo de salud.",
    "Encantador",
    "{kw-endofround}: Otorga +1 de {kw-charge} a todos los Magos aliados.",
    "Cazador",
    "{kw-followup}: Inflige 1 de daño /dos veces/tres veces al enemigo con menor Salud.",
    "Forjador",
    "{kw-endofround}: Otorga +{kw-scaling:1/1/0} de Armadura a otro aliado en esta fila.",
    "Mago del Sol",
    "Ganas el doble de {kw-charge}.",
    "Clérigo del Camino",
    "{kw-followup}: Restaura {kw-scaling:1/0/0} de Salud a un aliado herido que no sea un héroe.",
    "Clérigo de la Rosa",
    "{kw-healthisrecovered}: Inflige {kw-scaling:1/0/0} de daño al enemigo más cercano en su misma fila.",
    "Caballero con armadura",
    "Tiene una bonificación de Ataque igual a su Armadura.",
    "Druida",
    "{kw-channelmana} {kw-scaling:0/1/1}: invoca una {kw-summon:6/7/8} dos veces.",
    "Protector Divino",
    "Cuando invocas a un aliado, le otorga un {kw-shield}.",
    "Escudero",
    "{kw-endofround}: Otorga +1/2/3 de {kw-charge} a otro aliado en esta fila.",
    "Aguatilis",
    "Cuando un aliado muere, gana +2/3/4 de {kw-charge}.",
    "Hipogeo",
    "{kw-scheme}: Recupera 1 de Salud por cada Reptiliano aliado.",
    "Guardabosques",
    "Cuando invocas un aliado, gana +1/2/3 de {kw-charge}.",
    "Súbdito de los Fey",
    "Los aliados invocados tienen +{kw-scaling:1/0/0} de Ataque.",
    "Pícaro",
    "Curtidor",
    "Si este personaje mata a un enemigo, gana 1 de oro.",
    "Guardia Real",
    "Cuando este personaje gane Salud, tu héroe gana +1/2/3 de {kw-charge}.",
    "Canalizador",
    "{kw-followup}: Activa todos los efectos aliados de Condena.",
    "Jabalinero",
    "Ataca después de ganar Armadura.",
    "Francotirador",
    "Cuando a un enemigo se le aplica un {kw-poison}, le inflige {kw-scaling:1/0/0} de daño.",
    "Praexator",
    "Cuando este personaje mata a un enemigo, otorga +1 de {kw-charge} a todos los Reptilianos aliados.",
    "Erudito del Relámpago",
    "Cuando este personaje gana {kw-charge}, inflige {kw-scaling:1/0/0} de daño a un enemigo aleatorio.",
    "Invocador de Acero",
    "{kw-channelmana} {kw-scaling:0/1/1}: invoca un {kw-summon:12/13/14}.",
    "Clérigo de la Oscuridad",
    "Cuando este personaje mata a un enemigo, gana {kw-shield}.",
    "{kw-channelmana} {kw-scaling:0/1/1}: Obtienes {kw-shield}.",
    "Exanguinador",
    "{kw-endofround}: Invoca una {kw-summon:15} en su misma fila.",
    "Carnicero",
    "Cuando este personaje mata a un enemigo, cura 1 de Salud a un aliado daña/e a un enemigo, restaura 1 de Salud dos veces a un aliado heri/e a un enemigo, restaura 1 de Salud tres veces a un aliado herido que no sea un héroe.",
    "Bebedor de venenos",
    "Cuando un personaje envenenado muera, recupera {kw-scaling:1/0/0} de Salud.",
    "Clérigo del Martillo",
    "{kw-endofround}: Invoca un {kw-summon:16/17/18}.",
    "Maestro cervecero",
    "{kw-counter}: Restaura 2 de Salud a un aliado herido que no sea un héroe.",
    "Herrero Rúnico",
    "Cuando otro Enano reciba daño, gana +1 de {kw-charge}. {kw-endofround}: Gana +1 de Armadura por cada Enano presente.",
    "Arquero Mortífero",
    "Gana +1 de daño por cada No Muerto aliado.",
    "Guardia de Tarus",
    "{kw-channelsoul} 1: Otorga +1/2/3 de Armadura a los demás No Muertos aliados. Máx. de almas +1.",
    "Bebealmas",
    "{kw-endofround}: Si tienes 2 almas o más, restaura {kw-scaling:1/0/0} de Salud. Máx. de almas +2.",
    "Adepto Caído",
    "{kw-channelsoul} X: Inflige X de daño/daño doble/daño cuádruple al enemigo más cercano en su misma fila. Máx. de almas +3.",
    "Nigromante",
    "{kw-channelsoul} 2: Invoca un {kw-summon:3}. Máx. de almas +2.",
    "Sangre de Hierro",
    "{kw-channelblood} 1: Ganas +1 de Armadura por cada aliado herido.",
    "Sangre de Ascuas",
    "{kw-channelblood} 2: Gana +1 de Ataque.",
    "Cuerno del Sol",
    "{kw-channelblood} 1: Cura 1 de Salud /dos veces/tres veces a una Bestia herida adyacente.",
    "Oso de Guerra",
    "{kw-endofround}: Si este personaje tiene 1 de Salud, recupera 1/2 de Salud o menos, recupera 2/3 de Salud o menos, recupera 3 de Salud.",
    "Erudito de la Llama",
    "También afecta a los enemigos en la misma columna.",
    "{kw-channelmana} {kw-scaling:1/0/0}: ataca.",
    "Artesana",
    "{kw-endofround}: Si este personaje tiene {kw-charge}, invoca una {kw-summon:20/21/22}.",
    "Canalizador de la Ira",
    "{kw-counter}: Ataca.",
    "Arquero nocturno",
    "{kw-otherunitdies}: Gana +1/2/3 de {kw-charge}.",
    "Venenomante",
    "{kw-followup}: Inflige {kw-scaling:1/0/0} de daño a todos los enemigos envenenados.",
    "Praliator",
    "Si este personaje mata a un enemigo, ataca de nuevo.",
    "Bruja del Veneno",
    "Inflige el doble de daño a los personajes envenenados.",
    "{kw-channelmana} {kw-scaling:1/-1/0}: Invoca un {kw-summon:9}.",
    "Sanguijuela de Sangre",
    "{kw-otherunitdies}: Invoca un {kw-summon:10/11}.",
    "Arquero arcano",
    "{kw-endofround}: Otorga +2/3 de {kw-charge} a todos los Magos aliados en su misma columna.",
    "Asesino",
    "Los enemigos reciben +{kw-scaling:1/-1/0} de daño de los venenos.",
    "Maeledox",
    "Cuando este personaje consigue {kw-charge}, también obtiene un {kw-shield}. {kw-scheme}: Aplica una {kw-weaken} al enemigo más cercano.",
    "Thane, el Combatiente",
    "{kw-followup}: Activa los efectos de {kw-counter} de todos los personajes adyacentes.",
    "Xerxis",
    "{kw-channelmana} {kw-scaling:1/-1/0}: invoca un {kw-summon:19}.",
    "Amguan",
    "{kw-scheme}: Otorga +1/2 de {kw-charge} a todos los Reptilianos aliados.",
    "Canal del alma",
    "{kw-channelsoul} 1: Restaura 1/2 de Salud. {kw-followup}: Gana +1 alma. Máx. de almas +1.",
    "Espíritu del Bosque",
    "Cuando otra Bestia aliada reciba daño, gana +1/2 de {kw-charge}.",
    "Hellion",
    "{kw-channelblood} 2: Ataca. Cuando este personaje mate a un enemigo, recupera 1/2 de Salud.",
    "Clamaespíritus",
    "{kw-channelblood} 2: {kw-revive} a una Bestia aliada.",
    "Guardia de Aviakoran",
    "{kw-counter}: Invoca una {kw-summon:6/7}.",
    "Inmortal",
    "No pierde Armadura al final de la ronda.",
    "Mago de batalla",
    "Cuando este personaje consigue {kw-charge}, recupera 1/2 de Salud.",
    "Clérigo de batalla",
    "{kw-followup}: Restaura 1 de Salud a todos los personajes en su misma columna.",
    "Invocador del Vacío",
    "{kw-endofround}: Invoca un {kw-summon:23/24} enemigo.",
    "Almamante",
    "{kw-endofround}: Si no tienes almas, gana +1/2 alma y +2/4 de {kw-charge}. Máx. de almas +2.",
    "Elemante",
    "Cuando invoques a un Elemental aliado, gana +1 de Ataque.",
    "{kw-channelmana} {kw-scaling:1/-1/0}: invoca un {kw-summon:25}.",
    "Capitán real",
    "{kw-endofround}: Otorga +1 de Armadura a todos los personajes en su columna.",
    "Sabio de la Palabra",
    "{kw-healthisrecovered}: Otorga +1/2 de {kw-charge} a un aliado aleatorio.",
    "Cuando contrates a este personaje, gana 2 de oro por cada Reptiliano aliado. {kw-death}: Gana 1/2 de oro.",
    "Portaestandartes Caído",
    "{kw-channelsoul} 1: Todos los Arqueros aliados atacan. Máx. de almas +1.",
    "Coloso",
    "{kw-endofround}: Por cada alma, ganas uno de dos efectos aleatorios: gana +1 de {kw-charge} o recupera 1 de Salud. Máx. de almas +2.",
    "Ares, el Caballero Perdido",
    "Cuando este personaje gane Armadura, también ganará +3 de {kw-charge}.",
    "Edric, Maestro de Esgrima",
    "Ataca dos veces.",
    "Cyril, maestro animista",
    "Cuando se invoca un aliado, recupera 1 de Salud.",
    "{kw-death}: Se transforma en un {kw-summon:26}.",
    "Ixotle, guardián de las crías",
    "{kw-startofbattle} y {kw-death}: Llena tu lado del campo de batalla con {kw-summon:27}s de Reptiliano.",
    "Taur, el exiliado",
    "Gana +1 de Ataque por cada Bestia aliada. Si este personaje mata a un enemigo, recupera 3 de Salud.",
    "Zed, el Embaucador Eterno",
    "Cuando este personaje consiga {kw-charge}, invocará un {kw-summon:28} que permanecerá inmóvil.",
    "Nyx, de la luna ancestral",
    "{kw-otherunitdies}: Aplica {kw-weaken} a un enemigo aleatorio.",
    "Lyra, Luz del Amanecer",
    "Ataca a un enemigo aleatorio de cualquier fila.",
    "{kw-healthisrecovered}: Ataca.",
    "El Devorador",
    "Cuando un personaje envenenado muere, invoca un {kw-summon:9}.",
    "Ayma, Señor de los Relámpagos",
    "{kw-counter}: Otorga +1 de {kw-charge} a todos los aliados.",
    "La Suma Sacerdotisa",
    "{kw-followup}: Restaura 1 de Salud a todos los otros aliados.",
    "Nangruil, el Alquimista",
    "Cuando un aliado gane armadura, gana +1 de {kw-charge}.",
    "Ven, el Gran Anciano",
    "Cuando un personaje envenenado muere, gana +1 de Ataque y recupera 2 de Salud.",
    "Aeron, Espíritu del Bosque",
    "Cuando un aliado muere, restaura 1 de Salud. {kw-followup}: Todos los aliados invocados atacan.",
    "Ursa, el Oso Divino",
    "Cuando un aliado use un conjuro de sangre, ataca.",
    "Wisp Menor del Vacío",
    "Se ataca a sí mismo. {kw-death}: Inflige 1 de daño a todos los aliados.",
    "Pila de huesos",
    "{kw-endofround}: Se transforma en un {kw-summon:3}.",
    "Jack",
    "Esqueleto",
    "Llama Eterna",
    "{kw-endofround}: Otorga +1 de {kw-charge} a un aliado.",
    "Wisp Sagrado",
    "{kw-endofround}: Cura 1 de Salud a un aliado dañado que no sea un héroe.",
    "Paloma",
    "Cuervo",
    "Lobo",
    "Limo Venenoso",
    "Wisp Sangriento",
    "Wisp Sangriento Mayor",
    "Wisp de Metal Menor",
    "{kw-endofround}: Otorga +1 de Armadura a otro aliado en esta fila.",
    "Wisp de Metal",
    "{kw-endofround}: Otorga +2 de Armadura a otro aliado en esta fila.",
    "Wisp de Metal Mayor",
    "{kw-endofround}: Otorga +3 de Armadura a otro aliado en esta fila.",
    "Sombra Sangrienta",
    "{kw-death}: Inflige 4 de daño a un héroe aliado.",
    "Martillo Espectral",
    "{kw-followup}: Recibe 1 de daño.",
    "Gran Martillo Espectral",
    "Martillo Espectral Dorado",
    "Envenenescamoso",
    "Bomba",
    "{kw-death}: Inflige 2 de daño a TODOS los personajes en esta fila.",
    "Bomba grande",
    "{kw-death}: Inflige 4 de daño a TODOS los personajes de esta fila.",
    "Bomba dorada",
    "{kw-death}: Inflige 6 de daño a TODOS los personajes de esta fila.",
    "Wisp del Vacío",
    "Se ataca a sí mismo. {kw-death}: Inflige 2 de daño a todos los aliados.",
    "Wisp Mayor del Vacío",
    "Se ataca a sí mismo. {kw-death}: Inflige 3 de daño a todos los aliados.",
    "Wisp del Relámpago",
    "{kw-death}: Todos los aliados ganan +1 de {kw-charge}.",
    "Cyril, el sacudidor de la tierra",
    "Cría",
    "Reflejo de espejo",
    "No se puede mover.",
    "Limo cósmico",
    "No cuenta para tu límite máx. de grupo.",
    "{kw-endofround}: Todos los demás Elementales aliados ganan +1 de {kw-charge}.",
    "Asmodel, el Dorado",
    "Se vende por 15 de oro en los campamentos.",
    "{kw-endofround}: Gana un {kw-shield}.",
    "Estatua excepcional",
    "Estatua Dorada",
    "Se vende por 10 de oro en los campamentos.",
    "Discípulo Leal",
    "Matorral",
    "Wisp Dorado",
    "Desaparece al final de la segunda ronda.",
    "{kw-endofround}: Se mueve.",
    "Aventurero perdido",
    "El Heraldo",
    "{kw-followup}: Invoca una {kw-summon:1}.",
    "El Vigilante",
    "Ataca a un personaje aleatorio de cualquier fila.",
    "Rata terrible",
    "Limo",
    "Barril",
    "Minn Muerdegrilletes",
    "{kw-endofround}: Cambia de fila.",
    "Trasgo arquero",
    "Dienterrata",
    "{kw-endofround}: Invoca una Bestia aleatoria.",
    "Murciélago",
    "Cobra",
    "Urna de metal",
    "Aziel",
    "Tiene +1 de Ataque por cada {kw-summon:3} aliado.",
    "Faxel Fetterbite",
    "{kw-counter}: Inflige 1 de daño al enemigo más cercano, luego cambia de fila.",
    "Barril explosivo",
    "Limo Divisor",
    "{kw-death}: Invoca 2 x {kw-summon:42}.",
    "Herrero de los Muerdegrilletes",
    "{kw-endofround}: Otorga +4 de Armadura a un aliado aleatorio.",
    "Guarda Esquelético",
    "Dienteamargo",
    "{kw-followup}: Otorga +1 de Ataque a una Bestia aliada aleatoria.",
    "Flit Muerdegrilletes",
    "{kw-counter}: Gana +1 de {kw-charge}.",
    "Fial Muerdegrilletes",
    "Si un personaje cualquiera muere, gana +1 de Ataque.",
    "El Muerdegrilletes perdido",
    "{kw-endofround}: Invoca un {kw-summon:48}.",
    "Matriarca",
    "Escarabajo Carroñero",
    "{kw-endofround}: Otorga +2 de Armadura a la {kw-summon:64}.",
    "Coloso Reanimado",
    "Doblemante",
    "Rey Muerdegrilletes",
    "{kw-endofround}: Invoca un {kw-summon:46}.",
    "El Orbe de Mando",
    "Los Trasgos tienen +1 de Ataque.",
    "Invisible.",
    "Limo colosal",
    "{kw-endofround}: Invoca 2 x {kw-summon:42} y cambia de fila.",
    "Limo solidificado",
    "Engendro de Valac",
    "{kw-endofround}: Invoca un {kw-summon:73}.",
    "Orbe Errante",
    "Ataca a uno de los enemigos más cercanos de cualquier fila.",
    "Espejismo de Acéfalo",
    "{kw-followup}: Se mueve.",
    "Masa de Orbes",
    "{kw-death}: Invoca 3 x {kw-summon:73}.",
    "Colmillo Plateado",
    "Espejismo Deteriorado",
    "{kw-death}: Invoca un {kw-summon:74}.",
    "Urna antigua",
    "Reina Orbe",
    "Tiene +1 de Ataque por cada aliado.",
    "Espejismo de Venina",
    "Ataque paralizador.",
    "Espejismo Perfecto",
    "Cuando este personaje mate a un enemigo, recupera 2 de Salud.",
    "Licántropo",
    "Espíritu de la Cueva",
    "Matorral Maldito",
    "{kw-death}: Inflige 2 de daño al enemigo más cercano en su misma fila.",
    "Matorral Convocado",
    "{kw-endofround}: Invoca 2 x {kw-summon:85}.",
    "Araña",
    "La Bruja",
    "{kw-endofround}: Invoca un Limo aleatorio. Después, se mueve.",
    "Ladrón",
    "Cuando este personaje mate a un enemigo, roba 1 de oro.",
    "Mímico",
    "{kw-death}: Gana 1 de oro.",
    "Progenitor del Orbe",
    "{kw-endofround}: Invoca 2 x {kw-summon:73}.",
    "Espejismo de Clypaes",
    "{kw-endofround}: Otorga {kw-shield} a otro aliado.",
    "Espejismo de Firis",
    "{kw-counter}: Inflige 1 de daño al enemigo más cercano.",
    "La Hechicera",
    "Cuando un aliado muere, otorga +2 de Ataque a otro aliado.",
    "Firis",
    "Venina",
    "Clypaes",
    "Espejismo Primordial",
    "{kw-followup}: Inflige 5 de daño a todos los aliados y gana +1 de Ataque.",
    "Pozo de espejismos",
    "{kw-endofround}: Invoca un {kw-summon:77}.",
    "El Antiguo",
    "Cuando una Bestia aliada muere, gana +1 de Ataque.",
    "Licántropo Alfa",
    "{kw-death}: Invoca 2 x {kw-summon:83}.",
    "Aquel Que No Ve",
    "Ataca al enemigo con la Salud más alta.",
    "Escórpido",
    "Escórpido Esquelético",
    "Ataca tres veces.",
    "Sirviente del Fuego",
    "{kw-followup}: Cambia de fila y gana +1 de Ataque.",
    "Príncipe de Ascuas",
    "Ataques malditos.",
    "Wisp de Llamas",
    "{kw-death}: Otorga +2 de {kw-charge} a todos los aliados.",
    "Caminante del Abismo",
    "{kw-endofround}: Invoca un {kw-summon:109}.",
    "Resplandor Amenazador",
    "{kw-endofround}: Invoca 2 x {kw-summon:112}, luego se mueve.",
    "Resplandor Inestable",
    "{kw-endofround}: Inflige 5 de daño a TODOS los personajes de esta fila.",
    "Trol anciano",
    "Trol",
    "Pesadilla",
    "{kw-endofround}: Paraliza a un enemigo aleatorio.",
    "Terror cristalino",
    "{kw-death}: Invoca un {kw-summon:117}.",
    "Terror",
    "Sirviente de la Sombra",
    "Tiene +1 de Ataque por cada enemigo presente.",
    "Príncipe de las Sombras",
    "Confundido.",
    "Wisp Infernal",
    "{kw-death}: Otorga +1 de Ataque al {kw-summon:121}.",
    "Guardián del Abismo",
    "{kw-endofround}: Invoca un {kw-summon:120}.",
    "Urna espiritual",
    "{kw-death}: Destruye al {kw-summon:123}.",
    "Espíritu de Ascuas",
    "{kw-endofround}: Gana +15 de Armadura, luego se mueve.",
    "Gigante de Carne",
    "Los ataques aplican 2 acumulaciones de {kw-affliction}.",
    "Gusano de Carne",
    "Sirviente de la Codicia",
    "Príncipe Dorado",
    "{kw-followup}: Roba 1 de oro.",
    "La Mano de Abaddon",
    "Cuando un monstruo aliado muere, gana +1 de Ataque.",
    "Sacerdote de Abbadon",
    "{kw-counter}: Otorga +2 de Armadura a {kw-summon:128}.",
    "Sacerdotisa de Abaddon",
    "{kw-counter}: Otorga +2 de {kw-charge} a {kw-summon:128}.",
    "Llama Primigenia",
    "{kw-endofround}: Inflige 2 de daño a todos los personajes de su fila, y luego se mueve.",
    "Roca",
    "Llama Sombría Menor",
    "{kw-death}: Invoca una {kw-summon:134}.",
    "Llama Sombría",
    "{kw-death}: Invoca una {kw-summon:135}.",
    "Llama Sombría Mayor",
    "El Usurpador de Mentes",
    "Los ataques aplican un efecto de estado aleatorio. Ataca aleatoriamente.",
    "Campeón del Vacío",
    "{kw-endofround}: Gana +1 de Ataque y se mueve.",
    "Abaddon",
    "Se transforma en cada turno.",
    "Pereza",
    "Lujuria",
    "Envidia",
    "{kw-endofround}: Invoca una {kw-summon:142}.",
    "Esfera Envenenada",
    "{kw-death}: Aplica {kw-poison} al enemigo con la Salud más baja.",
    "Ira",
    "Soberbia",
    "Reduce al enemigo con mayor salud a 1 de Salud.",
    "Avaricia",
    "{kw-endofround}: Invoca tres Esferas Doradas.",
    "Corrupción",
    "{kw-endofround}: Invoca dos Esferas Malditas.",
    "Esfera Dorada",
    "Gula",
    "{kw-endofround}: Invoca dos Devoradores aleatorios.",
    "Esfera Maldita",
    "{kw-death}: Maldice a un enemigo aleatorio.",
    "Devorador de Fuerza",
    "Los personajes no pueden ganar Armadura.",
    "Devorador de Esperanza",
    "Los personajes no pueden recuperar Salud.",
    "El Guardián",
    "Illifar",
    "Valac",
    "Orobas",
    "Morax",
    "{kw-endofround}: {kw-summon:153} gana +5 de Armadura.",
    "Aamon",
    "{kw-endofround}: {kw-summon:153} gana +3 de {kw-charge}.",
    "Haagenti",
    "Los ataques ignoran la Armadura.",
    "Bathin, el Grande",
    "{kw-death}: Paraliza a todos los enemigos no heroicos.",
    "{kw-endofround}: Todos los aliados ganan +1 de {kw-charge}.",
    "Sombra Afligida",
    "Nazzatoth",
    "{kw-endofround}: Invoca 2 x Sombra.",
    "Sombra de la Llama Negra",
    "{kw-endofround}: Invoca 2 x {kw-summon:171} en su misma fila.",
    "Sombra Eléctrica",
    "Sombra Inestable",
    "{kw-followup}: Inflige 2 de daño a todos los personajes en su misma fila.",
    "Sombra Embelesadora",
    "Sombra Aulladora",
    "Sombra Maldita",
    "Llama Oscura",
    "El Guardián del Portal",
    "Vacío",
    "{kw-death}: Aplica un efecto de estado aleatorio a un enemigo aleatorio.",
    "{kw-endofround}: Otorga +4 de {kw-charge} a un aliado aleatorio.",
    "Ojo de Nazzatoth",
    "Ojo de Illifar",
    "Inflige el doble de daño a los enemigos afligidos.",
    "Ojo de Abaddon",
    "El Reflejo del Guardián",
    "{kw-endofround} y {kw-death}: Inflige 5 de daño al enemigo más cercano en su misma fila, y le aplica 2 acumulaciones de {kw-affliction}.",
    "{kw-endofround}: Invoca un Reflejo con una habilidad aleatoria.",
    "{kw-endofround} y {kw-death}: Inflige 1 de daño a todos los enemigos.",
    "{kw-endofround} y {kw-death}: Inflige 10 de daño al enemigo más cercano en su misma fila.",
    "{kw-endofround} y {kw-death}: Inflige 4 de daño dos veces al enemigo más cercano en su misma fila.",
    "{kw-endofround} y {kw-death}: Inflige 3 de daño al enemigo con mayor Salud y lo paraliza.",
    "Sombra de la Mazmorra",
    "Gusano Áureo",
    "{kw-death}: Gana 13 de oro.",
    "Rey de la torre",
    "{kw-endofround}: ???",
    "Guardia de la torre",
    "Archimaje",
    "Cazador real",
    "{kw-followup}: Inflige 1 de daño a un enemigo aleatorio.",
    "Herrero",
    "Bomba",
    "{kw-endofround}: Invoca un {kw-summon:20}.",
    "Capitán de la torre",
    "{kw-followup}: Aplica {kw-weaken} a un enemigo aleatorio.",
    "Brujo real",
    "Espadachín real",
    "Heraldo del martillo",
    "{kw-endofround}: Invoca un {kw-summon:17}.",
    "Maestro de pociones",
    "Asesino",
    "Astrónomo",
    "{kw-endofround}: Otorga +2 de {kw-charge} a un aliado aleatorio.",
    "Oráculo",
    "Torre Caballero",
    "{kw-followup}: Gana {kw-shield}.",
    "Guardián de la cripta",
    "{kw-endofround}: invoca una {kw-summon:1} dos veces.",
    "Asesino",
    "Botecario",
    "{kw-otherunitdies}: Inflige 2 de daño al enemigo más cercano.",
    "Bufón de la corte",
    "Lotante",
    "Lobo del Pantano",
    "{kw-endofround}: Recupera 1 de Salud.",
    "Cobra gigante",
    "Dúas de anochecer",
    "Torturador",
    "Golem",
    "Lancero",
    "Nobleza de la torre",
    "{kw-endofround}: Recupera 2 de Salud.",
    "Lacayo",
    "Limo interminable",
    "Mago de sangre",
    "{kw-death}: Invoca un {kw-summon:11}.",
    "Amanecer beatle",
    "{kw-startofbattle}: Gana {kw-shield}.",
    "Magma Golem",
    "{kw-followup}: Gana +1 de Ataque.",
    "Tumba inquieta",
    "{kw-death}: Invoca un {kw-summon:244}.",
    "Golem nulo",
    "{kw-death}: Inflige 1 de daño a todos los enemigos.",
    "Cazador",
    "Bailarín de espada",
    "Tiene +1 de Ataque mientras esté al máximo de salud.",
    "Clérigo de la corte",
    "{kw-endofround}: Restaura 1 de salud al héroe aliado.",
    "Espíritu encarcelado",
    "Esbirro",
    "Armadura del anochecer",
    "{kw-counter}: Gana +1 de Armadura.",
    "Golem infernal",
    "Gigante de la torre",
    "Salvia de la corte",
    "Anochecer elemental",
    "{kw-endofround}: Da +1 {kw-charge} al héroe aliado.",
    "Duelista",
    "Armadura del Terror",
    "{kw-counter}: Gana +4 de Armadura.",
    "Dragón del Crepúsculo",
    "Demonio Nocturno",
    "Golem Perfecto",
    "Golem Arcano",
    "{kw-death}: Invoca un {kw-summon:174}.",
    "Dragón del Alba",
    "Gigante anciano",
    "Comehombres",
    "{kw-death}: Paraliza a un enemigo aleatorio.",
    "Espíritu Vengador",
    "Urna maldita",
    "{kw-death}: Aplica {kw-poison} al enemigo más cercano en esta fila.",
    "Trampa de estatua",
    "{kw-death}: Invoca un {kw-summon:20}.",
    "Carcaj de Lyra",
    "Los arqueros aliados ganan +1 de Ataque.",
    "Escritura tauriana",
    "Las Bestias y los Reptilianos aliados ganan +1 de Salud.",
    "Diario de Edric",
    "Los Luchadores aliados ganan +1 de Ataque y pierden -1 de Salud.",
    "Martillo de la Tierra Ancestral",
    "Los aliados Enanos y Gnomos ganan +2 de Salud.",
    "La capa del Inquisidor",
    "Los aliados ganan +3 Velocidad.",
    "El Martillo del Forjador",
    "Cada vez que un aliado gana Armadura, obtiene +1 de Armadura adicional.",
    "Libro de leyes",
    "Los aliados Humanos y Enanos ganan +1 de Salud.",
    "Martillo de Thoric",
    "Los aliados podrán acumular hasta 1 de Armadura al final de cada ronda.",
    "Piedra de Erilari",
    "Los aliados invocados ganan +1 de Ataque.",
    "Bastón de Cyril",
    "Los aliados invocados no pueden agotarse.",
    "Recolector de esencia",
    "Cuando un aliado no invocado muera, invoca dos Wisps Sangrientos.",
    "Antorcha eterna",
    "{kw-startofbattle}: Invoca una {kw-summon:4}.",
    "La espada del Inquisidor",
    "{kw-startofbattle}: Otorga +3 de {kw-charge} y {kw-shield} a tu héroe.",
    "Espíritu con Cadenas",
    "La primera vez que muera un aliado, invoca un {kw-summon:244}.",
    "Bendición de Clypaen",
    "La primea vez que un aliado reciba daño, le otorga un {kw-shield}.",
    "Destilador de esencia",
    "Tras la primera ronda, invoca a un Wisp Menor del Vacío enemigo.",
    "El secreto del mercader",
    "Los objetos cuesta 1 de oro menos.",
    "Veneno puro",
    "Los enemigos reciben +2 de daño de los venenos.",
    "Maleficio de Venina",
    "Monedas falsificadas",
    "Los personajes de los campamentos cuestan 2 de oro menos.",
    "Insignia real",
    "Tu primer cambio de héroes en un campamento/tienda será gratuito. {kw-startofbattle}: Tu héroe atacará.",
    "Sangre de trol",
    "Cuando tu héroe mate a un enemigo, recuperará 2 de Salud.",
    "Martillo titánico",
    "{kw-startofbattle}: Otorga 2 de Armadura a todos los aliados.",
    "Bastón del Amguan",
    "Cuando un aliado no ataque, le otorga +1 de {kw-charge}.",
    "Destilador sagrado",
    "Tras la primera ronda, invoca a un {kw-summon:5}.",
    "Libro de poder",
    "{kw-endofround}: Otorga +1 de {kw-charge} a un aliado Humano aleatorio.",
    "Esencia etérea",
    "Cuando un aliado pierde su escudo, les otorga +1 de Ataque.",
    "Violín de Jack",
    "Al visitar un campamento o una fogata, ganas 3 de oro.",
    "Libro de las Estrellas",
    "{kw-endofround}: Otorga +1 de {kw-charge} al Mago aliado con la menor Salud.",
    "Carcaj de disparo rápido",
    "{kw-startofbattle}: Los arqueros aliados atacan dos veces.",
    "Hechicería de los Fey",
    "Al invocar a un aliado, le otorga +2 de {kw-charge}.",
    "Bastón de la Llama",
    "{kw-startofbattle}: Inflige 8 de daño a un enemigo aleatorio.",
    "Bastón del Cielo",
    "{kw-startofbattle}: Da a todos los aliados +1 {kw-charge}.",
    "Bastón del Vacío",
    "{kw-endofround}: Inflige 1 de daño a un enemigo aleatorio.",
    "Esencia elemental",
    "Los Elementales aliados ganan +2 de Salud.",
    "Mazo fundido",
    "{kw-endofround}: Otorga a un Luchador aliado aleatorio +1 de Armadura.",
    "Libro de Bathin",
    "{kw-startofbattle}: Gana 1 de oro. Tu héroe perderá -2 de Salud.",
    "La Hoja Perdida",
    "Tu héroe tiene +1 de Ataque y +2 de Velocidad.",
    "Botas de Edric",
    "Tu héroe tiene un ataque adicional.",
    "Espada de esencia",
    "Tu héroe gana \\\"{kw-otherunitdies}: Gana +1 de {kw-charge}.\\\"",
    "Libro de prisa",
    "Los Magos aliados no pueden agotarse.",
    "Brebaje extraño",
    "{kw-startofbattle}: Otorga +1 de Ataque a un Reptiliano, un Gnomo y un Elemental aliados.",
    "Símbolo de la Alianza",
    "{kw-startofbattle}: Le otorga {kw-shield} a un Humano, un Enano y un Elfo aliados.",
    "Destilador de Venin",
    "Cuando un personaje envenenado muere, cura 1 de Salud a un aliado dañado que no sea un héroe.",
    "Maleficio de sangre",
    "Después de la primera ronda, invoca a una {kw-summon:15}.",
    "Campana de invocación",
    "{kw-startofbattle}: Invoca dos Martillos Espectrales.",
    "Vasija de almas",
    "Máx. de almas +6.",
    "Recuerdo de Jack",
    "Las Bestias aliadas ganan +1 de Salud y +2 de Velocidad.",
    "Manastone",
    "Los personajes Manacast tienen +1 de Maná.",
    "Hoja sagrada",
    "Tu héroe gana \\\"{kw-healthisrecovered}: Gana +1 de {kw-charge}.\\\"",
    "Manablade",
    "Cuando un personaje manaca, tu héroe gana +1 Ataque.",
    "La corona del alba",
    "El límite de tu grupo aumenta en 1.",
    "Capa de discípulo",
    "Poción de lealtad",
    "Transforma a un {kw-summon:33} en un {kw-summon:34}. El personaje pierde todo su equipo. Consumible.",
    "Espada de Aamon",
    "{kw-counter}: Gana +1 de Ataque.",
    "Espada infernal",
    "Espada de campeón",
    "Espada del fénix",
    "Invitación de la Muerte",
    "Al equiparlo, mueres.",
    "Anillo de la plaga",
    "{kw-startofbattle}: Envenenado. Gana 3 de oro.",
    "Anillo de la edad",
    "{kw-startofbattle}: Ganas 3 de oro.",
    "Anillo de mortalidad",
    "{kw-startofbattle}: Recibe 1 de daño y gana 3 de oro.",
    "Anillo de debilidad",
    "Poción de curación",
    "Restaura 2 de Salud. Consumible.",
    "Poción temporal",
    "Transforma a tu héroe. Al hacerlo, perderá todo su equipo.",
    "Poción de curación menor",
    "Restaura 1 de Salud. Consumible.",
    "Poción de curación mayor",
    "Restaura 8 de Salud. Consumible.",
    "Capa de travesía",
    "Capa de vagabundo",
    "Arco corto",
    "El Arco de las Sombras",
    "Capa de carroñero",
    "Cuando este personaje mata a un enemigo, invoca un {kw-summon:7}.",
    "Arbalesta de Iliphar",
    "Arco infernal",
    "Arbalesta de Andromalius",
    "Poción de misterio menor",
    "Se transforma en un objeto aleatorio. Consumible.",
    "Poción de transformación",
    "Transforma a un Arquero en un personaje aleatorio de nivel 3. El personaje pierde todo su equipo. Consumible.",
    "Vial de esencia",
    "{kw-death}: Invoca un {kw-summon:10}.",
    "Colgante espejado",
    "El personaje equipado no puede ser paralizado.",
    "Lente del alma",
    "Cuando un aliado muere, inflige 1 de daño al enemigo más cercano.",
    "Colgante de Clypaes",
    "Bastón del adepto",
    "Piedra del sol",
    "{kw-endofround}: Gana +1 de {kw-charge}.",
    "Amuleto condenado",
    "Signo abrasador",
    "Cetro sagrado",
    "{kw-followup}: Cura 1 de Salud a un aliado dañado que no sea un héroe.",
    "Varita infernal",
    "Garra de Andromalius",
    "Poción de Midas",
    "Transforma a un Mago en una Estatua de Oro, que puede venderse por 10 de oro en los campamentos. El personaje pierde todo su equipo. Consumible.",
    "Poción de versatilidad mayor",
    "Transforma al mago en un multiclase, permitiéndole usar equipo de cualquier otra clase. Se consume al usarlo.",
    "Poción de misterio mayor",
    "Escudo de madera",
    "Escudo de veneno",
    "{kw-startofbattle}: Envenenado.",
    "Escudo del hostigador",
    "Escudo reforzado",
    "Yelmo de inmortal",
    "{kw-otherunitdies}: Gana +1 de Armadura.",
    "Muro del titán",
    "Escudo de cometa",
    "Yelmo vampírico",
    "{kw-otherunitdies}: Recupera 1 de Salud.",
    "Escama de dragón",
    "Escudo infernal",
    "{kw-startofbattle}: Gana +2 de Armadura.",
    "Escama de Andromalius",
    "Poción de versatilidad",
    "Transforma al guerrero en un multiclase, permitiéndole usar equipo de cualquier otra clase. Se consume al usarlo.",
    "Poción de replicación",
    "Transforma a un Guerrero en una copia básica de un miembro aleatorio del grupo. El personaje pierde todo su equipo. Consumible.",
    "Huevo de cría",
    "Tras la primera ronda, invoca a una {kw-summon:27} de reptiliano.",
    "Colmillo del relámpago",
    "Colmillo venenoso",
    "Los ataques envenenan al enemigo golpeado.",
    "Huevo Tóxico",
    "Tras la primera ronda, invoca a un Envenescamoso reptiliano.",
    "Moneda de la suerte",
    "No está claro para qué sirve.",
    "Casco de la muerte",
    "Cuando un personaje envenenado muere, recupera 1 de Salud.",
    "Casco de veneno",
    "{kw-followup}: Inflige 1 de daño a todos los enemigos envenenados.",
    "Casco del inmortal",
    "{kw-followup}: Recupera 1 de Salud.",
    "Alma agrietada",
    "{kw-startofbattle}: Gana 1 alma.\\Máx. de almas +1.",
    "Talismán de calavera",
    "Cuando un personaje use su Poder de almas, gana +1 de Armadura.",
    "Varita sanguina",
    "Tras la primera ronda, invoca a un {kw-summon:10}.",
    "Varita de escamas verdes",
    "{kw-endofround}: Otorga +1 de Armadura a una invocación aliada aleatoria.",
    "Varita necrótica",
    "Piedra estelar",
    "Cinto de Midas",
    "Hacha arrojadiza",
    "{kw-counter}: Inflige 1 de daño a un enemigo aleatorio.",
    "Hacha de berserker",
    "Gana +1 de Ataque si está por debajo de su Salud máxima.",
    "Hacha sagrada",
    "Cuando este personaje gana Salud, también gana +1 de {kw-charge}.",
    "Cinturón del inmortal",
    "{kw-counter}: Recupera 1 de Salud.",
    "Gema ancestral",
    "Cuchilla de Taur",
    "Coraza de noble",
    "{kw-death}: Gana 2 de oro.",
    "Cota de malla",
    "Coraza de mártir",
    "{kw-death}: Otorga +1 de Ataque a todos los aliados.",
    "Coraza de campeón",
    "Anillo de sangre vital",
    "Cinta de la paloma",
    "Una llave vieja",
    "Anillo antiveneno",
    "El personaje equipado no puede ser envenenado.",
    "Llave dorada",
    "La llave del contrabandista",
    "Anillo de titán",
    "{kw-startofbattle}: Gana +4 de Armadura.",
    "Guantes de curtidor",
    "Cinta del halcón",
    "Anillo de furia del Vacío",
    "Cuando este personaje mate a un enemigo, inflige 1 de daño a un enemigo aleatorio.",
    "Guantes reforzados",
    "Anillo necrótico",
    "Ladrón de almas",
    "Cuando este personaje mate a un enemigo, se cura 1 de Salud.",
    "Anillo de Thoric",
    "Gracia de la Muerte",
    "Si el personaje que lo lleva muere, destruye este objeto en su lugar.",
    "Cinto de pociones",
    "Calavera del Vacío",
    "Guanteletes",
    "Anillo de diamante",
    "Llave del portal",
    "Gema de zafiro",
    "Cenizas",
    "Anillo de obsidiana",
    "Un antiguo anillo de transformación.",
    "Gema de obsidiana",
    "Anillo de esmeralda",
    "Anillo de amatista",
    "Anillo de rubí",
    "Anillo de topacio",
    "Regalo de la Muerte",
    "+25 % de puntuación",
    "Sombra de la Muerte",
    "{kw-counter}: Gana {kw-shield}.",
    "Poción de experiencia",
    "Gana +1 de EXP. Consumible.",
    "Gana +1 de EXP. Los personajes que hayan muerto en esta batalla no ganarán EXP. Consumible.",
    "Poción de maestría",
    "Gana +3 de EXP. Consumible.",
    "Poción cósmica",
    "Transforma a un personaje en un {kw-summon:29}. El personaje pierde todo su equipo. Consumible.",
    "Bolsa de oro",
    "Poción de experiencia mayor",
    "Gana +2 de EXP. Los personajes que hayan muerto en esta batalla no ganarán EXP. Consumible.",
    "Metal",
    "Sol",
    "Martillo",
    "Corazón",
    "Escamoso",
    "La Rama",
    "Calavera",
    "Garra"
];
