var L = [
    "",
    "Mensch",
    "Zwerg",
    "Gnom",
    "Elf",
    "Echsenmensch",
    "Elementar",
    "Tier",
    "Goblin",
    "Untoter",
    "Monster",
    "Pflanze",
    "Konstrukt",
    "Alter Gott",
    "Dämon",
    "???",
    "Held",
    "Kämpfer",
    "Bogenschütze",
    "Zauberer",
    "Gefolgsmann",
    "Multiklasse",
    "-",
    "Nur Vorne",
    "Nur Hinten",
    "Angriff",
    "Leben",
    "Eile",
    "Tod",
    "TOD: Bewirkt etwas, wenn der Charakter stirbt.",
    "Rundenende",
    "RUNDENENDE: Bewirkt etwas, sobald alle Charaktere ihre Angriffe beendet haben. Ignoriert Erschöpfung.",
    "Folgeaktion",
    "FOLGEAKTION: Bewirkt etwas, sobald der Charakter seinen Angriff beendet hat.",
    "Gnadenlos",
    "GNADENLOS: Bewirkt etwas, sobald ein Gegner stirbt.",
    "Hoffnung",
    "HOFFNUNG: Bewirkt etwas, sobald das Leben eines Verbündeten erhöht wird.",
    "Intrige",
    "INTRIGE: Bewirkt etwas, sobald der Charakter auf seinen Angriff verzichtet.",
    "Kampfbeginn",
    "KAMPFBEGINN: Bewirkt etwas, bevor der Kampf beginnt.",
    "Seelenbeschwörung",
    "Soulcast X: Gib X Seelen aus, um  eine Fähigkeit zwischen den Runden zu aktivieren. Kann nur einmal pro Runde verwendet werden. Rechtsktlick zum Wirken.",
    "Gift",
    "POISON: Poisoned characters take 1 damage after their normal attack. Lasts until the end of this battle. Does not stack.",
    "Fluch",
    "FLUCH: Der nächste Schaden, den ein Charakter erleidet, wird verdoppelt.",
    "Schild",
    "SCHILD: Der nächste Angriff auf diesen Charakter verursacht keinen Schaden.",
    "Parade",
    "PARADE: Bewirkt etwas, wenn der Charakter Leben verliert (und dies überlebt).",
    "Gebrechen",
    "GEBRECHEN: Gebrechliche Charaktere können kein(e) Leben, Rüstung oder Macht erhalten Zum Rundenende hin wird jeweils ein Gebrechen entfernt.",
    "Macht",
    "MACHT: Der nächste Angriff verursacht erhöhten Schaden.",
    "RÜSTUNG",
    "RÜSTUNG: Die Schadenshöhe, die ein Charakter erleiden kann, bevor er Leben verliert. Rüstung verschwindet mit jedem Rundenende.",
    "Getötet",
    "Blutwurf",
    "Blutung X: Nimm Schaden, um eine Fähigkeit zwischen den Runden auszulösen. Kann einmal pro Runde verwendet werden. Rechtsklick zum Wirken.",
    "Wiederbeleben",
    "Wiederbelebung: Bringt einen toten Verbündeten mit 1 Lebenspunkt zurück ins Leben.",
    "beschwört",
    "Der Verirrte Abenteurer",
    "Er ist ein echter Pechvogel",
    "Thoric mit dem Hammer",
    "Fürst der Alten Erde",
    "{kw-endofround}: Erhält +1 Rüstung.",
    "Meisterschmied",
    "{kw-endofround}: Gewährt dem vordersten Verbündeten in dieser Reihe +1 Rüstung.",
    "Eloa",
    "Die Letzte Astronomin",
    "{kw-followup}: Gewährt einem Verbündeten in dieser Reihe +1 {kw-charge}. Unermüdlich.",
    "Arkane Forscherin",
    "{kw-endofround}: Gewährt einem Zauberer in dieser Reihe +2 {kw-charge}.",
    "Dominique Boutroux",
    "Der Reisekoch",
    "{kw-followup}: Heilt einem verletzen Verbündeten in dieser Reihe 1 Leben. Unermüdlich.",
    "Die reisende Händlerin",
    "{kw-startofbattle}: Gewinnt 1 Gold. Unermüdlich.",
    "Die Weise Gryx",
    "Sie-Die-Alleine-Schwimmt",
    "Greift an, wann immer ein Verbündeter stirbt. Unermüdlich.",
    "Brutmatriarchin",
    "Giftig. Unermüdlich.",
    "Mariana",
    "Streuner des Wissens",
    "{kw-startofbattle}: Beschwört {kw-summon:159}. Unermüdlich.",
    "Rache-Suchende",
    "Beginnt mit Jacks Gedächtnis. Unermüdlich.",
    "Taz'gyn",
    "Vom Alten Mond",
    "Startet mit einem Essenzdestillator. Unermüdlich.",
    "Erleuchteter Beschwörer",
    "Beschwört einen {kw-summon:4}, wann immer dieser Charakter einen Gegner tötet. Unermüdlich.",
    "Xandos III.",
    "Der Junge Prinz",
    "Startet mit der Krone der Dämmerung.",
    "Der Goldene Kaiser",
    "Erhält für jeweils 5 Gold +1 Angriff. Unermüdlich.",
    "Elsbeth",
    "Weit weg",
    "{kw-channelsoul} 1: Füge dem nächsten Feind 2 Schaden zu. Max. Seelen +1. Unermüdlich.",
    "Kunsthandwerker",
    "Beginnt mit zwei zusätzlichen zufälligen Relikten. Unermüdlich.",
    "Animara",
    "Wenn ein Charakter Blutwürfe, wirkt, erhält er +1 {kw-charge}. Unermüdlich.",
    "Taz'gyn, des Ordens",
    "{kw-otherunitdies}: Erhält +1 {kw-charge}. Unermüdlich.",
    "Xandos, der Große",
    "Elsbeth, Sumpfhexe",
    "{kw-startofbattle}: Vergifte zwei zufällige Gegner. Giftig. Unermüdlich.",
    "Artefakttruhe",
    "Wähle ein Artefakt",
    "Schwert des Recken",
    "Aamons Klinge",
    "{kw-counter}: Erhalte +1 Angriff.",
    "Aschehaufen",
    "Phönixklinge",
    "Umhang des Gefolgsmanns",
    "Taubenring",
    "Titanenring",
    "{kw-startofbattle}: Erhalte +4 Rüstung.",
    "Thorics Ring",
    "Falkenring",
    "Ring der Verwesung",
    "Lebensblutring",
    "Ring des Gegenvenins",
    "Sein Träger kann nicht vergiftet werden.",
    "Der Leerzornring",
    "Wann immer dieser Charakter einen Gegner tötet, erleidet ein zufälliger Gegner 1 Schaden.",
    "Heilgürtel",
    "{kw-endofround}: Heile 1 Leben.",
    "Der Seelendieb",
    "Heile 1 Leben, wann immer dieser Charakter einen Gegner tötet.",
    "Schädel der Leere",
    "Anmut des Todes",
    "Wenn dieser Charakter sterben würde, zerstöre dies stattdessen.",
    "Einladung des Todes",
    "Wenn ausgerüstet, sterben.",
    "Die Gabe des Todes",
    "+25% Punkte",
    "Schatten des Todes",
    "{kw-counter}: Erhalte {kw-shield}.",
    "Gerberhandschuhe",
    "Verstärkte Handschuhe",
    "{kw-startofbattle}: Erhalte +2 Rüstung.",
    "Panzerhandschuhe",
    "Helm der Unsterblichen",
    "{kw-otherunitdies}: Erhalte +1 Rüstung.",
    "Vampirhelm",
    "{kw-otherunitdies}: Heile 1 Leben.",
    "Hölzerner Kleinschild",
    "Verstärkter Kleinschild",
    "Kundschafterschild",
    "Langschild",
    "Der Titanenwall",
    "Drachenschuppe",
    "Schuppe des Andromalius",
    "Veninschild",
    "{kw-startofbattle}: Sein Träger wird vergiftet.",
    "Sonnenstein",
    "{kw-endofround}: Erhalte +1 {kw-charge}.",
    "Spiegelanhänger",
    "Sein Träger kann nicht versteinert werden.",
    "Segen der Clypaes",
    "{kw-startofbattle}: Erhalte {kw-shield}.",
    "Essenzphiole",
    "{kw-death}: Beschwöre eine {kw-summon:170}.",
    "Verfluchtes Amulett",
    "{kw-followup}: Erleide 1 Schaden.",
    "Seelenlinse",
    "Füge dem nächstgelegenen Gegner 1 Schaden zu, wann immer ein Verbündeter stirbt.",
    "Stab des Adepten",
    "Das Sengende Zeichen",
    "Heiliges Szepter",
    "{kw-followup}: Heile einem verletzten Verbündeten 1 Leben (Ausnahme: Held).",
    "Klaue des Andromalius",
    "Kurzbogen",
    "Der Schattenbogen",
    "Umhang des Übergangs",
    "Umhang des Wandersmanns",
    "Umhang des Plünderers",
    "Beschwöre einen {kw-summon:161}n, wann immer dieser Charakter einen Gegner tötet.",
    "Illiphars Armbrust",
    "Armbrust des Andromalius",
    "Brustpanzer des Märtyrers",
    "{kw-death}: Gewähre allen Verbündeten +1 Angriff.",
    "Fürstlicher Brustpanzer",
    "{kw-death}: Erhalte 2 Gold.",
    "Kettenhemd",
    "Brustpanzer des Recken",
    "Gürtel des Midas",
    "{kw-startofbattle}: Erhalte 1 Gold.",
    "Gürtel der Unsterblichen",
    "{kw-counter}: Heile 1 Leben.",
    "Wurfbeil",
    "{kw-counter}: Füge einem zufälligen Gegner 1 Schaden zu.",
    "Heilige Axt",
    "Erhält dieser Charakter Leben, so erhält er ebenfalls +1 {kw-charge}.",
    "Berserkeraxt",
    "Erhalte +1 Angriff, sobald dein Leben unter sein Maximum sinkt.",
    "Echsenei",
    "Beschwöre nach der ersten Runde eine {kw-summon:179}.",
    "Giftei",
    "Beschwöre nach der ersten Runde eine {kw-summon:180}.",
    "Reisszahn des Blitzes",
    "Reisszahn des Giftes",
    "Angegriffene Gegner werden vergiftet.",
    "Rotblutstab",
    "Beschwöre nach der ersten Runde eine {kw-summon:170}.",
    "Stab der Verwesung",
    "{kw-endofround}: Füge dem Gegner mit dem wenigsten Leben 1 Schaden zu.",
    "Grünschuppenstab",
    "{kw-endofround}: Gewähre einem zufälligen beschworenen Verbündeten +1 Rüstung.",
    "Giftmorchel",
    "{kw-followup}: Füge allen vergifteten Gegnern 1 Schaden zu.",
    "Glücksmünze",
    "Lebensmorchel",
    "{kw-followup}: Heile 1 Leben.",
    "Todesmorchel",
    "Heile 1 Leben, wann immer ein vergifteter Charakter stirbt.",
    "Sternenstein",
    "Schädel-Charme",
    "Nach dem verwenden von Seelenzauber: Erhalte +1 Rüstung.",
    "Gebrochene Seele",
    "{kw-startofbattle}: Erhalte 1 Seele. Max. Seelen +1.",
    "Taurisches Hackbeil",
    "Ahnen-Edelstein",
    "Wenn ein Charakter Blutwürfe, wirkt, erhält er +1 {kw-charge}.",
    "Ein alter Schlüssel",
    "Der Schlüssel des Schmugglers",
    "Goldener Schlüssel",
    "Pfortenschlüssel",
    "Obsidianring",
    "Ein uralter Ring der Umformung",
    "Smaragdring",
    "Topasring",
    "Diamantring",
    "Rubinring",
    "Amethystring",
    "Obsidianbrosche",
    "Saphirbrosche",
    "Ring der Schwäche",
    "{kw-startofbattle}: Erhalte 3 Gold. (Die Weise Gryx, Mariana)",
    "Ring der Sterblichkeit",
    "{kw-startofbattle}: Erleide 1 Schaden und erhalte 3 Gold. (Xandos III., Taz'gyn, Elsbeth)",
    "Ring der Alters",
    "{kw-startofbattle}: Erhalte 3 Gold. (Eloa, Dominique Boutroux)",
    "Ring der Seuchen",
    "{kw-startofbattle}: Werde vergiftet und erhalte 3 Gold. (Thoric mit dem Hammer)",
    "Trank der Wandlung",
    "Verwandelt einen Bogenschützen in einen zufälligen Charakter der Stufe 3. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Spiegeltrank",
    "Verwandelt einen Kämpfer in das einfache Abbild eines zufälligen Verbündeten. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Trank des Midas",
    "Verwandelt einen Zauberer in eine {kw-summon:155}, die an einem Lagerfeuer für 10 Gold verkauft werden kann. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Temporaler Trank",
    "Verwandle deinen Helden. Sie verlieren ihre gesamte Ausrüstung.",
    "Starker Rätseltrank",
    "Verwandelt sich in einen zufälligen Gegenstand. Verschwindet nach Gebrauch.",
    "Schwacher Rätseltrank",
    "Trank der Vielseitigkeit",
    "Verwandelt einen Kämpfer in eine Multiklasse, so dass er Gegenstände aller Klassen benutzen kann. Verschwindet nach Gebrauch.",
    "Starker Trank der Vielseitigkeit",
    "Verwandelt einen Zauberer in eine Multiklasse, so dass er Gegenstände aller Klassen benutzen kann. Verschwindet nach Gebrauch.",
    "Sack voller Gold",
    "Erhalte 3 Gold.",
    "Trank der Erfahrung",
    "Erhalte +1 XP. Verschwindet nach Gebrauch.",
    "Erhalte +1 XP. Charaktere, die in diesem Kampf gestorben sind, können keine XP bekommen. Verschwindet nach Gebrauch.",
    "Starker Trank der Erfahrung",
    "Erhalte +2 XP. Charaktere, die in diesem Kampf gestorben sind, können keine XP bekommen. Verschwindet nach Gebrauch.",
    "Trank der Meisterschaft",
    "Erhalte +3 XP. Verschwindet nach Gebrauch.",
    "Schwacher Heiltrank",
    "Heilt 1 Leben. Verschwindet nach Gebrauch.",
    "Heiltrank",
    "Heilt 2 Leben. Verschwindet nach Gebrauch.",
    "Starker Heiltrank",
    "Heilt 8 Leben. Verschwindet nach Gebrauch.",
    "Kosmischer Trank",
    "Verwandelt einen Charakter in einen Kosmischen Schleim. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Treuetrank",
    "Verwandelt einen Gefolgsmann in einen Treuen Gefolgsmann. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Lyras Köcher",
    "Verbündete Bogenschützen erhalten +1 Angriff.",
    "Die Heilige Schrift der Taurianer",
    "Verbündete Tiere und Echsenmenschen erhalten +1 Leben.",
    "Edrics Tagebuch",
    "Verbündete Kämpfer erhalten +1 Angriff, verlieren jedoch 1 Leben.",
    "Das Buch der Sterne",
    "{kw-endofround}: Der Zauberer mit der dem wenigsten Leben erhält +1 {kw-charge}.",
    "Hammer der Alten Erde",
    "Verbündete Zwerge und Menschen erhalten +2 Leben.",
    "Der Umhang des Gebieters",
    "Verbündete Elfen und Elementare erhalten +3 Eile.",
    "Der Schmiedehammer",
    "Wann immer ein Verbündeter Rüstung erhält, erhält er zusätzlich +1 Rüstung.",
    "Die Klinge des Gebieters",
    "{kw-startofbattle}: Gewähre deinem Helden +3 {kw-charge} und {kw-shield}.",
    "Das Buch des Gesetzes",
    "Verbündete Menschen und Zwerge erhalten +1 Leben.",
    "Thorics Hammer",
    "Verbündete behalten am Ende jeder Runde 1 Rüstung.",
    "Clypaes' Schutzbann",
    "Erleidet ein Verbündeter Schaden, so erhält er einmalig {kw-shield}.",
    "Das Geheimnis des Kaufmanns",
    "Gegenstände kosten 1 Gold weniger.",
    "Erilaris Gemme",
    "Beschworene Verbündete erhalten +1 Angriff.",
    "Cyrils Stab",
    "Beschworene Verbündete sind unermüdlich.",
    "Immerwährende Fackel",
    "{kw-startofbattle}: Beschwöre eine {kw-summon:163}.",
    "Seelenfessel",
    "Beim ersten Tod eines Verbündeten wird ein {kw-summon:164} beschworen.",
    "Essenzdestillator",
    "Beschwöre nach der ersten Runde eine schwache gegnerische Leerseele.",
    "Essenzsammler",
    "Beschwöre zwei {kw-summon:170}n, wann immer ein nicht-beschworener Verbündeter stirbt.",
    "Reines Venin",
    "Gegner erleiden durch Gift +1 Schaden.",
    "Veninas Fluch",
    "{kw-startofbattle}: Vergifte zwei zufällige Gegner.",
    "Falschmünzen",
    "Charaktere kosten an Lagerfeuern 2 Gold weniger.",
    "Königliche Insignien",
    "Eine kostenlose Erneuerung an jedem Lagerfeuer und Laden. {kw-startofbattle}: Dein Held greift an.",
    "Trollblut",
    "Wann immer dein Held einen Gegner tötet, heilt er 2 Leben.",
    "Das Buch der Macht",
    "{kw-endofround}: Gewähre einem zufälligen verbündeten Menschen +1 {kw-charge}.",
    "Stab der Amguanerin",
    "Verzichtet ein Verbündeter auf seinen Angriff, so erhält er +1 {kw-charge}.",
    "Ätherische Essenz",
    "Wann immer ein Verbündeter Rüstung verliert, erhält der +1 Angriff.",
    "Titanenhammer",
    "{kw-startofbattle}: Gewähre allen Verbündeten 2 Rüstung.",
    "Heiliger Destillator",
    "Beschwöre nach der ersten Runde eine {kw-summon:166}.",
    "Jacks Fiedel",
    "Wann immer du ein Lager- oder Freudenfeuer besuchst, erhältst du 3 Gold.",
    "Der Blitzschnelle Köcher",
    "{kw-startofbattle}: Verbündete Bogenschützen greifen zweimal an.",
    "Feenzauber",
    "Wenn ein Verbündeter beschworen wird, erhält er +2 {kw-charge}.",
    "Stab der Flammen",
    "{kw-startofbattle}: Füge einem zufälligen Gegner 5 Schaden zu.",
    "Stab des Himmels",
    "{kw-startofbattle}: Teile 4 Schaden zufällig unter deinen Gegnern auf.",
    "Stab der Leere",
    "{kw-endofround}: Füge einem zufälligen Gegner 1 Schaden zu.",
    "Elementaressenz",
    "Verbündete Elementare erhalten +2 Leben.",
    "Rotglühender Hammer",
    "{kw-endofround}: Gewähre einem zufälligen verbündeten Kämpfer +1 Rüstung.",
    "Bathins Buch",
    "{kw-startofbattle}: Erhalte 1 Gold. Dein Held hat 2 Leben weniger.",
    "Die Verschollene Klinge",
    "Dein Held erhält +1 Angriff und +2 Eile.",
    "Edrics Stiefel",
    "Dein Held greift ein weiteres Mal an.",
    "Essenzklinge",
    "Dein Held hat \\\"{kw-otherunitdies}: Erhalte +1 {kw-charge}.\\\"",
    "Das Buch der Hast",
    "Verbündete Zauberer sind unermüdlich.",
    "Seltsames Gebräu",
    "{kw-startofbattle}: Gewähre jeweils einem verbündeten Echenmensch, Gnom und Elementar +1 Angriff.",
    "Zeichen des Bundes",
    "{kw-startofbattle}: Gewähre jeweils einem verbündeten Mensch, Zwerg und Elf {kw-shield}.",
    "Venindestillator",
    "Wann immer ein vergifteter Charakter stirbt, heilt ein verletzter Verbündeter 1 Leben (Ausnahme: Held).",
    "Krankes Blut",
    "Beschwöre nach der ersten Runde eine gegnerische Blutseele.",
    "Beschwörungsglocke",
    "{kw-startofbattle}: Beschwöre zwei Spektralhämmer.",
    "Seelengefäß",
    "Maximale Seelen +6.",
    "Jacks Gedächtnis",
    "Verbündete Bestien erhalten +1 Lebenspunkte und +2 Geschwindigkeit.",
    "Die Krone der Dämmerung",
    "Deine maximale Gruppengröße wird um 1 erhöht.",
    "Aguatilis",
    "Erhält +2/3/4 {kw-charge}, wann immer ein Verbündeter stirbt. Unermüdlich.",
    "Panzerritter",
    "Vefügt über einen Angriffsbonus, der dem eigenen Rüstungswert entspricht.",
    "Rüstungsschmied",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +2/3/4 Rüstung.",
    "Berserker",
    "{kw-counter}: Erhält +1/2/3 {kw-charge}.",
    "Braumeister",
    "{kw-counter}: Heilt einem verletzten Verbündeten 1 Leben (Ausnahme: Held).",
    "Schlachter",
    "Wann immer dieser Charakter einen Gegner tötet, heilt er /zweimal/dreimal einem Verbündeten 1 Leben (Ausnahme: Held).",
    "Medium",
    "{kw-followup}: Löst alle verbündeten Gnadenlos-Effekte aus.",
    "Priester der Dunkelheit",
    "Erhält {kw-shield}, wann immer dieser Charakter einen Gegner tötet.",
    "Priester des Hammers",
    "{kw-endofround}: Beschwört einen {kw-summon:183/184/185}.",
    "Priester der Erkenntnis",
    "{kw-followup}: Heilt einem verletzen Verbündeten 1/1/2 Leben (Ausnahme: Held).",
    "Priester der Rose",
    "{kw-healthisrecovered}: Fügt dem nächstgelegenen Gegner in dieser Reihe 1/1/2 Schaden zu.",
    "Kultist",
    "{kw-otherunitdies}: Heilt 1/2/3 Leben.",
    "Deadeye",
    "+1 Schaden für jeden anderen verbündeten Untoten.",
    "Göttlicher Beschützer",
    "Gewährt Verbündeten {kw-shield}, sobald sie beschworen werden.",
    "Druide",
    "Beschwört nach der ersten Runde zwei {kw-summon:160/161/162}.",
    "Ember Blut",
    "{kw-channelblood} 2: Erhalte +1 Angriff.",
    "Zauberwirker",
    "{kw-endofround}: Gewährt allen Zauberern +1 {kw-charge}.",
    "Gefallener Adept",
    "{kw-channelsoul} X: Füge dem nächsten Feind in dieser Spur /2/4X Schaden zu. Max. Seelen +3.",
    "Adept der Verdammnis",
    "Giftig. Beschworene Verbündete erhalten +1/2/3 Angriff.",
    "Adept der Flammen",
    "Verletzt auch Gegner in der gleichen Spalte.",
    "Seher",
    "{kw-otherunitdies}: Fügt einem zufälligen Gegner 1/2/4 Schaden zu.",
    "Jäger",
    "{kw-followup}: Fügt dem Gegner mit dem wenigsten Leben 1/2/3 Schaden zu.",
    "Hypogaianer",
    "{kw-scheme}: Heilt sich 1 Leben für verbündeten Echsenmenschen.",
    "Eisenblut",
    "{kw-channelblood} 1: Erhalte +1 Rüstung für jeden beschädigten Verbündeten.",
    "Speerkämpfer",
    "Greit an, sobald er Rüstung erhält.",
    "Adeptin der Blitze",
    "Wann immer dieser Charakter {kw-charge} erhält, fügt er einem zufälligen Gegner 1/2/3 Schaden zu.",
    "Sonnenmagier",
    "Erhält doppelte {kw-charge}.",
    "Nekromant",
    "{kw-channelsoul} 2: Beschwöre ein {kw-summon:5}. Max. Seelen +2.",
    "Schattenschütze",
    "{kw-otherunitdies}: Erhält +1/2/3 {kw-charge}. Unermüdlich.",
    "Praexator",
    "Gewährt allen verbündeten Echsenmenschen +1 {kw-charge}, wann immer dieser Charakter einen Gegner tötet. Unermüdlich.",
    "Praliator",
    "Wann immer dieser Charakter einen Gegner tötet, greift er erneut an.",
    "Schurke",
    "Königswache",
    "Wann immer dieser Charakter Leben erhält, bekommt dein Held +1/1/2 {kw-charge}.",
    "Runenschmied",
    "Erhält +1 {kw-charge}, wann immer ein anderer verbündeter Zwerg Schaden erleidet. {kw-endofround}: Erhält +1 Rüstung für jeden verbündeten Zwerg.",
    "Bluthexer",
    "{kw-endofround}: Beschwört einen gegnerischen {kw-summon:182} in dieser Reihe. Unermüdlich.",
    "Scharfschütze",
    "Wann immer ein Gegner {kw-poison} wird, wird ihm 1/2/3 zusätzlicher Schaden zugefügt.",
    "Seelentrinker",
    "{kw-endofround}: Wenn du 2 oder mehr Seelen hast, regeneriere 1/2/3 Leben. Max. Seelen +2.",
    "Knappe",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +1/2/3 {kw-charge}.",
    "Beschwörer des Stahls",
    "Beschwört nach der ersten Runde eine {kw-summon:168/167/169}.",
    "Sonnenhorn",
    "{kw-channelblood} 1: Stelle/t zweimal/e dreimal 1 Lebenspunkt bei einer benachbarten beschädigten Bestie wieder her.",
    "Klingentänzer",
    "Erhält bei vollem Leben +1/2/3 Angriff. Unermüdlich.",
    "Gerber",
    "Erhalte 1 Gold, wann immer dieser Charakter einen Gegner tötet.",
    "Tarus-Wache",
    "{kw-channelsoul} 1: Gib allen anderen verbündeten Untoten +1/2/3 Rüstung. Max. Seelen +1.",
    "Tüftlerin",
    "{kw-endofround}: Wann immer dieser Charakter {kw-charge} erhält, beschwört er eine {kw-summon:175/176/177}.",
    "Venintrinker",
    "Heilt 1/2/3 Leben, wann immer ein vergifteter Charakter stirbt. Giftig.",
    "Venomant",
    "{kw-followup}: Fügt allen vergifteten Gegnern 1/2/3 Schaden zu. Giftig.",
    "Kriegsbär",
    "{kw-endofround}: Wenn dieser Charakter 1 Gesundheit hat, stelle 1 Gesundheit/2 oder weniger Lebenspunkte hat, stelle 2 Lebenspunkte/3 oder weniger Lebenspunkte hat, stelle 3 Lebenspunkte wieder her.",
    "Der Zornleiter",
    "{kw-counter}: Greift an. Unermüdlich.",
    "Amguanerin",
    "{kw-scheme}: Gewährt allen verbündeten Echsenmenschen +1/2 {kw-charge}.",
    "Arkanschütze",
    "{kw-endofround}: Gewährt allen verbündeten Zauberern in dieser Spalte +2/3 {kw-charge}.",
    "Meuchelmörder",
    "Gegner erleiden +1/2 Schaden durch Gifte. Giftig.",
    "Gardist der Aviakoraner",
    "{kw-counter}: Beschwört eine/n {kw-summon:160/161}.",
    "Schlachtenpriester",
    "{kw-followup}: Heilt allen Charakteren in dieser Spalte 1 Leben.",
    "Schlachtenmagierin",
    "Wann immer dieser Charakter {kw-charge} erhält, heilt er auch 1/2 Leben.",
    "Bannerträger",
    "{kw-followup}: Löst die {kw-counter}-Effekte aller benachbarten Charaktere aus.",
    "Blutsauger",
    "{kw-otherunitdies}: Beschwört eine {kw-summon:170/171}.",
    "Elementalist",
    "Erhält +1 Angriff, wann immer ein verbündeter Elementar beschworen wird. Beschwört nach der ersten Runde eine {kw-summon:165}.",
    "Gefallener Bannerträger",
    "{kw-channelsoul} 1: Alle verbündeten Bogenschützen greifen an. Max. Seelen +1.",
    "Waldgeist",
    "Wenn eine andere verbündete Bestie Schaden erleidet, erhält sie +1 {kw-charge}.",
    "Hellion",
    "{kw-channelblood} 2: Angriff. Wenn dieser Charakter einen Feind tötet, wird 1 Gesundheit/ Figur einen Feind tötet, werden 2 Lebenspunkte wiederhergestellt. Unermüdlich.",
    "Unsterblicher",
    "Verliert am Rundenende keine Rüstung.",
    "Maeledox",
    "Wann immer dieser Charakter {kw-charge} erhält, bekommt er ebenfalls {kw-shield}. {kw-scheme}: {kw-weaken} den nächstgelegenen Gegner.",
    "Waldläufer",
    "Erhält +2/3 {kw-charge}, wann immer ein Verbündeter beschworen wird. Unermüdlich.",
    "Kommandeurin der Königswache",
    "{kw-endofround}: Gewährt allen Charakteren in dieser Splate +1 Rüstung.",
    "Schriftgelehrter",
    "{kw-healthisrecovered}: Gewährt einem zufälligen Verbündeten +1/2 {kw-charge}.",
    "Schmuggler",
    "Wenn du diesen Charakter anheuerst, erhältst du 2 Gold für jeden verbündeten Echsenmenschen. {kw-death}: Erhalte 1/2 Gold.",
    "Seelenleiter",
    "{kw-channelsoul} 1: Regeneriere 1 Leben. {kw-followup}: Erhalte +1 Seele. Max. Seelen +1.",
    "Seelenmagier",
    "{kw-endofround}: Wenn du keine Seelen hast, erhältst du +1/2 Seele und +2/4 {kw-charge}. Max. Seelen +2.",
    "Geisterrufer",
    "{kw-channelblood} 2: {kw-revive} eine verbündete Bestie.",
    "Veninhexe",
    "Beschwört nach der ersten /und zweiten Runde einen {kw-summon:181}. Verursacht doppelten Schaden bei vergifteten Charakteren.",
    "Beschwörer der Leere",
    "{kw-endofround}: Beschwört eine gegnerische {kw-summon:173/174}.",
    "Xerxis",
    "Beschwört nach der ersten Runde eine {kw-summon:180}.",
    "Aeron, der Waldgeist",
    "Heilt 1 Leben, wann immer ein Verbündeter stirbt. {kw-followup}: Alle beschworenen Verbündeten greifen an.",
    "Ares, der verlorene Ritter",
    "Wann immer dieser Charakter Rüstung erhält, bekommt er auch +3 {kw-charge}.",
    "Ayma, die Blitzruferin",
    "{kw-counter}: Gewährt allen anderen Verbündeten +1 {kw-charge}.",
    "Cyril, der Meisterschamane",
    "{kw-death}: Verwandelt sich. Heilt 1 Leben, wann immer ein Verbündeter beschworen wird.",
    "Edric, der Fechtmeister",
    " Greift zweimal an. Unermüdlich.",
    "Ixotl, der Echsenaufseher",
    "{kw-startofbattle} und {kw-death}: Füllt deine Seite mit {kw-summon:179}n auf.",
    "Juggernaut",
    "{kw-endofround}: Erhalte für jede Seele, zufällig +1 {kw-charge} oder regeneriere 1 Leben. Max. Seelen +2.",
    "Lyra, die Morgenröte",
    "{kw-healthisrecovered}: Greift an.",
    "Nangruil, der Alchemist",
    "Erhält {kw-charge}, wann immer ein Verbündeter Rüstung bekommt.",
    "Nyx, vom Alten Mond",
    "{kw-otherunitdies}: {kw-weaken} einen zufälligen Gegner. Unermüdlich.",
    "Tauro, der Verstoßene",
    "Hat +1 Angriff für jede verbündete Bestie. Wenn dieser Charakter einen Feind tötet, stellt er 3 Lebenspunkte wieder her.",
    "Der Verschlinger",
    "Beschwört einen {kw-summon:181}, wann immer ein vergifteter Charakter stirbt.",
    "Die Hohepriesterin",
    "{kw-followup}: Heilt allen Verbündeten 1 Leben.",
    "Ursa, Göttlicher Bär",
    "Wenn ein Verbündeter mit Blutwürfen, angreift. Unermüdlich.",
    "Ven, der Altvordere",
    "Erhält +1 Angriff und heilt 1 Leben, wann immer ein vergifteter Charakter stirbt.",
    "Zed, der Ewige Schelm",
    "Wann immer dieser Charakter {kw-charge} erhält, beschwört er ein unbewegliches {kw-summon:178}.",
    "Zerfallender Schleim",
    "{kw-counter}: Beschwört einen Schleim.",
    "Schleim",
    "Der Unheilsbote",
    "{kw-followup}: Beschwört einen {kw-summon:4}.",
    "Knochenhaufen",
    "{kw-endofround}: Verwandelt sich in ein Skelett.",
    "Skelett",
    "Der Wächter",
    "Greift einen zufälligen Gegner in einer beliebigen Reihe an.",
    "Monsterratte",
    "Minn Fesselbeiss",
    "{kw-endofround}: Wechselt die Reihe.",
    "Goblinschütze",
    "Faxel Fesselbeiss",
    "{kw-counter}: Fügt dem nächstgelegenen Gegner 1 Schaden zu und wechselt dann die Reihe.",
    "Erstarkender Schlick",
    "Heilt 1 Leben, wann immer ein Verbündeter stirbt.",
    "Aufspaltender Schleim",
    "{kw-death}: Beschwört zwei Schleime.",
    "Aziel",
    "Bekommt für jedes verbündete Skelett +1 Angriff. {kw-followup}: Beschwört einen {kw-summon:4}.",
    "Rattenzahn",
    "{kw-endofround}: Beschwöre eine zufällige Bestie.",
    "Kobra",
    "Greift zweimal an.",
    "Fledermaus",
    "Fesselbeiss-Schmied",
    "{kw-endofround}: Gewährt einem zufälligen Verbündeten +4 Rüstung.",
    "Skelettwache",
    "Metallischer Schlick",
    "{kw-endofround}: Erhält +1 Rüstung und bewegt sich danach.",
    "Bitterzahn",
    "{kw-followup}: Gewährt einem zufälligen verbündeten Tier +1 Angriff.",
    "Flit Fesselbeiss",
    "{kw-counter}: Erhält +1 {kw-charge}.",
    "Fial Fesselbeiss",
    "Erhält +1 Angriff, wann immer ein Charakter stirbt.",
    "Der Verschollene Fesselbeiss",
    "{kw-endofround}: Beschwört eine Fledermaus.",
    "Brutmutter",
    "Aaskäfer",
    "{kw-endofround}: Gewährt der Brutmutter +2 Rüstung.",
    "Riesenhafter Schleim",
    "{kw-endofround}: Beschwört zwei Schleime und wechselt die Reihe.",
    "Verhärteter Schleim",
    "Wiederbelebtes Ungetüm",
    "Zwillingshexer",
    "Fürst Fesselbeiss",
    "{kw-endofround}: Beschwört einen Goblinschützen.",
    "Die Gebieterische Kristallkugel",
    "Goblins erhalten +1 Angriff Unsichtbar",
    "Silberzahn",
    "Giftig. {kw-endofround}: Wechselt die Reihe.",
    "Vermoderndes Simulae",
    "{kw-death}: Beschwört ein Kopfloses Simulae.",
    "Kopfloses Simulae",
    "{kw-followup}: Bewegt sich.",
    "Die Brut des Valac",
    "{kw-endofround}: Beschwört ein Wanderndes Auge.",
    "Wanderndes Auge",
    "Greift einen der nächstgelegenen Gegner in einer beliebigen Reihe an.",
    "Der Mahlrufer",
    "{kw-followup}: Heilt einem verletzten Verbündeten 2 Leben.",
    "Werwolf",
    "Königin der Augen",
    "Bekommt +1 Angriff für jeden Verbündeten.",
    "Augenmasse",
    "{kw-death}: Beschwört drei Wandernde Augen. {kw-endofround}: Bewegt sich.",
    "Erwachtes Dickicht",
    "{kw-endofround}: Beschwört zwei Verwunschene Dickichte.",
    "Verwunschenes Dickicht",
    "{kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe 2 Schden zu.",
    "Die Uralte Vettel",
    "Giftig. {kw-endofround}: Beschwört einen zufälligen {kw-summon:2} und bewegt sich danach.",
    "Dieb",
    "Wenn dieser Charakter einen Feind tötet, stiehlt er 1 Gold.",
    "Simulae der Venina",
    "Lähmender Angriff {kw-endofround}: Wechselt die Reihe.",
    "Perfekte Simulae",
    "Wenn dieser Charakter einen Feind tötet, stelle 2 Lebenspunkte wieder her.",
    "Nachahmer",
    "Spinne",
    "Giftig.",
    "Urmutter der Augen",
    "{kw-endofround}: Beschwört zwei Wandernde Augen.",
    "Simulae der Clypaes",
    "{kw-endofround}: Gewährt einem Verbündeten {kw-shield}.",
    "Der Rudelführer",
    "Greift den Gegner mit dem wenigsten Leben an.",
    "Höhlengeist",
    "Simulae der Firis",
    "{kw-counter}: Fügt dem nächstgelegenen Gegner 1 Schaden zu.",
    "Die Böse Zauberin",
    "Gewährt einem Verbündeten +2 Angriff, wann immer ein anderer Verbündeter stirbt.",
    "Der Grauvordere",
    "Erhält +1 Angriff, wann immer ein verbündetes Tier stirbt. {kw-endofround}: Wechselt die Reihe.",
    "Mächtiger Werwolf",
    "{kw-death}: Beschwört zwei Werwölfe. {kw-endofround}: Wechselt die Reihe.",
    "Firis",
    "Clypaes",
    "Venina",
    "Lähmender Angriff {kw-endofround}: Bewegt sich.",
    "Simulae Primus",
    "{kw-followup}: Fügt allen Verbündeten 5 Schaden zu und erhält +1 Angriff.",
    "Der Spiegel",
    "{kw-endofround}: Beschwört ein Simulae. Unsichtbar",
    "Der Augenlose",
    "Greift den Gegner mit dem meisten Leben an. Giftig.",
    "Skorpid",
    "{kw-endofround}: Bewegt sich.",
    "Skelettskorpid",
    "Greift dreimal an.",
    "Der Wandler am Abgrund",
    "{kw-endofround}: Beschwört eine Flammenseele.",
    "Flammenseele",
    "{kw-death}: Gewährt allen Verbündeten +2 {kw-charge}.",
    "Alptraum",
    "{kw-endofround}: Versteinert einen zufälligen Gegner.",
    "Erstarrter Schrecken",
    "{kw-death}: Beschwört einen Schrecken.",
    "Schrecken",
    "Bedrohliche Strahlung",
    "{kw-endofround}: Beschwört zwei Labile Strahlungen und bewegt sich danach.",
    "Labile Strahlung",
    "{kw-endofround}: Fügt ALLEN Charakteren in dieser Reihe 5 Schaden zu.",
    "Der Knecht der Flammen",
    "{kw-followup}: Wechselt die Reihe und erhält +1 Angriff.",
    "Der Prinz der Gluten",
    "Verfluchte Angriffe. Unsichtbar {kw-followup}: Bewegt sich.",
    "Alter Troll",
    "Troll",
    "Glutroter Geist",
    "{kw-endofround}: Erhält +15 Rüstung und bewegt sich danach. Vefügt über einen Angriffsbonus, der dem eigenen Rüstungswert entspricht.",
    "Seelenurne",
    "{kw-death}: Besiege den Glutroten Geist.",
    "Der Knecht der Schatten",
    "Erhält +1 Angriff für jeden Gegner.",
    "Der Prinz der Schatten",
    "Verwirrend Unsichtbar {kw-followup}: Bewegt sich.",
    "Der Hüter des Abgrunds",
    "{kw-endofround}: Beschwört eine Höllenseele.",
    "Höllenseele",
    "{kw-death}: Gewährt dem Hüter des Abgrundes +1 Angriff.",
    "Fleischriese",
    "Angriffe verursachen 2 {kw-affliction}. {kw-endofround}: Wechselt die Reihe.",
    "Fleischmade",
    "Der Knecht der Habgier",
    "Greift zweimal an. {kw-endofround}: Wechselt die Reihe.",
    "Der Güldene Prinz",
    "{kw-followup}: Stiehlt 1 Gold. Unsichtbar",
    "Der Hirnschlürfer",
    "Angriffe verursachen einen zufälligen Statuseffekt. Greift einen zufälligen Gegner an.",
    "Ausgehöhlter Recke",
    "{kw-endofround}: Erhält +1 Angriff und bewegt sich.",
    "Die Hand des Abaddon",
    "Erhält +1 Angriff, wann immer ein verbündetes Monster stirbt. Greift einen der nächstgelegenen Gegner in einer beliebigen Reihe an.",
    "Priester des Abaddon",
    "{kw-counter}: Gewährt der Hand des Abaddon +2 Rüstung.",
    "Priesterin des Abaddon",
    "{kw-counter}: Gewährt der Hand des Abaddon +2 {kw-charge}.",
    "Vorzeitliche Flamme",
    "{kw-followup}: Fügt allen Charakteren in dieser Reihe 2 Schaden zu. {kw-endofround}: Bewegt sich.",
    "Kleinere Schattenflamme",
    "{kw-death}: Beschwöre einen {kw-summon:94}. Unsichtbar",
    "Schattenflamme",
    "{kw-death}: Beschwöre einen {kw-summon:95}. Unsichtbar",
    "Größere Schattenflamme",
    "Unsichtbar",
    "Abaddon",
    "Verwandelt sich jede Runde.",
    "Goldene Sphäre",
    "Verwunschene Sphäre",
    "{kw-death}: Verflucht einen zufälligen Gegner.",
    "Vergiftete Sphäre",
    "{kw-death}: {kw-poison} den Gegner mit dem wenigsten Leben.",
    "Verschlinger der Hoffnung",
    "Charaktere können kein Leben heilen.",
    "Verschlinger der Stärke",
    "Charaktere können keine Rüstung erhalten.",
    "Der Hüter",
    "Greift einen zufälligen Gegner in einer beliebigen Reihe an. Unsichtbar",
    "Illifar",
    "Bathin",
    "Lähmender Angriff Greift den Gegner mit dem meisten Leben an.",
    "Bathin der Mächtige",
    "{kw-death}: Versteinert alle Gegner (Ausnahme: Held).",
    "Andromalius",
    "Angriffe verursachen 2 {kw-affliction}.",
    "Moraxo",
    "{kw-endofround}: Gewährt Illifar +5 Rüstung. Giftig.",
    "Aamon",
    "{kw-endofround}: Gewährt Illifar +3 {kw-charge}.",
    "Haagenti",
    "Der Angriff ignoriert Rüstungen.",
    "Valac",
    "{kw-endofround}: Beschwört ein Wanderndes Auge. Greift einen zufälligen Gegner in einer beliebigen Reihe an.",
    "Orobas",
    "{kw-endofround}: Gewährt allen Verbündeten +1 {kw-charge}. Unsichtbar",
    "Nazzatoth",
    "{kw-endofround}: Beschwört zwei Schatten.",
    "Düsterflammschatten",
    "{kw-endofround}: Beschwört zwei Düsterflammen in seiner Reihe. Unsichtbar",
    "Verwunschener Schatten",
    "Verfluchte Angriffe. Unsichtbar",
    "Heulender Schatten",
    "Betörender Schatten",
    "Verwirrend Unsichtbar",
    "Unbeständiger Schatten",
    "{kw-followup}: Fügt allen Charakteren in dieser Reihe 2 Schaden zu. Unsichtbar",
    "Befallener Schatten",
    "Angriffe verursachen 2 {kw-affliction}. Unsichtbar",
    "Elektrischer Schatten",
    "Greift dreimal an. Unsichtbar",
    "Düsterflamme",
    "Der Hüter der Pforte",
    "Leere",
    "{kw-death}: Verursacht bei einem zufälligen Gegner einen zufälligen Statuseffekt.",
    "{kw-endofround}: Gewährt einem zufälligen Verbündeten +4 {kw-charge}.",
    "Das Auge des Abaddon",
    "Greift den Gegner mit dem meisten Leben an. Unsichtbar",
    "Das Auge des Illifar",
    "Verursacht doppelten Schaden bei gebrechlichen Gegnern. Unsichtbar {kw-endofround}: Wechselt die Reihe.",
    "Das Auge der Nazzatoth",
    "Angriffe verursachen 2 {kw-affliction}. Unsichtbar {kw-endofround}: Wechselt die Reihe.",
    "{kw-endofround}: Beschwört ein Spiegelbild mit einer zufälligen Fähigkeit.",
    "Das Spiegelbild des Hüters",
    "{kw-endofround} und {kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe 10 Schaden zu.",
    "{kw-endofround} und {kw-death}: Fügt allen Gegnern 1 Schaden zu.",
    "{kw-endofround} und {kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe zweimal 4 Schaden zu.",
    "{kw-endofround} und {kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe 5 Schaden zu und verursacht 2 {kw-affliction}.",
    "{kw-endofround} und {kw-death}: Fügt dem Gegner mit dem meisten Leben 3 Schaden zu und versteinert ihn.",
    "Goldmade",
    "{kw-death}: Erhalte 13 Gold. Giftig.",
    "Schlossgespenst",
    "Reduziert den Gegner mit dem meisten Leben auf 1 Leben.",
    "Goldseele",
    "Verschwindet am Ende der zweiten Runde. {kw-endofround}: Wechselt die Reihe.",
    "Schatztruhe",
    "Verirrter Abenteurer",
    "Uralte Urne",
    "Fass",
    "Metallurne",
    "Dickicht",
    "Kann sich nicht bewegen.",
    "Felsblock",
    "Explosives Fass",
    "{kw-death}: Fügt ALLEN Charakteren in dieser Reihe 2 Schaden zu.",
    "Treuer Gefolgsmann",
    "Wird nicht zur maximalen Gruppengröße hinzugerechnet.",
    "Kosmischer Schleim",
    "{kw-endofround}: Gewährt allen verbündeten Elementaren +1 {kw-charge}. Wird nicht zur maximalen Gruppengröße hinzugerechnet.",
    "Goldene Statue",
    "Kann an Lagerfeuern für 10 Gold verkauft werden.",
    "Aussergewöhnliche Statue",
    "Kann an Lagerfeuern für 15 Gold verkauft werden.",
    "Asmodel, der Güldene",
    "{kw-endofround}: Erhält {kw-shield}. Kann an Lagerfeuern für 15 Gold verkauft werden.",
    "Cyril, der Erdenstürzer",
    "Heilt 1 Leben, wann immer ein Verbündeter beschworen wird.",
    "Jack",
    "Taube",
    "Rabe",
    "Streunender Wolf",
    "Immerlodernde Flamme",
    "{kw-endofround}: Gewährt einem Verbündeten +1 {kw-charge}.",
    "Rachegeist",
    "Unermüdlich.",
    "Gewitterseele",
    "{kw-death}: Gewährt allen Verbündeten +1 {kw-charge}.",
    "Weiheseele",
    "{kw-endofround}: Heilt einem verletzten Verbündeten 1 Leben (Ausnahme: Held).",
    "Erzseele",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +1 Rüstung.",
    "Schwache Erzseele",
    "Mächtige Erzseele",
    "Blutseele",
    "Mächtige Blutseele",
    "Schwache Leerseele",
    "Greift sich selbst an. {kw-death}: Fügt allen Verbündeten 1 Schaden zu.",
    "Leerseele",
    "Greift sich selbst an. {kw-death}: Fügt allen Verbündeten 2 Schaden zu.",
    "Mächtige Leerseele",
    "Greift sich selbst an. {kw-death}: Fügt allen Verbündeten 3 Schaden zu.",
    "Bombe",
    "Schwere Bombe",
    "{kw-death}: Fügt ALLEN Charakteren in dieser Reihe 4 Schaden zu.",
    "Goldene Bombe",
    "{kw-death}: Fügt ALLEN Charakteren in dieser Reihe 6 Schaden zu.",
    "Spiegelbild",
    "Jungechse",
    "Giftschuppe",
    "Giftiger Schleim",
    "Blutschatten",
    "{kw-death}: Fügt dem verbündeten Helden 4 Schaden zu.",
    "Geisthammer",
    "{kw-followup}: Erleidet 1 Schaden. Unermüdlich.",
    "Schwerer Geisthammer",
    "Goldender Geisthammer",
    "Wähle deinen Helden",
    "Das Blut des Abaddon: Erhalte 3 Gold.",
    "Das Blut des Illifar: Erhalte einen zufälligen Charakter der Stufe 2.",
    "Das Blut der Nazzatoth: Erhalte einen seltenen Gegenstand.",
    "Die Seele des Hüters: Dein Gruppenlimit wird um 1 erhöht. Die maximale Gesundheit deines Helden ist dauerhaft 1.",
    "Lied des Todes: +25% Punkte Gegnerische Helden haben +1 Angriff.",
    "Lagerfeuer",
    "An Freudenfeuern stehen mehr Charaktere zur Auswahl als an regulären Lagerfeuern. Durch das Freispielen neuer Charaktere schaltest du letztendlich auch neue Freudenfeuer frei.",
    "Oh. Hallo. Braucht ihr ein paar Schlüssel?",
    "Der Händler",
    "Die Hexe",
    "Wähle einen Ring.",
    "Im Schwarzmarkt werden Gegenstände günstiger angeboten als in regulären Läden.",
    "Aamon bietes verfluchte Ringe an. Der genaue Fluch hängt von deinem jeweiligen Helden ab.",
    "Ein Obsidianring - darf ich mal sehen? Sieht aus wie der, den ich vor langer Zeit verloren habe.",
    "weg",
    "held",
    "artefakt",
    "charakter",
    "artikel",
    "wandle",
    "monster",
    "gruppe",
    "Neues Spiel",
    "Neues Spiel+",
    "Neues Spiel++",
    "Neues Spiel+++",
    "Neues Spiel++++",
    "Neues Spiel+++++",
    "Legende",
    "Alle Gebiete",
    "Die Oberen Gewölbe",
    "Die Unteren Sääle",
    "Am Abgrund",
    "Die Pforte"
];
