var L = [
    "",
    "Mensch",
    "Tier",
    "Zwerg",
    "Elementar",
    "Elf",
    "Goblin",
    "Monster",
    "Untoter",
    "Konstrukt",
    "Pflanze",
    "Gnom",
    "Alter Gott",
    "Echsenmensch",
    "Dämon",
    "???",
    "Kämpfer",
    "Zauberer",
    "Bogenschütze",
    "Held",
    "Multiklasse",
    "Gefolgsmann",
    "Nur Vorne",
    "Nur Hinten",
    "-",
    "Angriff",
    "Leben",
    "Eile",
    "Tod",
    "TOD: Bewirkt etwas, wenn der Charakter stirbt.",
    "Rundenende",
    "RUNDENENDE: Bewirkt etwas, sobald alle Charaktere ihre Angriffe beendet haben. Ignoriert Erschöpfung.",
    "Folgeaktion",
    "FOLGEAKTION: Bewirkt etwas, sobald der Charakter seinen Angriff beendet hat.",
    "Gnadenlos",
    "GNADENLOS: Bewirkt etwas, sobald ein Gegner stirbt.",
    "Hoffnung",
    "HOFFNUNG: Bewirkt etwas, sobald das Leben eines Verbündeten erhöht wird.",
    "Intrige",
    "INTRIGE: Bewirkt etwas, sobald der Charakter auf seinen Angriff verzichtet.",
    "Kampfbeginn",
    "KAMPFBEGINN: Bewirkt etwas, bevor der Kampf beginnt.",
    "Seelenbeschwörung",
    "Soulcast X: Gib X Seelen aus, um  eine Fähigkeit zwischen den Runden zu aktivieren. Kann nur einmal pro Runde verwendet werden. Rechtsktlick zum Wirken.",
    "Gift",
    "POISON: Poisoned characters take 1 damage after their normal attack. Lasts until the end of this battle. Does not stack.",
    "Fluch",
    "FLUCH: Der nächste Schaden, den ein Charakter erleidet, wird verdoppelt.",
    "Schild",
    "SCHILD: Der nächste Angriff auf diesen Charakter verursacht keinen Schaden.",
    "Parade",
    "PARADE: Bewirkt etwas, wenn der Charakter Leben verliert (und dies überlebt).",
    "Gebrechen",
    "GEBRECHEN: Gebrechliche Charaktere können kein(e) Leben, Rüstung oder Macht erhalten Zum Rundenende hin wird jeweils ein Gebrechen entfernt.",
    "Macht",
    "MACHT: Der nächste Angriff verursacht erhöhten Schaden.",
    "Rüstung",
    "RÜSTUNG: Die Schadenshöhe, die ein Charakter erleiden kann, bevor er Leben verliert. Rüstung verschwindet mit jedem Rundenende.",
    "Blutwurf",
    "Blutung X: Nimm Schaden, um eine Fähigkeit zwischen den Runden auszulösen. Kann einmal pro Runde verwendet werden. Rechtsklick zum Wirken.",
    "Wiederbeleben",
    "Wiederbelebung: Bringt einen toten Verbündeten mit 1 Lebenspunkt zurück ins Leben.",
    "Manawurf ",
    "Manawurf: Mana ausgeben, um eine Fähigkeit zwischen den Runden auszulösen. Kann einmal pro Runde verwendet werden. Rechtsklick zum Wirken.",
    "Beschworen",
    "Charaktere, die Beschwörungen nutzen und davon profitieren, erscheinen eher an Lagerfeuern.",
    "Stufe",
    "Dieser Charakter kann endlos hochgelevelt werden. Er erhält diesen Bonus auf Stufe 4 und jeder weiteren Stufe.",
    "weg",
    "held",
    "artefakt",
    "charakter",
    "artikel",
    "wandle",
    "monster",
    "gruppe",
    "Lagerfeuer",
    "Rekrutiere oder entlasse Charaktere. Verschiebe angelegte Gegenstände per Rechtsklick.",
    "Freudenfeuer",
    "An Freudenfeuern stehen mehr Charaktere zur Auswahl als an regulären Lagerfeuern. Durch das Freispielen neuer Charaktere schaltest du letztendlich auch neue Freudenfeuer frei.",
    "Schatztruhe",
    "Verwandelt sich in einen zufälligen Gegenstand.",
    "Schatzkammer",
    "Erhalte 3 Gold.",
    "Bathin",
    "Bathin macht dir optionale Angebote, mit denen die Schwierigkeit des nächsten Kampfes erhöht wird. Als Belohnung bietet er dir zusätzliches Gold.",
    "Händler",
    "Kaufe und verkaufe Gegenstände. Verschiebe angelegte Gegenstände per Rechtsklick.",
    "Die Hexe",
    "Du da! Ich habe noch mehr Tränke im Angebot!",
    "Andromalius",
    "Andromalius wird sich in einen Ausrüstungsgegenstand verwandeln.   Entferne einen angelegten Gegenstand per Rechtsklick aus dem Inventar eines Charakters und lege ihn in Der Leere ab.",
    "Der Schlüsselschmied",
    "Oh. Hallo. Braucht ihr ein paar Schlüssel?",
    "Der Oger",
    "Wähle einen Ring.",
    "Schmuggler",
    "Im Schwarzmarkt werden Gegenstände günstiger angeboten als in regulären Läden.",
    "Der Verirrte Zauberer",
    "Ein Obsidianring - darf ich mal sehen? Sieht aus wie der, den ich vor langer Zeit verloren habe.",
    "Aamons Schatzkammer",
    "Aamon bietes verfluchte Ringe an. Der genaue Fluch hängt von deinem jeweiligen Helden ab.",
    "Artefakttruhe",
    "Wähle ein Artefakt",
    "Wähle deinen Helden",
    "Das Blut des Abaddon",
    "Erhalte 8 Gold.",
    "Das Blut des Illifar",
    "Erhalte einen zufälligen Charakter der Stufe 2.",
    "Das Blut der Nazzatoth",
    "Erhalte einen seltenen Gegenstand.",
    "Die Seele des Hüters",
    "Dein Gruppenlimit wird um 1 erhöht. Die maximale Gesundheit deines Helden ist dauerhaft 1.",
    "Lied des Todes",
    "+25% Punkte Gegnerische Helden haben +1 Angriff.",
    "Neues Spiel",
    "Neues Spiel+1",
    "Neues Spiel+2",
    "Neues Spiel+3",
    "Neues Spiel+4",
    "Neues Spiel+5",
    "Legende",
    "Alle Gebiete",
    "Die Oberen Gewölbe",
    "Die Unteren Sääle",
    "Am Abgrund",
    "Die Pforte",
    "Der Turm",
    "Er ist ein echter Pechvogel",
    "Der Verirrte Abenteurer",
    "Der Mahlrufer",
    "{kw-followup}: Heilt einem verletzten Verbündeten 2 Leben.",
    "Der Rudelführer",
    "Greift den Gegner mit dem wenigsten Leben an.",
    "Fürst der Alten Erde",
    "Thoric mit dem Hammer",
    "{kw-endofround}: Erhält +1 Rüstung.",
    "Meisterschmied",
    "{kw-endofround}: Gewährt dem vordersten Verbündeten in dieser Reihe +1 Rüstung.",
    "Die Letzte Astronomin",
    "Eloa",
    "{kw-followup}: Gewährt einem Verbündeten in dieser Reihe +1 {kw-charge}.",
    "Unermüdlich.",
    "Arkane Forscherin",
    "{kw-endofround}: Gewährt einem Zauberer in dieser Reihe +2 {kw-charge}.",
    "Vom Alten Mond",
    "Taz'gyn",
    "{kw-channelmana}: Beschwöre einen feindlichen {kw-summon:0}.",
    "Erleuchteter Beschwörer",
    "Beschwört einen {kw-summon:1}, wann immer dieser Charakter einen Gegner tötet.",
    "Taz'gyn, des Ordens",
    "{kw-otherunitdies}: Erhält +1 {kw-charge}.",
    "Der Reisekoch",
    "Dominique Boutroux",
    "{kw-followup}: Heilt einem verletzen Verbündeten in dieser Reihe 1 Leben.",
    "Die reisende Händlerin",
    "{kw-startofbattle}: Gewinnt 1 Gold.",
    "Sie-Die-Alleine-Schwimmt",
    "Die Weise Gryx",
    "Greift an, wann immer ein Verbündeter stirbt.",
    "Brutmatriarchin",
    "Giftig.",
    "Der Junge Prinz",
    "Xandos III.",
    "Startet mit der Krone der Dämmerung.",
    "Xandos, der Große",
    "Streuner des Wissens",
    "Mariana",
    "{kw-startofbattle}: Beschwört {kw-summon:2}.",
    "Animara",
    "Wenn ein Charakter Blutwürfe, wirkt, erhält er +1 {kw-charge}.",
    "Weit weg",
    "Elsbeth",
    "{kw-channelsoul} 1: Füge dem nächsten Feind 2 Schaden zu. Max. Seelen +1.",
    "Elsbeth, Sumpfhexe",
    "{kw-startofbattle}: Vergifte zwei zufällige Gegner.",
    "Rache-Suchende",
    "Beginnt mit {kw-relic:47}.",
    "Der Goldene Kaiser",
    "Erhält für jeweils 5 Gold +1 Angriff.",
    "Kunsthandwerker",
    "Beginnt mit zwei zusätzlichen zufälligen Relikten.",
    "Erstarkender Schlick",
    "Heilt 1 Leben, wann immer ein Verbündeter stirbt.",
    "Zerfallender Schleim",
    "{kw-counter}: Beschwört einen {kw-summon:42}.",
    "Metallischer Schlick",
    "{kw-endofround}: Erhält +1 Rüstung und bewegt sich danach.",
    "Seher",
    "{kw-otherunitdies}: Fügt einem zufälligen Gegner {kw-scaling:1} Schaden zu.",
    "Kultist",
    "{kw-otherunitdies}: Heilt {kw-scaling:0} Leben.",
    "Berserker",
    "{kw-counter}: Erhält +1/2/3 {kw-charge}.",
    "Klingentänzer",
    "Erhält bei vollem Leben +1/2/3 Angriff.",
    "Zauberwirker",
    "{kw-endofround}: Gewährt allen Zauberern +1 {kw-charge}.",
    "Jäger",
    "{kw-followup}: Fügt dem Gegner mit dem wenigsten Leben 1/2/3 Schaden zu.",
    "Rüstungsschmied",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +{kw-scaling:1} Rüstung.",
    "Sonnenmagier",
    "Erhält doppelte {kw-charge}.",
    "Priester der Erkenntnis",
    "{kw-followup}: Heilt einem verletzen Verbündeten {kw-scaling:0} Leben (Ausnahme: Held).",
    "Priester der Rose",
    "{kw-healthisrecovered}: Fügt dem nächstgelegenen Gegner in dieser Reihe {kw-scaling:0} Schaden zu.",
    "Panzerritter",
    "Vefügt über einen Angriffsbonus, der dem eigenen Rüstungswert entspricht.",
    "Druide",
    "{kw-channelmana:0}: Beschwöre zweimal einen {kw-summon:6/7/8}.",
    "Göttlicher Beschützer",
    "Gewährt Verbündeten {kw-shield}, sobald sie beschworen werden.",
    "Knappe",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +1/2/3 {kw-charge}.",
    "Aguatilis",
    "Erhält +2/3/4 {kw-charge}, wann immer ein Verbündeter stirbt.",
    "Hypogaianer",
    "{kw-scheme}: Heilt sich 1 Leben für verbündeten Echsenmenschen.",
    "Waldläufer",
    "Erhält +1/2/3 {kw-charge}, wann immer ein Verbündeter beschworen wird.",
    "Adept der Verdammnis",
    "Beschworene Verbündete erhalten +{kw-scaling:0} Angriff.",
    "Schurke",
    "Gerber",
    "Erhalte 1 Gold, wann immer dieser Charakter einen Gegner tötet.",
    "Königswache",
    "Wann immer dieser Charakter Leben erhält, bekommt dein Held +1/2/3 {kw-charge}.",
    "Medium",
    "{kw-followup}: Löst alle verbündeten Gnadenlos-Effekte aus.",
    "Speerkämpfer",
    "Greit an, sobald er Rüstung erhält.",
    "Scharfschütze",
    "Wann immer ein Gegner {kw-poison} wird, wird ihm {kw-scaling:0} zusätzlicher Schaden zugefügt.",
    "Praexator",
    "Gewährt allen verbündeten Echsenmenschen +1 {kw-charge}, wann immer dieser Charakter einen Gegner tötet.",
    "Adeptin der Blitze",
    "Wann immer dieser Charakter {kw-charge} erhält, fügt er einem zufälligen Gegner {kw-scaling:0} Schaden zu.",
    "Beschwörer des Stahls",
    "{kw-channelmana:0}: Beschwöre einen {kw-summon:12/13/14}.",
    "Priester der Dunkelheit",
    "Erhält {kw-shield}, wann immer dieser Charakter einen Gegner tötet.",
    "{kw-channelmana:0}: Erhalte {kw-shield}.",
    "Bluthexer",
    "{kw-endofround}: Beschwört einen gegnerischen {kw-summon:15} in dieser Reihe.",
    "Schlachter",
    "Wann immer dieser Charakter einen Gegner tötet, heilt er /zweimal/dreimal einem Verbündeten 1 Leben (Ausnahme: Held).",
    "Venintrinker",
    "Heilt {kw-scaling:0} Leben, wann immer ein vergifteter Charakter stirbt.",
    "Priester des Hammers",
    "{kw-endofround}: Beschwört einen {kw-summon:16/17/18}.",
    "Braumeister",
    "{kw-counter}: Heilt einem verletzten Verbündeten 2 Leben (Ausnahme: Held).",
    "Runenschmied",
    "Erhält +1 {kw-charge}, wann immer ein anderer verbündeter Zwerg Schaden erleidet. {kw-endofround}: Erhält +1 Rüstung für jeden verbündeten Zwerg.",
    "Deadeye",
    "+1 Schaden für jeden anderen verbündeten Untoten.",
    "Tarus-Wache",
    "{kw-channelsoul} 1: Gib allen anderen verbündeten Untoten +1/2/3 Rüstung. Max. Seelen +1.",
    "Seelentrinker",
    "{kw-endofround}: Wenn du 2 oder mehr Seelen hast, regeneriere {kw-scaling:0} Leben. Max. Seelen +2.",
    "Gefallener Adept",
    "{kw-channelsoul} X: Füge dem nächsten Feind in dieser Spur /2/4X Schaden zu. Max. Seelen +3.",
    "Nekromant",
    "{kw-channelsoul} 2: Beschwöre ein {kw-summon:3}. Max. Seelen +2.",
    "Eisenblut",
    "{kw-channelblood} 1: Erhalte +1 Rüstung für jeden beschädigten Verbündeten.",
    "Ember Blut",
    "{kw-channelblood} 2: Erhalte +1 Angriff.",
    "Sonnenhorn",
    "{kw-channelblood} 1: Stelle/t zweimal/e dreimal 1 Lebenspunkt bei einer benachbarten beschädigten Bestie wieder her.",
    "Kriegsbär",
    "{kw-endofround}: Wenn dieser Charakter 1 Gesundheit hat, stelle 1 Gesundheit/2 oder weniger Lebenspunkte hat, stelle 2 Lebenspunkte/3 oder weniger Lebenspunkte hat, stelle 3 Lebenspunkte wieder her.",
    "Adept der Flammen",
    "Schädigt auch Feinde in der gleichen Spalte.",
    "{kw-channelmana:2}: Attacke.",
    "Tüftlerin",
    "{kw-endofround}: Wann immer dieser Charakter {kw-charge} erhält, beschwört er eine {kw-summon:20/21/22}.",
    "Der Zornleiter",
    "{kw-counter}: Greift an.",
    "Schattenschütze",
    "{kw-otherunitdies}: Erhält +1/2/3 {kw-charge}.",
    "Venomant",
    "{kw-followup}: Fügt allen vergifteten Gegnern {kw-scaling:0} Schaden zu.",
    "Praliator",
    "Wann immer dieser Charakter einen Gegner tötet, greift er erneut an.",
    "Veninhexe",
    "Verursacht doppelten Schaden bei vergifteten Charakteren.",
    "{kw-channelmana:0}: Beschwört einen {kw-summon:9}.",
    "Blutsauger",
    "{kw-otherunitdies}: Beschwört eine {kw-summon:10/11}.",
    "Arkanschütze",
    "{kw-endofround}: Gewährt allen verbündeten Zauberern in dieser Spalte +2/3 {kw-charge}.",
    "Meuchelmörder",
    "Gegner erleiden +{kw-scaling:-2} Schaden durch Gifte.",
    "Maeledox",
    "Wann immer dieser Charakter {kw-charge} erhält, bekommt er ebenfalls {kw-shield}. {kw-scheme}: {kw-weaken} den nächstgelegenen Gegner.",
    "Bannerträger",
    "{kw-followup}: Löst die {kw-counter}-Effekte aller benachbarten Charaktere aus.",
    "Xerxis",
    "{kw-channelmana:0}: Beschwöre einen {kw-summon:19}.",
    "Amguanerin",
    "{kw-scheme}: Gewährt allen verbündeten Echsenmenschen +1/2 {kw-charge}.",
    "Seelenleiter",
    "{kw-channelsoul} 1: Regeneriere 1/2 Leben. {kw-followup}: Erhalte +1 Seele. Max. Seelen +1.",
    "Waldgeist",
    "Wenn eine andere verbündete Bestie Schaden erleidet, erhält sie +1/2 {kw-charge}.",
    "Hellion",
    "{kw-channelblood} 2: Angriff. Wenn dieser Charakter einen Feind tötet, wird 1/2 Gesundheit wiederhergestellt.",
    "Geisterrufer",
    "{kw-channelblood} 2: {kw-revive} eine verbündete Bestie.",
    "Gardist der Aviakoraner",
    "{kw-counter}: Beschwört eine {kw-summon:6/7}.",
    "Unsterblicher",
    "Verliert am Rundenende keine Rüstung.",
    "Schlachtenmagierin",
    "Wann immer dieser Charakter {kw-charge} erhält, heilt er auch 1/2 Leben.",
    "Schlachtenpriester",
    "{kw-followup}: Heilt allen Charakteren in dieser Spalte 1 Leben.",
    "Beschwörer der Leere",
    "{kw-endofround}: Beschwört eine gegnerische {kw-summon:23/24}.",
    "Seelenmagier",
    "{kw-endofround}: Wenn du keine Seelen hast, erhältst du +1/2 Seele und +2/4 {kw-charge}. Max. Seelen +2.",
    "Elementalist",
    "Erhält +1 Angriff, wann immer ein verbündeter Elementar beschworen wird.",
    "{kw-channelmana:0}: Beschwöre einen {kw-summon:25}.",
    "Kommandeurin der Königswache",
    "{kw-endofround}: Gewährt allen Charakteren in dieser Splate +1 Rüstung.",
    "Schriftgelehrter",
    "{kw-healthisrecovered}: Gewährt einem zufälligen Verbündeten +1/2 {kw-charge}.",
    "Wenn du diesen Charakter anheuerst, erhältst du 2 Gold für jeden verbündeten Echsenmenschen. {kw-death}: Erhalte 1/2 Gold.",
    "Gefallener Bannerträger",
    "{kw-channelsoul} 1: Alle verbündeten Bogenschützen greifen an. Max. Seelen +1.",
    "Juggernaut",
    "{kw-endofround}: Erhalte für jede Seele, zufällig +1 {kw-charge} oder regeneriere 1 Leben. Max. Seelen +2.",
    "Ares, der verlorene Ritter",
    "Wann immer dieser Charakter Rüstung erhält, bekommt er auch +3 {kw-charge}.",
    "Edric, der Fechtmeister",
    "Greift zweimal an.",
    "Cyril, der Meisterschamane",
    "Heilt 1 Leben, wann immer ein Verbündeter beschworen wird.",
    "{kw-death}: Verwandelt sich.",
    "Ixotl, der Echsenaufseher",
    "{kw-startofbattle} und {kw-death}: Füllt deine Seite mit {kw-summon:27}n auf.",
    "Tauro, der Verstoßene",
    "Hat +1 Angriff für jede verbündete Bestie. Wenn dieser Charakter einen Feind tötet, stellt er 3 Lebenspunkte wieder her.",
    "Zed, der Ewige Schelm",
    "Wann immer dieser Charakter {kw-charge} erhält, beschwört er ein unbewegliches {kw-summon:28}.",
    "Nyx, vom Alten Mond",
    "{kw-otherunitdies}: {kw-weaken} einen zufälligen Gegner.",
    "Lyra, die Morgenröte",
    "Greift einen zufälligen Gegner in einer beliebigen Reihe an.",
    "{kw-healthisrecovered}: Greift an.",
    "Der Verschlinger",
    "Beschwört einen {kw-summon:9}, wann immer ein vergifteter Charakter stirbt.",
    "Ayma, die Blitzruferin",
    "{kw-counter}: Gewährt allen anderen Verbündeten +1 {kw-charge}.",
    "Die Hohepriesterin",
    "{kw-followup}: Heilt allen Verbündeten 1 Leben.",
    "Nangruil, der Alchemist",
    "Erhält {kw-charge}, wann immer ein Verbündeter Rüstung bekommt.",
    "Ven, der Altvordere",
    "Erhält +1 Angriff und heilt 2 Leben, wann immer ein vergifteter Charakter stirbt.",
    "Aeron, der Waldgeist",
    "Heilt 1 Leben, wann immer ein Verbündeter stirbt. {kw-followup}: Alle beschworenen Verbündeten greifen an.",
    "Ursa, Göttlicher Bär",
    "Wenn ein Verbündeter mit Blutwürfen, angreift.",
    "Schwache Leerseele",
    "Greift sich selbst an. {kw-death}: Fügt allen Verbündeten 1 Schaden zu.",
    "Knochenhaufen",
    "{kw-endofround}: Verwandelt sich in ein {kw-summon:3}.",
    "Jack",
    "Skelett",
    "Immerlodernde Flamme",
    "{kw-endofround}: Gewährt einem Verbündeten +1 {kw-charge}.",
    "Weiheseele",
    "{kw-endofround}: Heilt einem verletzten Verbündeten 1 Leben (Ausnahme: Held).",
    "Taube",
    "Rabe",
    "Streunender Wolf",
    "Giftiger Schleim",
    "Blutseele",
    "Mächtige Blutseele",
    "Schwache Erzseele",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +1 Rüstung.",
    "Erzseele",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +2 Rüstung.",
    "Mächtige Erzseele",
    "{kw-endofround}: Gewährt einem anderen Verbündeten in dieser Reihe +3 Rüstung.",
    "Blutschatten",
    "{kw-death}: Fügt dem verbündeten Helden 4 Schaden zu.",
    "Geisthammer",
    "{kw-followup}: Erleidet 1 Schaden.",
    "Schwerer Geisthammer",
    "Goldender Geisthammer",
    "Giftschuppe",
    "Bombe",
    "{kw-death}: Fügt ALLEN Charakteren in dieser Reihe 2 Schaden zu.",
    "Schwere Bombe",
    "{kw-death}: Fügt ALLEN Charakteren in dieser Reihe 4 Schaden zu.",
    "Goldene Bombe",
    "{kw-death}: Fügt ALLEN Charakteren in dieser Reihe 6 Schaden zu.",
    "Leerseele",
    "Greift sich selbst an. {kw-death}: Fügt allen Verbündeten 2 Schaden zu.",
    "Mächtige Leerseele",
    "Greift sich selbst an. {kw-death}: Fügt allen Verbündeten 3 Schaden zu.",
    "Gewitterseele",
    "{kw-death}: Gewährt allen Verbündeten +1 {kw-charge}.",
    "Cyril, der Erdenstürzer",
    "Jungechse",
    "Spiegelbild",
    "Kann sich nicht bewegen.",
    "Kosmischer Schleim",
    "Wird nicht zur maximalen Gruppengröße hinzugerechnet.",
    "{kw-endofround}: Gewährt allen verbündeten Elementaren +1 {kw-charge}.",
    "Asmodel, der Güldene",
    "Kann an Lagerfeuern für 15 Gold verkauft werden.",
    "{kw-endofround}: Erhält {kw-shield}.",
    "Aussergewöhnliche Statue",
    "Goldene Statue",
    "Kann an Lagerfeuern für 10 Gold verkauft werden.",
    "Treuer Gefolgsmann",
    "Dickicht",
    "Goldseele",
    "Verschwindet am Ende der zweiten Runde.",
    "{kw-endofround}: Bewegt sich.",
    "Verirrter Abenteurer",
    "Der Unheilsbote",
    "{kw-followup}: Beschwört einen {kw-summon:1}.",
    "Der Wächter",
    "Greift einen zufälligen Gegner in einer beliebigen Reihe an.",
    "Monsterratte",
    "Schleim",
    "Fass",
    "Minn Fesselbeiss",
    "{kw-endofround}: Wechselt die Reihe.",
    "Goblinschütze",
    "Rattenzahn",
    "{kw-endofround}: Beschwöre eine zufällige Bestie.",
    "Fledermaus",
    "Kobra",
    "Metallurne",
    "Aziel",
    "Bekommt für jedes verbündete {kw-summon:3} +1 Angriff.",
    "Faxel Fesselbeiss",
    "{kw-counter}: Fügt dem nächstgelegenen Gegner 1 Schaden zu und wechselt dann die Reihe.",
    "Explosives Fass",
    "Aufspaltender Schleim",
    "{kw-death}: Beschwört zwei {kw-summon:42}e.",
    "Fesselbeiss-Schmied",
    "{kw-endofround}: Gewährt einem zufälligen Verbündeten +4 Rüstung.",
    "Skelettwache",
    "Bitterzahn",
    "{kw-followup}: Gewährt einem zufälligen verbündeten Tier +1 Angriff.",
    "Flit Fesselbeiss",
    "{kw-counter}: Erhält +1 {kw-charge}.",
    "Fial Fesselbeiss",
    "Erhält +1 Angriff, wann immer ein Charakter stirbt.",
    "Der Verschollene Fesselbeiss",
    "{kw-endofround}: Beschwört eine {kw-summon:48}.",
    "Brutmutter",
    "Aaskäfer",
    "{kw-endofround}: Gewährt der {kw-summon:64} +2 Rüstung.",
    "Wiederbelebtes Ungetüm",
    "Zwillingshexer",
    "Fürst Fesselbeiss",
    "{kw-endofround}: Beschwört einen {kw-summon:46}n.",
    "Die Gebieterische Kristallkugel",
    "Goblins erhalten +1 Angriff",
    "Unsichtbar",
    "Riesenhafter Schleim",
    "{kw-endofround}: Beschwört zwei {kw-summon:42}e und wechselt die Reihe.",
    "Verhärteter Schleim",
    "Die Brut des Valac",
    "{kw-endofround}: Beschwört ein {kw-summon:73}.",
    "Wanderndes Auge",
    "Greift einen der nächstgelegenen Gegner in einer beliebigen Reihe an.",
    "Kopfloses Simulae",
    "{kw-followup}: Bewegt sich.",
    "Augenmasse",
    "{kw-death}: Beschwört drei Wandernde Augen.",
    "Silberzahn",
    "Vermoderndes Simulae",
    "{kw-death}: Beschwört ein {kw-summon:74}.",
    "Uralte Urne",
    "Königin der Augen",
    "Bekommt +1 Angriff für jeden Verbündeten.",
    "Simulae der Venina",
    "Lähmender Angriff",
    "Perfekte Simulae",
    "Wenn dieser Charakter einen Feind tötet, stelle 2 Lebenspunkte wieder her.",
    "Werwolf",
    "Höhlengeist",
    "Verwunschenes Dickicht",
    "{kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe 2 Schden zu.",
    "Erwachtes Dickicht",
    "{kw-endofround}: Beschwört zwei Verwunschene Dickichte.",
    "Spinne",
    "Die Uralte Vettel",
    "{kw-endofround}: Beschwört einen zufälligen Schleim und bewegt sich danach.",
    "Dieb",
    "Wenn dieser Charakter einen Feind tötet, stiehlt er 1 Gold.",
    "Nachahmer",
    "{kw-death}: Erhalte 1 Gold.",
    "Urmutter der Augen",
    "{kw-endofround}: Beschwört zwei Wandernde Augen.",
    "Simulae der Clypaes",
    "{kw-endofround}: Gewährt einem Verbündeten {kw-shield}.",
    "Simulae der Firis",
    "{kw-counter}: Fügt dem nächstgelegenen Gegner 1 Schaden zu.",
    "Die Böse Zauberin",
    "Gewährt einem Verbündeten +2 Angriff, wann immer ein anderer Verbündeter stirbt.",
    "Firis",
    "Venina",
    "Clypaes",
    "Simulae Primus",
    "{kw-followup}: Fügt allen Verbündeten 5 Schaden zu und erhält +1 Angriff.",
    "Der Spiegel",
    "{kw-endofround}: Beschwört ein Simulae.",
    "Der Grauvordere",
    "Erhält +1 Angriff, wann immer ein verbündetes Tier stirbt.",
    "Mächtiger Werwolf",
    "{kw-death}: Beschwört zwei Werwölfe.",
    "Der Augenlose",
    "Greift den Gegner mit dem meisten Leben an.",
    "Skorpid",
    "Skelettskorpid",
    "Greift dreimal an.",
    "Der Knecht der Flammen",
    "{kw-followup}: Wechselt die Reihe und erhält +1 Angriff.",
    "Der Prinz der Gluten",
    "Verfluchte Angriffe.",
    "Flammenseele",
    "{kw-death}: Gewährt allen Verbündeten +2 {kw-charge}.",
    "Der Wandler am Abgrund",
    "{kw-endofround}: Beschwört eine {kw-summon:109}.",
    "Bedrohliche Strahlung",
    "{kw-endofround}: Beschwört zwei {kw-summon:112}en und bewegt sich danach.",
    "Labile Strahlung",
    "{kw-endofround}: Fügt ALLEN Charakteren in dieser Reihe 5 Schaden zu.",
    "Alter Troll",
    "Troll",
    "Alptraum",
    "{kw-endofround}: Versteinert einen zufälligen Gegner.",
    "Erstarrter Schrecken",
    "{kw-death}: Beschwört einen {kw-summon:117}.",
    "Schrecken",
    "Der Knecht der Schatten",
    "Erhält +1 Angriff für jeden Gegner.",
    "Der Prinz der Schatten",
    "Verwirrend",
    "Höllenseele",
    "{kw-death}: Gewährt dem Hüter des Abgrundes +1 Angriff.",
    "Der Hüter des Abgrunds",
    "{kw-endofround}: Beschwört eine {kw-summon:120}.",
    "Seelenurne",
    "{kw-death}: Besiege den Glutroten Geist.",
    "Glutroter Geist",
    "{kw-endofround}: Erhält +15 Rüstung und bewegt sich danach.",
    "Fleischriese",
    "Angriffe verursachen 2 {kw-affliction}.",
    "Fleischmade",
    "Der Knecht der Habgier",
    "Der Güldene Prinz",
    "{kw-followup}: Stiehlt 1 Gold.",
    "Die Hand des Abaddon",
    "Erhält +1 Angriff, wann immer ein verbündetes Monster stirbt.",
    "Priester des Abaddon",
    "{kw-counter}: Gewährt der Hand des Abaddon +2 Rüstung.",
    "Priesterin des Abaddon",
    "{kw-counter}: Gewährt der Hand des Abaddon +2 {kw-charge}.",
    "Vorzeitliche Flamme",
    "{kw-endofround}: Füge allen Charakteren in dieser Gasse 2 Schaden zu, und bewege dich dann.",
    "Felsblock",
    "Kleinere Schattenflamme",
    "{kw-death}: Beschwöre einen {kw-summon:134}.",
    "Schattenflamme",
    "{kw-death}: Beschwöre einen {kw-summon:135}.",
    "Größere Schattenflamme",
    "Der Hirnschlürfer",
    "Angriffe verursachen einen zufälligen Statuseffekt. Greift einen zufälligen Gegner an.",
    "Ausgehöhlter Recke",
    "{kw-endofround}: Erhält +1 Angriff und bewegt sich.",
    "Abaddon",
    "Verwandelt sich jede Runde.",
    "Trägheit",
    "Wollust",
    "Neid",
    "{kw-endofround}: Beschwört eine {kw-summon:142}.",
    "Vergiftete Sphäre",
    "{kw-death}: {kw-poison} den Gegner mit dem wenigsten Leben.",
    "Zorn",
    "Hochmut",
    "Reduziert den Gegner mit dem meisten Leben auf 1 Leben.",
    "Habgier",
    "{kw-endofround}: Beschwört drei {kw-summon:147}n.",
    "Verderbtheit",
    "{kw-endofround}: Beschwört zwei {kw-summon:149}n.",
    "Goldene Sphäre",
    "Völlerei",
    "{kw-endofround}: Beschwört zwei zufällige Verschlinger.",
    "Verwunschene Sphäre",
    "{kw-death}: Verflucht einen zufälligen Gegner.",
    "Verschlinger der Stärke",
    "Charaktere können keine Rüstung erhalten.",
    "Verschlinger der Hoffnung",
    "Charaktere können kein Leben heilen.",
    "Der Hüter",
    "Illifar",
    "Valac",
    "Orobas",
    "Moraxo",
    "{kw-endofround}: Gewährt {kw-summon:153} +5 Rüstung.",
    "Aamon",
    "{kw-endofround}: Gewährt {kw-summon:153} +3 {kw-charge}.",
    "Haagenti",
    "Der Angriff ignoriert Rüstungen.",
    "Bathin der Mächtige",
    "{kw-death}: Versteinert alle Gegner (Ausnahme: Held).",
    "{kw-endofround}: Gewährt allen Verbündeten +1 {kw-charge}.",
    "Befallener Schatten",
    "Nazzatoth",
    "{kw-endofround}: Beschwört zwei Schatten.",
    "Düsterflammschatten",
    "{kw-endofround}: Beschwört zwei {kw-summon:171}n in seiner Reihe.",
    "Elektrischer Schatten",
    "Unbeständiger Schatten",
    "{kw-followup}: Fügt allen Charakteren in dieser Reihe 2 Schaden zu.",
    "Betörender Schatten",
    "Heulender Schatten",
    "Verwunschener Schatten",
    "Düsterflamme",
    "Der Hüter der Pforte",
    "Leere",
    "{kw-death}: Verursacht bei einem zufälligen Gegner einen zufälligen Statuseffekt.",
    "{kw-endofround}: Gewährt einem zufälligen Verbündeten +4 {kw-charge}.",
    "Das Auge der Nazzatoth",
    "Das Auge des Illifar",
    "Verursacht doppelten Schaden bei gebrechlichen Gegnern.",
    "Das Auge des Abaddon",
    "Das Spiegelbild des Hüters",
    "{kw-endofround} und {kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe 5 Schaden zu und verursacht 2 {kw-affliction}.",
    "{kw-endofround}: Beschwört ein Spiegelbild mit einer zufälligen Fähigkeit.",
    "{kw-endofround} und {kw-death}: Fügt allen Gegnern 1 Schaden zu.",
    "{kw-endofround} und {kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe 10 Schaden zu.",
    "{kw-endofround} und {kw-death}: Fügt dem nächstgelegenen Gegner in dieser Reihe zweimal 4 Schaden zu.",
    "{kw-endofround} und {kw-death}: Fügt dem Gegner mit dem meisten Leben 3 Schaden zu und versteinert ihn.",
    "Schlossgespenst",
    "Goldmade",
    "{kw-death}: Erhalte 13 Gold.",
    "Tower King",
    "{kw-endofround}: ???",
    "Turmwache",
    "Erzmage",
    "Königlicher Jäger",
    "{kw-followup}: Fügt einem zufälligen Gegner 1 Schaden zu.",
    "Schmied",
    "Bombsmith",
    "{kw-endofround}: Beschwört einen {kw-summon:20}.",
    "Turmkapitän",
    "{kw-followup}: {kw-weaken} einen zufälligen Gegner.",
    "Königlicher Hexenmeister",
    "Königlicher Schwertkämpfer",
    "Hammer",
    "{kw-endofround}: Beschwört einen {kw-summon:17}.",
    "Trankmeister",
    "Cutthroat",
    "Astronom",
    "{kw-endofround}: Gewährt einem zufälligen Verbündeten +2 {kw-charge}.",
    "Orakel",
    "Turm Ritter",
    "{kw-followup}: Erhalte {kw-shield}.",
    "Krypta -Keeper",
    "{kw-endofround}: Beschwöre zweimal einen {kw-summon:1}.",
    "Tötung",
    "Apotheker",
    "{kw-otherunitdies}: Fügt dem nächstgelegenen Gegner 2 Schaden zu.",
    "Hofnarr",
    "Royal Footman",
    "Sumpfwolf",
    "{kw-endofround}: Heilt 1 Leben.",
    "Riesenkobra",
    "Dämmerung Drache",
    "Mauler",
    "Sandgolem",
    "Spearman",
    "Turmadel",
    "{kw-endofround}: Heilt 2 Leben.",
    "Lakai",
    "Endloser Schleim",
    "Blutmagier",
    "{kw-death}: Beschwört eine {kw-summon:11}.",
    "Dawn Beatle",
    "{kw-startofbattle}: Erhalte {kw-shield}.",
    "Magma Golem",
    "{kw-followup}: Erhaltet +1 Angriff.",
    "Unruhiges Grab",
    "{kw-death}: Beschwört eine {kw-summon:235}.",
    "Leere Golem",
    "{kw-death}: Fügt allen Gegnern 1 Schaden zu.",
    "Jäger",
    "Blade Tänzer",
    "Erhält bei vollem Leben +1 Angriff.",
    "Gerichtsschreiber",
    "{kw-endofround}: Stelle dem verbündeten Helden 1 Gesundheit wieder her.",
    "Inhaftierter Geist",
    "Günstling",
    "Dämmerung Rüstung",
    "{kw-counter}: Erhalte +1 Rüstung.",
    "Infernal Golem",
    "Turmriese",
    "Gerichts Salbei",
    "Dämmerungselementar",
    "{kw-endofround}: Gib dem verbündeten Helden +1 {kw-charge}.",
    "Duellist",
    "Rachegeist",
    "Verfluchte Urne",
    "{kw-death}: {kw-poison} den nächstgelegenen Gegner in dieser Reihe.",
    "Statue -Falle",
    "{kw-death}: Beschwört eine {kw-summon:20}.",
    "Lyras Köcher",
    "Verbündete Bogenschützen erhalten +1 Angriff.",
    "Die Heilige Schrift der Taurianer",
    "Verbündete Tiere und Echsenmenschen erhalten +1 Leben.",
    "Edrics Tagebuch",
    "Verbündete Kämpfer erhalten +1 Angriff, verlieren jedoch 1 Leben.",
    "Hammer der Alten Erde",
    "Verbündete Zwerge und Gnome erhalten +2 Leben.",
    "Der Umhang des Gebieters",
    "Verbündete erhalten +3 Geschwindigkeit.",
    "Der Schmiedehammer",
    "Wann immer ein Verbündeter Rüstung erhält, erhält er zusätzlich +1 Rüstung.",
    "Das Buch des Gesetzes",
    "Verbündete Menschen und Zwerge erhalten +1 Leben.",
    "Thorics Hammer",
    "Verbündete behalten am Ende jeder Runde 1 Rüstung.",
    "Erilaris Gemme",
    "Beschworene Verbündete erhalten +1 Angriff.",
    "Cyrils Stab",
    "Beschworene Verbündete sind unermüdlich.",
    "Essenzsammler",
    "Beschwöre zwei {kw-summon:10}n, wann immer ein nicht-beschworener Verbündeter stirbt.",
    "Immerwährende Fackel",
    "{kw-startofbattle}: Beschwöre eine {kw-summon:4}.",
    "Die Klinge des Gebieters",
    "{kw-startofbattle}: Gewähre deinem Helden +3 {kw-charge} und {kw-shield}.",
    "Seelenfessel",
    "Beim ersten Tod eines Verbündeten wird ein {kw-summon:235} beschworen.",
    "Clypaes' Schutzbann",
    "Erleidet ein Verbündeter Schaden, so erhält er einmalig {kw-shield}.",
    "Essenzdestillator",
    "Beschwöre nach der ersten Runde eine schwache gegnerische {kw-summon:23}.",
    "Das Geheimnis des Kaufmanns",
    "Gegenstände kosten 1 Gold weniger.",
    "Reines Venin",
    "Gegner erleiden durch Gift +2 Schaden.",
    "Veninas Fluch",
    "Falschmünzen",
    "Charaktere kosten an Lagerfeuern 2 Gold weniger.",
    "Königliche Insignien",
    "Eine kostenlose Erneuerung an jedem Lagerfeuer und Laden. {kw-startofbattle}: Dein Held greift an.",
    "Trollblut",
    "Wann immer dein Held einen Gegner tötet, heilt er 2 Leben.",
    "Titanenhammer",
    "{kw-startofbattle}: Gewähre allen Verbündeten 2 Rüstung.",
    "Stab der Amguanerin",
    "Verzichtet ein Verbündeter auf seinen Angriff, so erhält er +1 {kw-charge}.",
    "Heiliger Destillator",
    "Beschwöre nach der ersten Runde eine {kw-summon:5}.",
    "Das Buch der Macht",
    "{kw-endofround}: Gewähre einem zufälligen verbündeten Menschen +1 {kw-charge}.",
    "Ätherische Essenz",
    "Wenn ein Verbündeter seinen Schild verliert, erhält er +1 Angriff.",
    "Jacks Fiedel",
    "Wann immer du ein Lager- oder Freudenfeuer besuchst, erhältst du 3 Gold.",
    "Das Buch der Sterne",
    "{kw-endofround}: Der Zauberer mit der dem wenigsten Leben erhält +1 {kw-charge}.",
    "Der Blitzschnelle Köcher",
    "{kw-startofbattle}: Verbündete Bogenschützen greifen zweimal an.",
    "Feenzauber",
    "Wenn ein Verbündeter beschworen wird, erhält er +2 {kw-charge}.",
    "Stab der Flammen",
    "{kw-startofbattle}: Füge einem zufälligen Gegner 8 Schaden zu.",
    "Stab des Himmels",
    "{kw-startofbattle}: Gibt allen Verbündeten +1 {kw-charge}.",
    "Stab der Leere",
    "{kw-endofround}: Füge einem zufälligen Gegner 1 Schaden zu.",
    "Elementaressenz",
    "Verbündete Elementare erhalten +2 Leben.",
    "Rotglühender Hammer",
    "{kw-endofround}: Gewähre einem zufälligen verbündeten Kämpfer +1 Rüstung.",
    "Bathins Buch",
    "{kw-startofbattle}: Erhalte 1 Gold. Dein Held hat 2 Leben weniger.",
    "Die Verschollene Klinge",
    "Dein Held erhält +1 Angriff und +2 Eile.",
    "Edrics Stiefel",
    "Dein Held greift ein weiteres Mal an.",
    "Essenzklinge",
    "Dein Held hat \\\"{kw-otherunitdies}: Erhalte +1 {kw-charge}.\\\"",
    "Das Buch der Hast",
    "Verbündete Zauberer sind unermüdlich.",
    "Seltsames Gebräu",
    "{kw-startofbattle}: Gewähre jeweils einem verbündeten Echenmensch, Gnom und Elementar +1 Angriff.",
    "Zeichen des Bundes",
    "{kw-startofbattle}: Gewähre jeweils einem verbündeten Mensch, Zwerg und Elf {kw-shield}.",
    "Venindestillator",
    "Wann immer ein vergifteter Charakter stirbt, heilt ein verletzter Verbündeter 1 Leben (Ausnahme: Held).",
    "Krankes Blut",
    "Beschwöre nach der ersten Runde eine gegnerische Blutseele.",
    "Beschwörungsglocke",
    "{kw-startofbattle}: Beschwöre zwei Spektralhämmer.",
    "Seelengefäß",
    "Maximale Seelen +6.",
    "Jacks Gedächtnis",
    "Verbündete Bestien erhalten +1 Lebenspunkte und +2 Geschwindigkeit.",
    "Manastein",
    "Manakastierte Charaktere haben +1 Mana.",
    "Heilige Klinge",
    "Dein Held hat \\\"{kw-healthisrecovered}: Erhalte +1 {kw-charge}.\\\"",
    "Manablade",
    "Wenn ein Charakter manakastiert, erhält dein Held +1 Angriff.",
    "Die Krone der Dämmerung",
    "Deine maximale Gruppengröße wird um 1 erhöht.",
    "Umhang des Gefolgsmanns",
    "Treuetrank",
    "Verwandelt einen {kw-summon:33} in einen Treuen {kw-summon:33}. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Aamons Klinge",
    "{kw-counter}: Erhalte +1 Angriff.",
    "Schwert des Recken",
    "Phönixklinge",
    "Einladung des Todes",
    "Wenn ausgerüstet, sterben.",
    "Ring der Seuchen",
    "{kw-startofbattle}: Werde vergiftet und erhalte 3 Gold.",
    "Ring der Alters",
    "{kw-startofbattle}: Erhalte 3 Gold.",
    "Ring der Sterblichkeit",
    "{kw-startofbattle}: Erleide 1 Schaden und erhalte 3 Gold.",
    "Ring der Schwäche",
    "Heiltrank",
    "Heilt 2 Leben. Verschwindet nach Gebrauch.",
    "Temporaler Trank",
    "Verwandle deinen Helden. Sie verlieren ihre gesamte Ausrüstung.",
    "Schwacher Heiltrank",
    "Heilt 1 Leben. Verschwindet nach Gebrauch.",
    "Starker Heiltrank",
    "Heilt 8 Leben. Verschwindet nach Gebrauch.",
    "Umhang des Übergangs",
    "Umhang des Wandersmanns",
    "Kurzbogen",
    "Der Schattenbogen",
    "Umhang des Plünderers",
    "Beschwöre einen {kw-summon:7}n, wann immer dieser Charakter einen Gegner tötet.",
    "Illiphars Armbrust",
    "Armbrust des Andromalius",
    "Schwacher Rätseltrank",
    "Verwandelt sich in einen zufälligen Gegenstand. Verschwindet nach Gebrauch.",
    "Trank der Wandlung",
    "Verwandelt einen Bogenschützen in einen zufälligen Charakter der Stufe 3. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Essenzphiole",
    "{kw-death}: Beschwöre eine {kw-summon:10}.",
    "Spiegelanhänger",
    "Sein Träger kann nicht versteinert werden.",
    "Seelenlinse",
    "Füge dem nächstgelegenen Gegner 1 Schaden zu, wann immer ein Verbündeter stirbt.",
    "Segen der Clypaes",
    "Stab des Adepten",
    "Sonnenstein",
    "{kw-endofround}: Erhalte +1 {kw-charge}.",
    "Verfluchtes Amulett",
    "Das Sengende Zeichen",
    "Heiliges Szepter",
    "{kw-followup}: Heile einem verletzten Verbündeten 1 Leben (Ausnahme: Held).",
    "Klaue des Andromalius",
    "Trank des Midas",
    "Verwandelt einen Zauberer in eine {kw-summon:32}, die an einem Lagerfeuer für 10 Gold verkauft werden kann. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Starker Trank der Vielseitigkeit",
    "Verwandelt einen Zauberer in eine Multiklasse, so dass er Gegenstände aller Klassen benutzen kann. Verschwindet nach Gebrauch.",
    "Starker Rätseltrank",
    "Hölzerner Kleinschild",
    "Veninschild",
    "{kw-startofbattle}: Sein Träger wird vergiftet.",
    "Kundschafterschild",
    "Verstärkter Kleinschild",
    "Helm der Unsterblichen",
    "{kw-otherunitdies}: Erhalte +1 Rüstung.",
    "Der Titanenwall",
    "Langschild",
    "Vampirhelm",
    "{kw-otherunitdies}: Heile 1 Leben.",
    "Drachenschuppe",
    "Schuppe des Andromalius",
    "Trank der Vielseitigkeit",
    "Verwandelt einen Kämpfer in eine Multiklasse, so dass er Gegenstände aller Klassen benutzen kann. Verschwindet nach Gebrauch.",
    "Spiegeltrank",
    "Verwandelt einen Kämpfer in das einfache Abbild eines zufälligen Verbündeten. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Echsenei",
    "Beschwöre nach der ersten Runde eine {kw-summon:27}.",
    "Reisszahn des Blitzes",
    "Reisszahn des Giftes",
    "Angegriffene Gegner werden vergiftet.",
    "Giftei",
    "Beschwöre nach der ersten Runde eine {kw-summon:19}.",
    "Glücksmünze",
    "Es ist unklar, was die bewirkt.",
    "Todesmorchel",
    "Heile 1 Leben, wann immer ein vergifteter Charakter stirbt.",
    "Giftmorchel",
    "{kw-followup}: Füge allen vergifteten Gegnern 1 Schaden zu.",
    "Lebensmorchel",
    "{kw-followup}: Heile 1 Leben.",
    "Gebrochene Seele",
    "{kw-startofbattle}: Erhalte 1 Seele. Max. Seelen +1.",
    "Schädel-Charme",
    "Nach dem verwenden von Seelenzauber: Erhalte +1 Rüstung.",
    "Rotblutstab",
    "Beschwöre nach der ersten Runde eine {kw-summon:10}.",
    "Grünschuppenstab",
    "{kw-endofround}: Gewähre einem zufälligen beschworenen Verbündeten +1 Rüstung.",
    "Stab der Verwesung",
    "Sternenstein",
    "Gürtel des Midas",
    "Wurfbeil",
    "{kw-counter}: Füge einem zufälligen Gegner 1 Schaden zu.",
    "Berserkeraxt",
    "Erhalte +1 Angriff, sobald dein Leben unter sein Maximum sinkt.",
    "Heilige Axt",
    "Erhält dieser Charakter Leben, so erhält er ebenfalls +1 {kw-charge}.",
    "Gürtel der Unsterblichen",
    "{kw-counter}: Heile 1 Leben.",
    "Ahnen-Edelstein",
    "Taurisches Hackbeil",
    "Fürstlicher Brustpanzer",
    "{kw-death}: Erhalte 2 Gold.",
    "Kettenhemd",
    "Brustpanzer des Märtyrers",
    "{kw-death}: Gewähre allen Verbündeten +1 Angriff.",
    "Brustpanzer des Recken",
    "Lebensblutring",
    "Taubenring",
    "Ein alter Schlüssel",
    "Ring des Gegenvenins",
    "Sein Träger kann nicht vergiftet werden.",
    "Goldener Schlüssel",
    "Der Schlüssel des Schmugglers",
    "Titanenring",
    "{kw-startofbattle}: Erhalte +4 Rüstung.",
    "Gerberhandschuhe",
    "Falkenring",
    "Der Leerzornring",
    "Wann immer dieser Charakter einen Gegner tötet, erleidet ein zufälliger Gegner 1 Schaden.",
    "Verstärkte Handschuhe",
    "{kw-startofbattle}: Erhalte +2 Rüstung.",
    "Ring der Verwesung",
    "Der Seelendieb",
    "Heile 1 Leben, wann immer dieser Charakter einen Gegner tötet.",
    "Thorics Ring",
    "Anmut des Todes",
    "Wenn dieser Charakter sterben würde, zerstöre dies stattdessen.",
    "Heilgürtel",
    "Schädel der Leere",
    "Panzerhandschuhe",
    "Diamantring",
    "Pfortenschlüssel",
    "Saphirbrosche",
    "Aschehaufen",
    "Obsidianring",
    "Ein uralter Ring der Umformung",
    "Obsidianbrosche",
    "Smaragdring",
    "Amethystring",
    "Rubinring",
    "Topasring",
    "Die Gabe des Todes",
    "+25% Punkte",
    "Schatten des Todes",
    "{kw-counter}: Erhalte {kw-shield}.",
    "Trank der Erfahrung",
    "Erhalte +1 XP. Verschwindet nach Gebrauch.",
    "Erhalte +1 XP. Charaktere, die in diesem Kampf gestorben sind, können keine XP bekommen. Verschwindet nach Gebrauch.",
    "Trank der Meisterschaft",
    "Erhalte +3 XP. Verschwindet nach Gebrauch.",
    "Kosmischer Trank",
    "Verwandelt einen Charakter in einen Kosmischen Schleim. Der Charakter verliert all seine Gegenstände. Verschwindet nach Gebrauch.",
    "Sack voller Gold",
    "Starker Trank der Erfahrung",
    "Erhalte +2 XP. Charaktere, die in diesem Kampf gestorben sind, können keine XP bekommen. Verschwindet nach Gebrauch."
];
